package modelo;

// Generated 10/02/2012 11:18:51 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ComisionActividad generated by hbm2java
 */
@Entity
@Table(name = "comision_actividad", schema = "public")
public class ComisionActividad implements java.io.Serializable {

	private int codigoComisionActividad;
	private Actividad actividad;
	private int codigoComision;

	public ComisionActividad() {
	}

	public ComisionActividad(int codigoComisionActividad, Actividad actividad,
			int codigoComision) {
		this.codigoComisionActividad = codigoComisionActividad;
		this.actividad = actividad;
		this.codigoComision = codigoComision;
	}

	@Id
	@Column(name = "codigo_comision_actividad", unique = true, nullable = false)
	public int getCodigoComisionActividad() {
		return this.codigoComisionActividad;
	}

	public void setCodigoComisionActividad(int codigoComisionActividad) {
		this.codigoComisionActividad = codigoComisionActividad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_actividad", nullable = false)
	public Actividad getActividad() {
		return this.actividad;
	}

	public void setActividad(Actividad actividad) {
		this.actividad = actividad;
	}

	@Column(name = "codigo_comision", nullable = false)
	public int getCodigoComision() {
		return this.codigoComision;
	}

	public void setCodigoComision(int codigoComision) {
		this.codigoComision = codigoComision;
	}

}
