package modelo;

// Generated 10/02/2012 11:18:51 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ComisionActividadPlanificada generated by hbm2java
 */
@Entity
@Table(name = "comision_actividad_planificada", schema = "public")
public class ComisionActividadPlanificada implements java.io.Serializable {

	private int codigoComisionActividadPlan;
	private int codigoPlanificacionActividad;
	private int codigoComision;

	public ComisionActividadPlanificada() {
	}

	public ComisionActividadPlanificada(int codigoComisionActividadPlan,
			int codigoPlanificacionActividad, int codigoComision) {
		this.codigoComisionActividadPlan = codigoComisionActividadPlan;
		this.codigoPlanificacionActividad = codigoPlanificacionActividad;
		this.codigoComision = codigoComision;
	}

	@Id
	@Column(name = "codigo_comision_actividad_plan", unique = true, nullable = false)
	public int getCodigoComisionActividadPlan() {
		return this.codigoComisionActividadPlan;
	}

	public void setCodigoComisionActividadPlan(int codigoComisionActividadPlan) {
		this.codigoComisionActividadPlan = codigoComisionActividadPlan;
	}

	@Column(name = "codigo_planificacion_actividad", nullable = false)
	public int getCodigoPlanificacionActividad() {
		return this.codigoPlanificacionActividad;
	}

	public void setCodigoPlanificacionActividad(int codigoPlanificacionActividad) {
		this.codigoPlanificacionActividad = codigoPlanificacionActividad;
	}

	@Column(name = "codigo_comision", nullable = false)
	public int getCodigoComision() {
		return this.codigoComision;
	}

	public void setCodigoComision(int codigoComision) {
		this.codigoComision = codigoComision;
	}

}
