package modelo;

// Generated 10/02/2012 11:18:51 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CondicionCompetencia generated by hbm2java
 */
@Entity
@Table(name = "condicion_competencia", schema = "public")
public class CondicionCompetencia implements java.io.Serializable {

	private int codigoCondicionCompetencia;
	private ClasificacionCompetencia clasificacionCompetencia;
	private int codigoCondicion;
	private char estatus;

	public CondicionCompetencia() {
	}

	public CondicionCompetencia(int codigoCondicionCompetencia,
			ClasificacionCompetencia clasificacionCompetencia,
			int codigoCondicion, char estatus) {
		this.codigoCondicionCompetencia = codigoCondicionCompetencia;
		this.clasificacionCompetencia = clasificacionCompetencia;
		this.codigoCondicion = codigoCondicion;
		this.estatus = estatus;
	}

	@Id
	@Column(name = "codigo_condicion_competencia", unique = true, nullable = false)
	public int getCodigoCondicionCompetencia() {
		return this.codigoCondicionCompetencia;
	}

	public void setCodigoCondicionCompetencia(int codigoCondicionCompetencia) {
		this.codigoCondicionCompetencia = codigoCondicionCompetencia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_clasificacion_competencia", nullable = false)
	public ClasificacionCompetencia getClasificacionCompetencia() {
		return this.clasificacionCompetencia;
	}

	public void setClasificacionCompetencia(
			ClasificacionCompetencia clasificacionCompetencia) {
		this.clasificacionCompetencia = clasificacionCompetencia;
	}

	@Column(name = "codigo_condicion", nullable = false)
	public int getCodigoCondicion() {
		return this.codigoCondicion;
	}

	public void setCodigoCondicion(int codigoCondicion) {
		this.codigoCondicion = codigoCondicion;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

}
