package modelo;

// Generated 10/02/2012 11:18:51 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DatoAcademico generated by hbm2java
 */
@Entity
@Table(name = "dato_academico", schema = "public")
public class DatoAcademico implements java.io.Serializable {

	private int codigoAcademico;
	private Institucion institucion;
	private String cedulaRif;
	private int codigoAnnoEscolar;
	private int codigoCurso;
	private Date fechaIngreso;
	private char estatus;
	private Set<DocumentoAcademico> documentoAcademicos = new HashSet<DocumentoAcademico>(
			0);

	public DatoAcademico() {
	}

	public DatoAcademico(int codigoAcademico, Institucion institucion,
			String cedulaRif, int codigoAnnoEscolar, int codigoCurso,
			Date fechaIngreso, char estatus) {
		this.codigoAcademico = codigoAcademico;
		this.institucion = institucion;
		this.cedulaRif = cedulaRif;
		this.codigoAnnoEscolar = codigoAnnoEscolar;
		this.codigoCurso = codigoCurso;
		this.fechaIngreso = fechaIngreso;
		this.estatus = estatus;
	}

	public DatoAcademico(int codigoAcademico, Institucion institucion,
			String cedulaRif, int codigoAnnoEscolar, int codigoCurso,
			Date fechaIngreso, char estatus,
			Set<DocumentoAcademico> documentoAcademicos) {
		this.codigoAcademico = codigoAcademico;
		this.institucion = institucion;
		this.cedulaRif = cedulaRif;
		this.codigoAnnoEscolar = codigoAnnoEscolar;
		this.codigoCurso = codigoCurso;
		this.fechaIngreso = fechaIngreso;
		this.estatus = estatus;
		this.documentoAcademicos = documentoAcademicos;
	}

	@Id
	@Column(name = "codigo_academico", unique = true, nullable = false)
	public int getCodigoAcademico() {
		return this.codigoAcademico;
	}

	public void setCodigoAcademico(int codigoAcademico) {
		this.codigoAcademico = codigoAcademico;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_institucion", nullable = false)
	public Institucion getInstitucion() {
		return this.institucion;
	}

	public void setInstitucion(Institucion institucion) {
		this.institucion = institucion;
	}

	@Column(name = "cedula_rif", nullable = false)
	public String getCedulaRif() {
		return this.cedulaRif;
	}

	public void setCedulaRif(String cedulaRif) {
		this.cedulaRif = cedulaRif;
	}

	@Column(name = "codigo_anno_escolar", nullable = false)
	public int getCodigoAnnoEscolar() {
		return this.codigoAnnoEscolar;
	}

	public void setCodigoAnnoEscolar(int codigoAnnoEscolar) {
		this.codigoAnnoEscolar = codigoAnnoEscolar;
	}

	@Column(name = "codigo_curso", nullable = false)
	public int getCodigoCurso() {
		return this.codigoCurso;
	}

	public void setCodigoCurso(int codigoCurso) {
		this.codigoCurso = codigoCurso;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_ingreso", nullable = false, length = 13)
	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "datoAcademico")
	public Set<DocumentoAcademico> getDocumentoAcademicos() {
		return this.documentoAcademicos;
	}

	public void setDocumentoAcademicos(
			Set<DocumentoAcademico> documentoAcademicos) {
		this.documentoAcademicos = documentoAcademicos;
	}

}
