package modelo;

// Generated 10/02/2012 11:18:51 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DatoSocial generated by hbm2java
 */
@Entity
@Table(name = "dato_social", schema = "public")
public class DatoSocial implements java.io.Serializable {

	private int codigoDatoSocial;
	private Institucion institucion;
	private String cedulaRif;
	private int codigoActividadSocial;
	private Integer horasDedicadas;
	private Date fechaInicio;
	private char estatus;

	public DatoSocial() {
	}

	public DatoSocial(int codigoDatoSocial, Institucion institucion,
			String cedulaRif, int codigoActividadSocial, char estatus) {
		this.codigoDatoSocial = codigoDatoSocial;
		this.institucion = institucion;
		this.cedulaRif = cedulaRif;
		this.codigoActividadSocial = codigoActividadSocial;
		this.estatus = estatus;
	}

	public DatoSocial(int codigoDatoSocial, Institucion institucion,
			String cedulaRif, int codigoActividadSocial,
			Integer horasDedicadas, Date fechaInicio, char estatus) {
		this.codigoDatoSocial = codigoDatoSocial;
		this.institucion = institucion;
		this.cedulaRif = cedulaRif;
		this.codigoActividadSocial = codigoActividadSocial;
		this.horasDedicadas = horasDedicadas;
		this.fechaInicio = fechaInicio;
		this.estatus = estatus;
	}

	@Id
	@Column(name = "codigo_dato_social", unique = true, nullable = false)
	public int getCodigoDatoSocial() {
		return this.codigoDatoSocial;
	}

	public void setCodigoDatoSocial(int codigoDatoSocial) {
		this.codigoDatoSocial = codigoDatoSocial;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_institucion", nullable = false)
	public Institucion getInstitucion() {
		return this.institucion;
	}

	public void setInstitucion(Institucion institucion) {
		this.institucion = institucion;
	}

	@Column(name = "cedula_rif", nullable = false)
	public String getCedulaRif() {
		return this.cedulaRif;
	}

	public void setCedulaRif(String cedulaRif) {
		this.cedulaRif = cedulaRif;
	}

	@Column(name = "codigo_actividad_social", nullable = false)
	public int getCodigoActividadSocial() {
		return this.codigoActividadSocial;
	}

	public void setCodigoActividadSocial(int codigoActividadSocial) {
		this.codigoActividadSocial = codigoActividadSocial;
	}

	@Column(name = "horas_dedicadas")
	public Integer getHorasDedicadas() {
		return this.horasDedicadas;
	}

	public void setHorasDedicadas(Integer horasDedicadas) {
		this.horasDedicadas = horasDedicadas;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_inicio", length = 13)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

}
