package modelo;

// Generated 10/02/2012 11:18:51 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DocumentoAcreedorMaterial generated by hbm2java
 */
@Entity
@Table(name = "documento_acreedor_material", schema = "public")
public class DocumentoAcreedorMaterial implements java.io.Serializable {

	private DocumentoAcreedorMaterialId id;
	private char estatus;
	private int cantidad;

	public DocumentoAcreedorMaterial() {
	}

	public DocumentoAcreedorMaterial(DocumentoAcreedorMaterialId id,
			char estatus, int cantidad) {
		this.id = id;
		this.estatus = estatus;
		this.cantidad = cantidad;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codigoMaterial", column = @Column(name = "codigo_material", nullable = false)),
			@AttributeOverride(name = "codigoDocumentoAcreedor", column = @Column(name = "codigo_documento_acreedor", nullable = false)) })
	public DocumentoAcreedorMaterialId getId() {
		return this.id;
	}

	public void setId(DocumentoAcreedorMaterialId id) {
		this.id = id;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@Column(name = "cantidad", nullable = false)
	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

}
