package modelo;

// Generated 10/02/2012 11:18:51 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FamiliarJugador generated by hbm2java
 */
@Entity
@Table(name = "familiar_jugador", schema = "public")
public class FamiliarJugador implements java.io.Serializable {

	private int codigoFamiliarJugador;
	private Familiar familiar;
	private String cedulaRif;
	private int codigoParentesco;
	private boolean representanteActual;
	private Date fechaIngreso;
	private char estatus;
	private Set<ComisionFamiliar> comisionFamiliars = new HashSet<ComisionFamiliar>(
			0);
	private Representante representante;
	private Set<Hospedaje> hospedajes = new HashSet<Hospedaje>(0);

	public FamiliarJugador() {
	}

	public FamiliarJugador(int codigoFamiliarJugador, Familiar familiar,
			String cedulaRif, int codigoParentesco,
			boolean representanteActual, Date fechaIngreso, char estatus) {
		this.codigoFamiliarJugador = codigoFamiliarJugador;
		this.familiar = familiar;
		this.cedulaRif = cedulaRif;
		this.codigoParentesco = codigoParentesco;
		this.representanteActual = representanteActual;
		this.fechaIngreso = fechaIngreso;
		this.estatus = estatus;
	}

	public FamiliarJugador(int codigoFamiliarJugador, Familiar familiar,
			String cedulaRif, int codigoParentesco,
			boolean representanteActual, Date fechaIngreso, char estatus,
			Set<ComisionFamiliar> comisionFamiliars,
			Representante representante, Set<Hospedaje> hospedajes) {
		this.codigoFamiliarJugador = codigoFamiliarJugador;
		this.familiar = familiar;
		this.cedulaRif = cedulaRif;
		this.codigoParentesco = codigoParentesco;
		this.representanteActual = representanteActual;
		this.fechaIngreso = fechaIngreso;
		this.estatus = estatus;
		this.comisionFamiliars = comisionFamiliars;
		this.representante = representante;
		this.hospedajes = hospedajes;
	}

	@Id
	@Column(name = "codigo_familiar_jugador", unique = true, nullable = false)
	public int getCodigoFamiliarJugador() {
		return this.codigoFamiliarJugador;
	}

	public void setCodigoFamiliarJugador(int codigoFamiliarJugador) {
		this.codigoFamiliarJugador = codigoFamiliarJugador;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cedula_familiar", nullable = false)
	public Familiar getFamiliar() {
		return this.familiar;
	}

	public void setFamiliar(Familiar familiar) {
		this.familiar = familiar;
	}

	@Column(name = "cedula_rif", nullable = false)
	public String getCedulaRif() {
		return this.cedulaRif;
	}

	public void setCedulaRif(String cedulaRif) {
		this.cedulaRif = cedulaRif;
	}

	@Column(name = "codigo_parentesco", nullable = false)
	public int getCodigoParentesco() {
		return this.codigoParentesco;
	}

	public void setCodigoParentesco(int codigoParentesco) {
		this.codigoParentesco = codigoParentesco;
	}

	@Column(name = "representante_actual", nullable = false)
	public boolean isRepresentanteActual() {
		return this.representanteActual;
	}

	public void setRepresentanteActual(boolean representanteActual) {
		this.representanteActual = representanteActual;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_ingreso", nullable = false, length = 13)
	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "familiarJugador")
	public Set<ComisionFamiliar> getComisionFamiliars() {
		return this.comisionFamiliars;
	}

	public void setComisionFamiliars(Set<ComisionFamiliar> comisionFamiliars) {
		this.comisionFamiliars = comisionFamiliars;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "familiarJugador")
	public Representante getRepresentante() {
		return this.representante;
	}

	public void setRepresentante(Representante representante) {
		this.representante = representante;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "familiarJugador")
	public Set<Hospedaje> getHospedajes() {
		return this.hospedajes;
	}

	public void setHospedajes(Set<Hospedaje> hospedajes) {
		this.hospedajes = hospedajes;
	}

}
