package modelo;

// Generated 10/02/2012 11:18:51 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * IngresoDocumentoAcreedor generated by hbm2java
 */
@Entity
@Table(name = "ingreso_documento_acreedor", schema = "public")
public class IngresoDocumentoAcreedor implements java.io.Serializable {

	private IngresoDocumentoAcreedorId id;
	private Ingreso ingreso;
	private double montoAbonado;
	private char estatus;

	public IngresoDocumentoAcreedor() {
	}

	public IngresoDocumentoAcreedor(IngresoDocumentoAcreedorId id,
			Ingreso ingreso, double montoAbonado, char estatus) {
		this.id = id;
		this.ingreso = ingreso;
		this.montoAbonado = montoAbonado;
		this.estatus = estatus;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codigoDocumentoAcreedor", column = @Column(name = "codigo_documento_acreedor", nullable = false)),
			@AttributeOverride(name = "codigoIngreso", column = @Column(name = "codigo_ingreso", nullable = false)) })
	public IngresoDocumentoAcreedorId getId() {
		return this.id;
	}

	public void setId(IngresoDocumentoAcreedorId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_ingreso", nullable = false, insertable = false, updatable = false)
	public Ingreso getIngreso() {
		return this.ingreso;
	}

	public void setIngreso(Ingreso ingreso) {
		this.ingreso = ingreso;
	}

	@Column(name = "monto_abonado", nullable = false, precision = 17, scale = 17)
	public double getMontoAbonado() {
		return this.montoAbonado;
	}

	public void setMontoAbonado(double montoAbonado) {
		this.montoAbonado = montoAbonado;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

}
