package modelo;

// Generated 10/02/2012 11:18:51 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * IngresoFormaPago generated by hbm2java
 */
@Entity
@Table(name = "ingreso_forma_pago", schema = "public")
public class IngresoFormaPago implements java.io.Serializable {

	private IngresoFormaPagoId id;
	private Ingreso ingreso;
	private DatoBasico datoBasico;
	private Integer codigoFormaPago;
	private Integer codigoBanco;
	private double monto;
	private char estatus;
	private String numeroDocumentoPago;

	public IngresoFormaPago() {
	}

	public IngresoFormaPago(IngresoFormaPagoId id, Ingreso ingreso,
			double monto, char estatus) {
		this.id = id;
		this.ingreso = ingreso;
		this.monto = monto;
		this.estatus = estatus;
	}

	public IngresoFormaPago(IngresoFormaPagoId id, Ingreso ingreso,
			DatoBasico datoBasico, Integer codigoFormaPago,
			Integer codigoBanco, double monto, char estatus,
			String numeroDocumentoPago) {
		this.id = id;
		this.ingreso = ingreso;
		this.datoBasico = datoBasico;
		this.codigoFormaPago = codigoFormaPago;
		this.codigoBanco = codigoBanco;
		this.monto = monto;
		this.estatus = estatus;
		this.numeroDocumentoPago = numeroDocumentoPago;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codigoIngresoFormaPago", column = @Column(name = "codigo_ingreso_forma_pago", nullable = false)),
			@AttributeOverride(name = "codigoIngreso", column = @Column(name = "codigo_ingreso", nullable = false)) })
	public IngresoFormaPagoId getId() {
		return this.id;
	}

	public void setId(IngresoFormaPagoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_ingreso", nullable = false, insertable = false, updatable = false)
	public Ingreso getIngreso() {
		return this.ingreso;
	}

	public void setIngreso(Ingreso ingreso) {
		this.ingreso = ingreso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_tarjeta")
	public DatoBasico getDatoBasico() {
		return this.datoBasico;
	}

	public void setDatoBasico(DatoBasico datoBasico) {
		this.datoBasico = datoBasico;
	}

	@Column(name = "codigo_forma_pago")
	public Integer getCodigoFormaPago() {
		return this.codigoFormaPago;
	}

	public void setCodigoFormaPago(Integer codigoFormaPago) {
		this.codigoFormaPago = codigoFormaPago;
	}

	@Column(name = "codigo_banco")
	public Integer getCodigoBanco() {
		return this.codigoBanco;
	}

	public void setCodigoBanco(Integer codigoBanco) {
		this.codigoBanco = codigoBanco;
	}

	@Column(name = "monto", nullable = false, precision = 17, scale = 17)
	public double getMonto() {
		return this.monto;
	}

	public void setMonto(double monto) {
		this.monto = monto;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@Column(name = "numero_documento_pago")
	public String getNumeroDocumentoPago() {
		return this.numeroDocumentoPago;
	}

	public void setNumeroDocumentoPago(String numeroDocumentoPago) {
		this.numeroDocumentoPago = numeroDocumentoPago;
	}

}
