package modelo;

// Generated 10/02/2012 11:18:51 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PersonalActividadPlanificada generated by hbm2java
 */
@Entity
@Table(name = "personal_actividad_planificada", schema = "public")
public class PersonalActividadPlanificada implements java.io.Serializable {

	private int codigoPersonalActividadPlan;
	private Personal personal;
	private int codigoPlanificacionActividad;
	private char estatus;
	private Set<TareaActividadPlanificada> tareaActividadPlanificadas = new HashSet<TareaActividadPlanificada>(
			0);

	public PersonalActividadPlanificada() {
	}

	public PersonalActividadPlanificada(int codigoPersonalActividadPlan,
			Personal personal, int codigoPlanificacionActividad, char estatus) {
		this.codigoPersonalActividadPlan = codigoPersonalActividadPlan;
		this.personal = personal;
		this.codigoPlanificacionActividad = codigoPlanificacionActividad;
		this.estatus = estatus;
	}

	public PersonalActividadPlanificada(int codigoPersonalActividadPlan,
			Personal personal, int codigoPlanificacionActividad, char estatus,
			Set<TareaActividadPlanificada> tareaActividadPlanificadas) {
		this.codigoPersonalActividadPlan = codigoPersonalActividadPlan;
		this.personal = personal;
		this.codigoPlanificacionActividad = codigoPlanificacionActividad;
		this.estatus = estatus;
		this.tareaActividadPlanificadas = tareaActividadPlanificadas;
	}

	@Id
	@Column(name = "codigo_personal_actividad_plan", unique = true, nullable = false)
	public int getCodigoPersonalActividadPlan() {
		return this.codigoPersonalActividadPlan;
	}

	public void setCodigoPersonalActividadPlan(int codigoPersonalActividadPlan) {
		this.codigoPersonalActividadPlan = codigoPersonalActividadPlan;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cedula_rif", nullable = false)
	public Personal getPersonal() {
		return this.personal;
	}

	public void setPersonal(Personal personal) {
		this.personal = personal;
	}

	@Column(name = "codigo_planificacion_actividad", nullable = false)
	public int getCodigoPlanificacionActividad() {
		return this.codigoPlanificacionActividad;
	}

	public void setCodigoPlanificacionActividad(int codigoPlanificacionActividad) {
		this.codigoPlanificacionActividad = codigoPlanificacionActividad;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personalActividadPlanificada")
	public Set<TareaActividadPlanificada> getTareaActividadPlanificadas() {
		return this.tareaActividadPlanificadas;
	}

	public void setTareaActividadPlanificadas(
			Set<TareaActividadPlanificada> tareaActividadPlanificadas) {
		this.tareaActividadPlanificadas = tareaActividadPlanificadas;
	}

}
