package modelo;

// Generated 28/01/2012 11:49:55 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PersonalEquipoCompetenciaId generated by hbm2java
 */
@Embeddable
public class PersonalEquipoCompetenciaId implements java.io.Serializable {

	private int codigoPersonalEquipo;
	private int codigoCompetencia;

	public PersonalEquipoCompetenciaId() {
	}

	public PersonalEquipoCompetenciaId(int codigoPersonalEquipo,
			int codigoCompetencia) {
		this.codigoPersonalEquipo = codigoPersonalEquipo;
		this.codigoCompetencia = codigoCompetencia;
	}

	@Column(name = "codigo_personal_equipo", nullable = false)
	public int getCodigoPersonalEquipo() {
		return this.codigoPersonalEquipo;
	}

	public void setCodigoPersonalEquipo(int codigoPersonalEquipo) {
		this.codigoPersonalEquipo = codigoPersonalEquipo;
	}

	@Column(name = "codigo_competencia", nullable = false)
	public int getCodigoCompetencia() {
		return this.codigoCompetencia;
	}

	public void setCodigoCompetencia(int codigoCompetencia) {
		this.codigoCompetencia = codigoCompetencia;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PersonalEquipoCompetenciaId))
			return false;
		PersonalEquipoCompetenciaId castOther = (PersonalEquipoCompetenciaId) other;

		return (this.getCodigoPersonalEquipo() == castOther
				.getCodigoPersonalEquipo())
				&& (this.getCodigoCompetencia() == castOther
						.getCodigoCompetencia());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoPersonalEquipo();
		result = 37 * result + this.getCodigoCompetencia();
		return result;
	}

}
