package modelo;

// Generated 10/02/2012 11:18:51 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RecaudoPorProceso generated by hbm2java
 */
@Entity
@Table(name = "recaudo_por_proceso", schema = "public")
public class RecaudoPorProceso implements java.io.Serializable {

	private int codigoRecaudoPorProceso;
	private int codigoImportancia;
	private int codigoProceso;
	private int codigoDocumento;
	private Integer cantidad;
	private char estatus;
	private Set<DocumentoEntregado> documentoEntregados = new HashSet<DocumentoEntregado>(
			0);

	public RecaudoPorProceso() {
	}

	public RecaudoPorProceso(int codigoRecaudoPorProceso,
			int codigoImportancia, int codigoProceso, int codigoDocumento,
			char estatus) {
		this.codigoRecaudoPorProceso = codigoRecaudoPorProceso;
		this.codigoImportancia = codigoImportancia;
		this.codigoProceso = codigoProceso;
		this.codigoDocumento = codigoDocumento;
		this.estatus = estatus;
	}

	public RecaudoPorProceso(int codigoRecaudoPorProceso,
			int codigoImportancia, int codigoProceso, int codigoDocumento,
			Integer cantidad, char estatus,
			Set<DocumentoEntregado> documentoEntregados) {
		this.codigoRecaudoPorProceso = codigoRecaudoPorProceso;
		this.codigoImportancia = codigoImportancia;
		this.codigoProceso = codigoProceso;
		this.codigoDocumento = codigoDocumento;
		this.cantidad = cantidad;
		this.estatus = estatus;
		this.documentoEntregados = documentoEntregados;
	}

	@Id
	@Column(name = "codigo_recaudo_por_proceso", unique = true, nullable = false)
	public int getCodigoRecaudoPorProceso() {
		return this.codigoRecaudoPorProceso;
	}

	public void setCodigoRecaudoPorProceso(int codigoRecaudoPorProceso) {
		this.codigoRecaudoPorProceso = codigoRecaudoPorProceso;
	}

	@Column(name = "codigo_importancia", nullable = false)
	public int getCodigoImportancia() {
		return this.codigoImportancia;
	}

	public void setCodigoImportancia(int codigoImportancia) {
		this.codigoImportancia = codigoImportancia;
	}

	@Column(name = "codigo_proceso", nullable = false)
	public int getCodigoProceso() {
		return this.codigoProceso;
	}

	public void setCodigoProceso(int codigoProceso) {
		this.codigoProceso = codigoProceso;
	}

	@Column(name = "codigo_documento", nullable = false)
	public int getCodigoDocumento() {
		return this.codigoDocumento;
	}

	public void setCodigoDocumento(int codigoDocumento) {
		this.codigoDocumento = codigoDocumento;
	}

	@Column(name = "cantidad")
	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "recaudoPorProceso")
	public Set<DocumentoEntregado> getDocumentoEntregados() {
		return this.documentoEntregados;
	}

	public void setDocumentoEntregados(
			Set<DocumentoEntregado> documentoEntregados) {
		this.documentoEntregados = documentoEntregados;
	}

}
