package modelo;

// Generated 10/02/2012 11:18:51 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TareaActividad generated by hbm2java
 */
@Entity
@Table(name = "tarea_actividad", schema = "public")
public class TareaActividad implements java.io.Serializable {

	private int codigoTareaActividad;
	private DatoBasico datoBasicoByCodigoTarea;
	private ComisionFamiliar comisionFamiliar;
	private DatoBasico datoBasicoByEstadoTarea;
	private Actividad actividad;
	private PersonalActividad personalActividad;
	private char estatus;

	public TareaActividad() {
	}

	public TareaActividad(int codigoTareaActividad,
			DatoBasico datoBasicoByCodigoTarea,
			DatoBasico datoBasicoByEstadoTarea, Actividad actividad,
			char estatus) {
		this.codigoTareaActividad = codigoTareaActividad;
		this.datoBasicoByCodigoTarea = datoBasicoByCodigoTarea;
		this.datoBasicoByEstadoTarea = datoBasicoByEstadoTarea;
		this.actividad = actividad;
		this.estatus = estatus;
	}

	public TareaActividad(int codigoTareaActividad,
			DatoBasico datoBasicoByCodigoTarea,
			ComisionFamiliar comisionFamiliar,
			DatoBasico datoBasicoByEstadoTarea, Actividad actividad,
			PersonalActividad personalActividad, char estatus) {
		this.codigoTareaActividad = codigoTareaActividad;
		this.datoBasicoByCodigoTarea = datoBasicoByCodigoTarea;
		this.comisionFamiliar = comisionFamiliar;
		this.datoBasicoByEstadoTarea = datoBasicoByEstadoTarea;
		this.actividad = actividad;
		this.personalActividad = personalActividad;
		this.estatus = estatus;
	}

	@Id
	@Column(name = "codigo_tarea_actividad", unique = true, nullable = false)
	public int getCodigoTareaActividad() {
		return this.codigoTareaActividad;
	}

	public void setCodigoTareaActividad(int codigoTareaActividad) {
		this.codigoTareaActividad = codigoTareaActividad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_tarea", nullable = false)
	public DatoBasico getDatoBasicoByCodigoTarea() {
		return this.datoBasicoByCodigoTarea;
	}

	public void setDatoBasicoByCodigoTarea(DatoBasico datoBasicoByCodigoTarea) {
		this.datoBasicoByCodigoTarea = datoBasicoByCodigoTarea;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_comision_familiar")
	public ComisionFamiliar getComisionFamiliar() {
		return this.comisionFamiliar;
	}

	public void setComisionFamiliar(ComisionFamiliar comisionFamiliar) {
		this.comisionFamiliar = comisionFamiliar;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "estado_tarea", nullable = false)
	public DatoBasico getDatoBasicoByEstadoTarea() {
		return this.datoBasicoByEstadoTarea;
	}

	public void setDatoBasicoByEstadoTarea(DatoBasico datoBasicoByEstadoTarea) {
		this.datoBasicoByEstadoTarea = datoBasicoByEstadoTarea;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_actividad", nullable = false)
	public Actividad getActividad() {
		return this.actividad;
	}

	public void setActividad(Actividad actividad) {
		this.actividad = actividad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_personal_actividad")
	public PersonalActividad getPersonalActividad() {
		return this.personalActividad;
	}

	public void setPersonalActividad(PersonalActividad personalActividad) {
		this.personalActividad = personalActividad;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

}
