package modelo;

// Generated 10/02/2012 11:18:51 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoIngreso generated by hbm2java
 */
@Entity
@Table(name = "tipo_ingreso", schema = "public")
public class TipoIngreso implements java.io.Serializable {

	private int codigoTipoIngreso;
	private int codigoTipo;
	private Integer codigoPeriodicidad;
	private String descripcion;
	private Double monto;
	private char estatus;
	private boolean aplicaRepresentante;
	private Set<IngresoInscripcion> ingresoInscripcions = new HashSet<IngresoInscripcion>(
			0);
	private Set<DocumentoAcreedor> documentoAcreedors = new HashSet<DocumentoAcreedor>(
			0);

	public TipoIngreso() {
	}

	public TipoIngreso(int codigoTipoIngreso, int codigoTipo,
			String descripcion, char estatus, boolean aplicaRepresentante) {
		this.codigoTipoIngreso = codigoTipoIngreso;
		this.codigoTipo = codigoTipo;
		this.descripcion = descripcion;
		this.estatus = estatus;
		this.aplicaRepresentante = aplicaRepresentante;
	}

	public TipoIngreso(int codigoTipoIngreso, int codigoTipo,
			Integer codigoPeriodicidad, String descripcion, Double monto,
			char estatus, boolean aplicaRepresentante,
			Set<IngresoInscripcion> ingresoInscripcions,
			Set<DocumentoAcreedor> documentoAcreedors) {
		this.codigoTipoIngreso = codigoTipoIngreso;
		this.codigoTipo = codigoTipo;
		this.codigoPeriodicidad = codigoPeriodicidad;
		this.descripcion = descripcion;
		this.monto = monto;
		this.estatus = estatus;
		this.aplicaRepresentante = aplicaRepresentante;
		this.ingresoInscripcions = ingresoInscripcions;
		this.documentoAcreedors = documentoAcreedors;
	}

	@Id
	@Column(name = "codigo_tipo_ingreso", unique = true, nullable = false)
	public int getCodigoTipoIngreso() {
		return this.codigoTipoIngreso;
	}

	public void setCodigoTipoIngreso(int codigoTipoIngreso) {
		this.codigoTipoIngreso = codigoTipoIngreso;
	}

	@Column(name = "codigo_tipo", nullable = false)
	public int getCodigoTipo() {
		return this.codigoTipo;
	}

	public void setCodigoTipo(int codigoTipo) {
		this.codigoTipo = codigoTipo;
	}

	@Column(name = "codigo_periodicidad")
	public Integer getCodigoPeriodicidad() {
		return this.codigoPeriodicidad;
	}

	public void setCodigoPeriodicidad(Integer codigoPeriodicidad) {
		this.codigoPeriodicidad = codigoPeriodicidad;
	}

	@Column(name = "descripcion", nullable = false)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "monto", precision = 17, scale = 17)
	public Double getMonto() {
		return this.monto;
	}

	public void setMonto(Double monto) {
		this.monto = monto;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@Column(name = "aplica_representante", nullable = false)
	public boolean isAplicaRepresentante() {
		return this.aplicaRepresentante;
	}

	public void setAplicaRepresentante(boolean aplicaRepresentante) {
		this.aplicaRepresentante = aplicaRepresentante;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoIngreso")
	public Set<IngresoInscripcion> getIngresoInscripcions() {
		return this.ingresoInscripcions;
	}

	public void setIngresoInscripcions(
			Set<IngresoInscripcion> ingresoInscripcions) {
		this.ingresoInscripcions = ingresoInscripcions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoIngreso")
	public Set<DocumentoAcreedor> getDocumentoAcreedors() {
		return this.documentoAcreedors;
	}

	public void setDocumentoAcreedors(Set<DocumentoAcreedor> documentoAcreedors) {
		this.documentoAcreedors = documentoAcreedors;
	}

}
