package modelo;

// Generated 05/12/2011 10:49:17 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EstadoVenezuela generated by hbm2java
 */
@Entity
@Table(name = "estado_venezuela")
public class EstadoVenezuela implements java.io.Serializable {

	private String codigoEstado;
	private String nombre;
	private Set<Municipio> municipios = new HashSet<Municipio>(0);

	public EstadoVenezuela() {
	}

	public EstadoVenezuela(String codigoEstado, String nombre) {
		this.codigoEstado = codigoEstado;
		this.nombre = nombre;
	}

	public EstadoVenezuela(String codigoEstado, String nombre,
			Set<Municipio> municipios) {
		this.codigoEstado = codigoEstado;
		this.nombre = nombre;
		this.municipios = municipios;
	}

	@Id
	@Column(name = "codigo_estado", unique = true, nullable = false)
	public String getCodigoEstado() {
		return this.codigoEstado;
	}

	public void setCodigoEstado(String codigoEstado) {
		this.codigoEstado = codigoEstado;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estadoVenezuela")
	public Set<Municipio> getMunicipios() {
		return this.municipios;
	}

	public void setMunicipios(Set<Municipio> municipios) {
		this.municipios = municipios;
	}

}
