package modelo;

// Generated 06/12/2011 05:27:34 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EstadoVenezuela generated by hbm2java
 */
@Entity
@Table(name = "estado_venezuela")
public class EstadoVenezuela implements java.io.Serializable {

	private String codigoEstado;
	private String nombre;
	private Set<Divisa> divisas = new HashSet<Divisa>(0);
	private Set<Divisa> divisas_1 = new HashSet<Divisa>(0);
	private Set<Municipio> municipios = new HashSet<Municipio>(0);
	private Set<Municipio> municipios_1 = new HashSet<Municipio>(0);

	public EstadoVenezuela() {
	}

	public EstadoVenezuela(String codigoEstado, String nombre) {
		this.codigoEstado = codigoEstado;
		this.nombre = nombre;
	}

	public EstadoVenezuela(String codigoEstado, String nombre,
			Set<Divisa> divisas, Set<Divisa> divisas_1,
			Set<Municipio> municipios, Set<Municipio> municipios_1) {
		this.codigoEstado = codigoEstado;
		this.nombre = nombre;
		this.divisas = divisas;
		this.divisas_1 = divisas_1;
		this.municipios = municipios;
		this.municipios_1 = municipios_1;
	}

	@Id
	@Column(name = "codigo_estado", unique = true, nullable = false)
	public String getCodigoEstado() {
		return this.codigoEstado;
	}

	public void setCodigoEstado(String codigoEstado) {
		this.codigoEstado = codigoEstado;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estadoVenezuela")
	public Set<Divisa> getDivisas() {
		return this.divisas;
	}

	public void setDivisas(Set<Divisa> divisas) {
		this.divisas = divisas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estadoVenezuela")
	public Set<Divisa> getDivisas_1() {
		return this.divisas_1;
	}

	public void setDivisas_1(Set<Divisa> divisas_1) {
		this.divisas_1 = divisas_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estadoVenezuela")
	public Set<Municipio> getMunicipios() {
		return this.municipios;
	}

	public void setMunicipios(Set<Municipio> municipios) {
		this.municipios = municipios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estadoVenezuela")
	public Set<Municipio> getMunicipios_1() {
		return this.municipios_1;
	}

	public void setMunicipios_1(Set<Municipio> municipios_1) {
		this.municipios_1 = municipios_1;
	}

}
