package modelo;

// Generated 06/12/2011 05:27:34 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estado generated by hbm2java
 */
@Entity
@Table(name = "estado")
public class Estado implements java.io.Serializable {

	private String codigoEstado;
	private String descripcion;
	private char estatus;
	private Set<EstadoMantenimiento> estadoMantenimientos = new HashSet<EstadoMantenimiento>(
			0);
	private Set<EstadoMantenimiento> estadoMantenimientos_1 = new HashSet<EstadoMantenimiento>(
			0);

	public Estado() {
	}

	public Estado(String codigoEstado, String descripcion, char estatus) {
		this.codigoEstado = codigoEstado;
		this.descripcion = descripcion;
		this.estatus = estatus;
	}

	public Estado(String codigoEstado, String descripcion, char estatus,
			Set<EstadoMantenimiento> estadoMantenimientos,
			Set<EstadoMantenimiento> estadoMantenimientos_1) {
		this.codigoEstado = codigoEstado;
		this.descripcion = descripcion;
		this.estatus = estatus;
		this.estadoMantenimientos = estadoMantenimientos;
		this.estadoMantenimientos_1 = estadoMantenimientos_1;
	}

	@Id
	@Column(name = "codigo_estado", unique = true, nullable = false)
	public String getCodigoEstado() {
		return this.codigoEstado;
	}

	public void setCodigoEstado(String codigoEstado) {
		this.codigoEstado = codigoEstado;
	}

	@Column(name = "descripcion", nullable = false)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estado")
	public Set<EstadoMantenimiento> getEstadoMantenimientos() {
		return this.estadoMantenimientos;
	}

	public void setEstadoMantenimientos(
			Set<EstadoMantenimiento> estadoMantenimientos) {
		this.estadoMantenimientos = estadoMantenimientos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estado")
	public Set<EstadoMantenimiento> getEstadoMantenimientos_1() {
		return this.estadoMantenimientos_1;
	}

	public void setEstadoMantenimientos_1(
			Set<EstadoMantenimiento> estadoMantenimientos_1) {
		this.estadoMantenimientos_1 = estadoMantenimientos_1;
	}

}
