package modelo;

// Generated 06/12/2011 05:27:34 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mantenimiento generated by hbm2java
 */
@Entity
@Table(name = "mantenimiento")
public class Mantenimiento implements java.io.Serializable {

	private String codigoMantenimiento;
	private PlanificacionMantenimiento planificacionMantenimiento;
	private char estatus;
	private Date fechaInicio;
	private Date fechaCulminacion;
	private Set<MaterialMantenimiento> materialMantenimientos = new HashSet<MaterialMantenimiento>(
			0);
	private Set<MaterialMantenimiento> materialMantenimientos_1 = new HashSet<MaterialMantenimiento>(
			0);
	private Set<TareaMantenimiento> tareaMantenimientos = new HashSet<TareaMantenimiento>(
			0);
	private Set<EmpleadoMantenimiento> empleadoMantenimientos = new HashSet<EmpleadoMantenimiento>(
			0);
	private Set<EmpleadoMantenimiento> empleadoMantenimientos_1 = new HashSet<EmpleadoMantenimiento>(
			0);
	private Set<TareaMantenimiento> tareaMantenimientos_1 = new HashSet<TareaMantenimiento>(
			0);
	private Set<EstadoMantenimiento> estadoMantenimientos = new HashSet<EstadoMantenimiento>(
			0);
	private Set<EstadoMantenimiento> estadoMantenimientos_1 = new HashSet<EstadoMantenimiento>(
			0);

	public Mantenimiento() {
	}

	public Mantenimiento(String codigoMantenimiento,
			PlanificacionMantenimiento planificacionMantenimiento,
			char estatus, Date fechaInicio, Date fechaCulminacion) {
		this.codigoMantenimiento = codigoMantenimiento;
		this.planificacionMantenimiento = planificacionMantenimiento;
		this.estatus = estatus;
		this.fechaInicio = fechaInicio;
		this.fechaCulminacion = fechaCulminacion;
	}

	public Mantenimiento(String codigoMantenimiento,
			PlanificacionMantenimiento planificacionMantenimiento,
			char estatus, Date fechaInicio, Date fechaCulminacion,
			Set<MaterialMantenimiento> materialMantenimientos,
			Set<MaterialMantenimiento> materialMantenimientos_1,
			Set<TareaMantenimiento> tareaMantenimientos,
			Set<EmpleadoMantenimiento> empleadoMantenimientos,
			Set<EmpleadoMantenimiento> empleadoMantenimientos_1,
			Set<TareaMantenimiento> tareaMantenimientos_1,
			Set<EstadoMantenimiento> estadoMantenimientos,
			Set<EstadoMantenimiento> estadoMantenimientos_1) {
		this.codigoMantenimiento = codigoMantenimiento;
		this.planificacionMantenimiento = planificacionMantenimiento;
		this.estatus = estatus;
		this.fechaInicio = fechaInicio;
		this.fechaCulminacion = fechaCulminacion;
		this.materialMantenimientos = materialMantenimientos;
		this.materialMantenimientos_1 = materialMantenimientos_1;
		this.tareaMantenimientos = tareaMantenimientos;
		this.empleadoMantenimientos = empleadoMantenimientos;
		this.empleadoMantenimientos_1 = empleadoMantenimientos_1;
		this.tareaMantenimientos_1 = tareaMantenimientos_1;
		this.estadoMantenimientos = estadoMantenimientos;
		this.estadoMantenimientos_1 = estadoMantenimientos_1;
	}

	@Id
	@Column(name = "codigo_mantenimiento", unique = true, nullable = false)
	public String getCodigoMantenimiento() {
		return this.codigoMantenimiento;
	}

	public void setCodigoMantenimiento(String codigoMantenimiento) {
		this.codigoMantenimiento = codigoMantenimiento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_planificacion_mantenimiento", nullable = false)
	public PlanificacionMantenimiento getPlanificacionMantenimiento() {
		return this.planificacionMantenimiento;
	}

	public void setPlanificacionMantenimiento(
			PlanificacionMantenimiento planificacionMantenimiento) {
		this.planificacionMantenimiento = planificacionMantenimiento;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_inicio", nullable = false, length = 13)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_culminacion", nullable = false, length = 13)
	public Date getFechaCulminacion() {
		return this.fechaCulminacion;
	}

	public void setFechaCulminacion(Date fechaCulminacion) {
		this.fechaCulminacion = fechaCulminacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mantenimiento")
	public Set<MaterialMantenimiento> getMaterialMantenimientos() {
		return this.materialMantenimientos;
	}

	public void setMaterialMantenimientos(
			Set<MaterialMantenimiento> materialMantenimientos) {
		this.materialMantenimientos = materialMantenimientos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mantenimiento")
	public Set<MaterialMantenimiento> getMaterialMantenimientos_1() {
		return this.materialMantenimientos_1;
	}

	public void setMaterialMantenimientos_1(
			Set<MaterialMantenimiento> materialMantenimientos_1) {
		this.materialMantenimientos_1 = materialMantenimientos_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mantenimiento")
	public Set<TareaMantenimiento> getTareaMantenimientos() {
		return this.tareaMantenimientos;
	}

	public void setTareaMantenimientos(
			Set<TareaMantenimiento> tareaMantenimientos) {
		this.tareaMantenimientos = tareaMantenimientos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mantenimiento")
	public Set<EmpleadoMantenimiento> getEmpleadoMantenimientos() {
		return this.empleadoMantenimientos;
	}

	public void setEmpleadoMantenimientos(
			Set<EmpleadoMantenimiento> empleadoMantenimientos) {
		this.empleadoMantenimientos = empleadoMantenimientos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mantenimiento")
	public Set<EmpleadoMantenimiento> getEmpleadoMantenimientos_1() {
		return this.empleadoMantenimientos_1;
	}

	public void setEmpleadoMantenimientos_1(
			Set<EmpleadoMantenimiento> empleadoMantenimientos_1) {
		this.empleadoMantenimientos_1 = empleadoMantenimientos_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mantenimiento")
	public Set<TareaMantenimiento> getTareaMantenimientos_1() {
		return this.tareaMantenimientos_1;
	}

	public void setTareaMantenimientos_1(
			Set<TareaMantenimiento> tareaMantenimientos_1) {
		this.tareaMantenimientos_1 = tareaMantenimientos_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mantenimiento")
	public Set<EstadoMantenimiento> getEstadoMantenimientos() {
		return this.estadoMantenimientos;
	}

	public void setEstadoMantenimientos(
			Set<EstadoMantenimiento> estadoMantenimientos) {
		this.estadoMantenimientos = estadoMantenimientos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mantenimiento")
	public Set<EstadoMantenimiento> getEstadoMantenimientos_1() {
		return this.estadoMantenimientos_1;
	}

	public void setEstadoMantenimientos_1(
			Set<EstadoMantenimiento> estadoMantenimientos_1) {
		this.estadoMantenimientos_1 = estadoMantenimientos_1;
	}

}
