package modelo;

// Generated 06-dic-2011 15:00:16 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Medico generated by hbm2java
 */
@Entity
@Table(name = "medico")
public class Medico implements java.io.Serializable {

	private String matricula;
	private String numeroColegio;
	private String cedulaMedico;
	private String nombre;
	private String apellido;
	private Date fechaIngreso;
	private char estatus;
	private Set<DatoMedico> datoMedicos = new HashSet<DatoMedico>(0);
	private Set<DatoMedico> datoMedicos_1 = new HashSet<DatoMedico>(0);

	public Medico() {
	}

	public Medico(String matricula, String numeroColegio, String cedulaMedico,
			String nombre, String apellido, Date fechaIngreso, char estatus) {
		this.matricula = matricula;
		this.numeroColegio = numeroColegio;
		this.cedulaMedico = cedulaMedico;
		this.nombre = nombre;
		this.apellido = apellido;
		this.fechaIngreso = fechaIngreso;
		this.estatus = estatus;
	}

	public Medico(String matricula, String numeroColegio, String cedulaMedico,
			String nombre, String apellido, Date fechaIngreso, char estatus,
			Set<DatoMedico> datoMedicos, Set<DatoMedico> datoMedicos_1) {
		this.matricula = matricula;
		this.numeroColegio = numeroColegio;
		this.cedulaMedico = cedulaMedico;
		this.nombre = nombre;
		this.apellido = apellido;
		this.fechaIngreso = fechaIngreso;
		this.estatus = estatus;
		this.datoMedicos = datoMedicos;
		this.datoMedicos_1 = datoMedicos_1;
	}

	@Id
	@Column(name = "matricula", unique = true, nullable = false)
	public String getMatricula() {
		return this.matricula;
	}

	public void setMatricula(String matricula) {
		this.matricula = matricula;
	}

	@Column(name = "numero_colegio", nullable = false)
	public String getNumeroColegio() {
		return this.numeroColegio;
	}

	public void setNumeroColegio(String numeroColegio) {
		this.numeroColegio = numeroColegio;
	}

	@Column(name = "cedula_medico", nullable = false)
	public String getCedulaMedico() {
		return this.cedulaMedico;
	}

	public void setCedulaMedico(String cedulaMedico) {
		this.cedulaMedico = cedulaMedico;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apellido", nullable = false)
	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_ingreso", nullable = false, length = 13)
	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "medico")
	public Set<DatoMedico> getDatoMedicos() {
		return this.datoMedicos;
	}

	public void setDatoMedicos(Set<DatoMedico> datoMedicos) {
		this.datoMedicos = datoMedicos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "medico")
	public Set<DatoMedico> getDatoMedicos_1() {
		return this.datoMedicos_1;
	}

	public void setDatoMedicos_1(Set<DatoMedico> datoMedicos_1) {
		this.datoMedicos_1 = datoMedicos_1;
	}

}
