package modelo;

// Generated 06/12/2011 05:27:34 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PeriodicidadPago generated by hbm2java
 */
@Entity
@Table(name = "periodicidad_pago")
public class PeriodicidadPago implements java.io.Serializable {

	private String codigoPeriodicidadPago;
	private String descripcion;
	private char estatus;
	private Set<TipoNomina> tipoNominas = new HashSet<TipoNomina>(0);
	private Set<TipoNomina> tipoNominas_1 = new HashSet<TipoNomina>(0);

	public PeriodicidadPago() {
	}

	public PeriodicidadPago(String codigoPeriodicidadPago, String descripcion,
			char estatus) {
		this.codigoPeriodicidadPago = codigoPeriodicidadPago;
		this.descripcion = descripcion;
		this.estatus = estatus;
	}

	public PeriodicidadPago(String codigoPeriodicidadPago, String descripcion,
			char estatus, Set<TipoNomina> tipoNominas,
			Set<TipoNomina> tipoNominas_1) {
		this.codigoPeriodicidadPago = codigoPeriodicidadPago;
		this.descripcion = descripcion;
		this.estatus = estatus;
		this.tipoNominas = tipoNominas;
		this.tipoNominas_1 = tipoNominas_1;
	}

	@Id
	@Column(name = "codigo_periodicidad_pago", unique = true, nullable = false)
	public String getCodigoPeriodicidadPago() {
		return this.codigoPeriodicidadPago;
	}

	public void setCodigoPeriodicidadPago(String codigoPeriodicidadPago) {
		this.codigoPeriodicidadPago = codigoPeriodicidadPago;
	}

	@Column(name = "descripcion", nullable = false)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "periodicidadPago")
	public Set<TipoNomina> getTipoNominas() {
		return this.tipoNominas;
	}

	public void setTipoNominas(Set<TipoNomina> tipoNominas) {
		this.tipoNominas = tipoNominas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "periodicidadPago")
	public Set<TipoNomina> getTipoNominas_1() {
		return this.tipoNominas_1;
	}

	public void setTipoNominas_1(Set<TipoNomina> tipoNominas_1) {
		this.tipoNominas_1 = tipoNominas_1;
	}

}
