package modelo;

// Generated 05/12/2011 10:49:17 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Profesion generated by hbm2java
 */
@Entity
@Table(name = "profesion")
public class Profesion implements java.io.Serializable {

	private String codigoProfesion;
	private String nombre;
	private char estatus;
	private Set<Familiar> familiars = new HashSet<Familiar>(0);

	public Profesion() {
	}

	public Profesion(String codigoProfesion, String nombre, char estatus) {
		this.codigoProfesion = codigoProfesion;
		this.nombre = nombre;
		this.estatus = estatus;
	}

	public Profesion(String codigoProfesion, String nombre, char estatus,
			Set<Familiar> familiars) {
		this.codigoProfesion = codigoProfesion;
		this.nombre = nombre;
		this.estatus = estatus;
		this.familiars = familiars;
	}

	@Id
	@Column(name = "codigo_profesion", unique = true, nullable = false)
	public String getCodigoProfesion() {
		return this.codigoProfesion;
	}

	public void setCodigoProfesion(String codigoProfesion) {
		this.codigoProfesion = codigoProfesion;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "profesion")
	public Set<Familiar> getFamiliars() {
		return this.familiars;
	}

	public void setFamiliars(Set<Familiar> familiars) {
		this.familiars = familiars;
	}

}
