package modelo;

// Generated 06-dic-2011 15:00:16 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TareaMantenimiento generated by hbm2java
 */
@Entity
@Table(name = "tarea_mantenimiento")
public class TareaMantenimiento implements java.io.Serializable {

	private TareaMantenimientoId id;
	private Tarea tarea;
	private Mantenimiento mantenimiento;
	private EmpleadoMantenimiento empleadoMantenimientoByFk2be9c788a2d2a5db;
	private EmpleadoMantenimiento empleadoMantenimientoByEmpleadoMantenimientoTareaMantenimientoFk;
	private String codigoTareaMantenimiento;
	private char estatus;

	public TareaMantenimiento() {
	}

	public TareaMantenimiento(
			TareaMantenimientoId id,
			Tarea tarea,
			Mantenimiento mantenimiento,
			EmpleadoMantenimiento empleadoMantenimientoByFk2be9c788a2d2a5db,
			EmpleadoMantenimiento empleadoMantenimientoByEmpleadoMantenimientoTareaMantenimientoFk,
			String codigoTareaMantenimiento, char estatus) {
		this.id = id;
		this.tarea = tarea;
		this.mantenimiento = mantenimiento;
		this.empleadoMantenimientoByFk2be9c788a2d2a5db = empleadoMantenimientoByFk2be9c788a2d2a5db;
		this.empleadoMantenimientoByEmpleadoMantenimientoTareaMantenimientoFk = empleadoMantenimientoByEmpleadoMantenimientoTareaMantenimientoFk;
		this.codigoTareaMantenimiento = codigoTareaMantenimiento;
		this.estatus = estatus;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codigoTarea", column = @Column(name = "codigo_tarea", nullable = false)),
			@AttributeOverride(name = "codigoMantenimiento", column = @Column(name = "codigo_mantenimiento", nullable = false)) })
	public TareaMantenimientoId getId() {
		return this.id;
	}

	public void setId(TareaMantenimientoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_tarea", nullable = false, insertable = false, updatable = false)
	public Tarea getTarea() {
		return this.tarea;
	}

	public void setTarea(Tarea tarea) {
		this.tarea = tarea;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_mantenimiento", nullable = false, insertable = false, updatable = false)
	public Mantenimiento getMantenimiento() {
		return this.mantenimiento;
	}

	public void setMantenimiento(Mantenimiento mantenimiento) {
		this.mantenimiento = mantenimiento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "cedula", referencedColumnName = "codigo_mantenimiento", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "codigo_mantenimiento", referencedColumnName = "cedula", nullable = false, insertable = false, updatable = false) })
	public EmpleadoMantenimiento getEmpleadoMantenimientoByFk2be9c788a2d2a5db() {
		return this.empleadoMantenimientoByFk2be9c788a2d2a5db;
	}

	public void setEmpleadoMantenimientoByFk2be9c788a2d2a5db(
			EmpleadoMantenimiento empleadoMantenimientoByFk2be9c788a2d2a5db) {
		this.empleadoMantenimientoByFk2be9c788a2d2a5db = empleadoMantenimientoByFk2be9c788a2d2a5db;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "codigo_mantenimiento", referencedColumnName = "codigo_mantenimiento", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "cedula", referencedColumnName = "cedula", nullable = false, insertable = false, updatable = false) })
	public EmpleadoMantenimiento getEmpleadoMantenimientoByEmpleadoMantenimientoTareaMantenimientoFk() {
		return this.empleadoMantenimientoByEmpleadoMantenimientoTareaMantenimientoFk;
	}

	public void setEmpleadoMantenimientoByEmpleadoMantenimientoTareaMantenimientoFk(
			EmpleadoMantenimiento empleadoMantenimientoByEmpleadoMantenimientoTareaMantenimientoFk) {
		this.empleadoMantenimientoByEmpleadoMantenimientoTareaMantenimientoFk = empleadoMantenimientoByEmpleadoMantenimientoTareaMantenimientoFk;
	}

	@Column(name = "codigo_tarea_mantenimiento", nullable = false)
	public String getCodigoTareaMantenimiento() {
		return this.codigoTareaMantenimiento;
	}

	public void setCodigoTareaMantenimiento(String codigoTareaMantenimiento) {
		this.codigoTareaMantenimiento = codigoTareaMantenimiento;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

}
