package modelo;

// Generated 06/12/2011 05:27:34 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoAfeccion generated by hbm2java
 */
@Entity
@Table(name = "tipo_afeccion")
public class TipoAfeccion implements java.io.Serializable {

	private String codigoAfeccion;
	private String nombre;
	private String descripcion;
	private char estatus;
	private Set<AfeccionJugador> afeccionJugadors = new HashSet<AfeccionJugador>(
			0);
	private Set<AfeccionJugador> afeccionJugadors_1 = new HashSet<AfeccionJugador>(
			0);

	public TipoAfeccion() {
	}

	public TipoAfeccion(String codigoAfeccion, String nombre,
			String descripcion, char estatus) {
		this.codigoAfeccion = codigoAfeccion;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.estatus = estatus;
	}

	public TipoAfeccion(String codigoAfeccion, String nombre,
			String descripcion, char estatus,
			Set<AfeccionJugador> afeccionJugadors,
			Set<AfeccionJugador> afeccionJugadors_1) {
		this.codigoAfeccion = codigoAfeccion;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.estatus = estatus;
		this.afeccionJugadors = afeccionJugadors;
		this.afeccionJugadors_1 = afeccionJugadors_1;
	}

	@Id
	@Column(name = "codigo_afeccion", unique = true, nullable = false)
	public String getCodigoAfeccion() {
		return this.codigoAfeccion;
	}

	public void setCodigoAfeccion(String codigoAfeccion) {
		this.codigoAfeccion = codigoAfeccion;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", nullable = false)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoAfeccion")
	public Set<AfeccionJugador> getAfeccionJugadors() {
		return this.afeccionJugadors;
	}

	public void setAfeccionJugadors(Set<AfeccionJugador> afeccionJugadors) {
		this.afeccionJugadors = afeccionJugadors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoAfeccion")
	public Set<AfeccionJugador> getAfeccionJugadors_1() {
		return this.afeccionJugadors_1;
	}

	public void setAfeccionJugadors_1(Set<AfeccionJugador> afeccionJugadors_1) {
		this.afeccionJugadors_1 = afeccionJugadors_1;
	}

}
