package modelo;

// Generated 06-dic-2011 15:00:16 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoConceptoNomina generated by hbm2java
 */
@Entity
@Table(name = "tipo_concepto_nomina")
public class TipoConceptoNomina implements java.io.Serializable {

	private String codigoTipoConceptoNomina;
	private String descripcion;
	private char estatus;
	private Set<ConceptoNomina> conceptoNominas = new HashSet<ConceptoNomina>(0);
	private Set<ConceptoNomina> conceptoNominas_1 = new HashSet<ConceptoNomina>(
			0);

	public TipoConceptoNomina() {
	}

	public TipoConceptoNomina(String codigoTipoConceptoNomina,
			String descripcion, char estatus) {
		this.codigoTipoConceptoNomina = codigoTipoConceptoNomina;
		this.descripcion = descripcion;
		this.estatus = estatus;
	}

	public TipoConceptoNomina(String codigoTipoConceptoNomina,
			String descripcion, char estatus,
			Set<ConceptoNomina> conceptoNominas,
			Set<ConceptoNomina> conceptoNominas_1) {
		this.codigoTipoConceptoNomina = codigoTipoConceptoNomina;
		this.descripcion = descripcion;
		this.estatus = estatus;
		this.conceptoNominas = conceptoNominas;
		this.conceptoNominas_1 = conceptoNominas_1;
	}

	@Id
	@Column(name = "codigo_tipo_concepto_nomina", unique = true, nullable = false)
	public String getCodigoTipoConceptoNomina() {
		return this.codigoTipoConceptoNomina;
	}

	public void setCodigoTipoConceptoNomina(String codigoTipoConceptoNomina) {
		this.codigoTipoConceptoNomina = codigoTipoConceptoNomina;
	}

	@Column(name = "descripcion", nullable = false)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoConceptoNomina")
	public Set<ConceptoNomina> getConceptoNominas() {
		return this.conceptoNominas;
	}

	public void setConceptoNominas(Set<ConceptoNomina> conceptoNominas) {
		this.conceptoNominas = conceptoNominas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoConceptoNomina")
	public Set<ConceptoNomina> getConceptoNominas_1() {
		return this.conceptoNominas_1;
	}

	public void setConceptoNominas_1(Set<ConceptoNomina> conceptoNominas_1) {
		this.conceptoNominas_1 = conceptoNominas_1;
	}

}
