package modelo;

// Generated 06-dic-2011 15:00:16 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoEscalaMedicion generated by hbm2java
 */
@Entity
@Table(name = "tipo_escala_medicion")
public class TipoEscalaMedicion implements java.io.Serializable {

	private String idTipoEscalaMedicion;
	private char estatus;
	private String nombre;
	private Set<EscalaMedicion> escalaMedicions = new HashSet<EscalaMedicion>(0);
	private Set<EscalaMedicion> escalaMedicions_1 = new HashSet<EscalaMedicion>(
			0);

	public TipoEscalaMedicion() {
	}

	public TipoEscalaMedicion(String idTipoEscalaMedicion, char estatus,
			String nombre) {
		this.idTipoEscalaMedicion = idTipoEscalaMedicion;
		this.estatus = estatus;
		this.nombre = nombre;
	}

	public TipoEscalaMedicion(String idTipoEscalaMedicion, char estatus,
			String nombre, Set<EscalaMedicion> escalaMedicions,
			Set<EscalaMedicion> escalaMedicions_1) {
		this.idTipoEscalaMedicion = idTipoEscalaMedicion;
		this.estatus = estatus;
		this.nombre = nombre;
		this.escalaMedicions = escalaMedicions;
		this.escalaMedicions_1 = escalaMedicions_1;
	}

	@Id
	@Column(name = "id_tipo_escala_medicion", unique = true, nullable = false)
	public String getIdTipoEscalaMedicion() {
		return this.idTipoEscalaMedicion;
	}

	public void setIdTipoEscalaMedicion(String idTipoEscalaMedicion) {
		this.idTipoEscalaMedicion = idTipoEscalaMedicion;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoEscalaMedicion")
	public Set<EscalaMedicion> getEscalaMedicions() {
		return this.escalaMedicions;
	}

	public void setEscalaMedicions(Set<EscalaMedicion> escalaMedicions) {
		this.escalaMedicions = escalaMedicions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoEscalaMedicion")
	public Set<EscalaMedicion> getEscalaMedicions_1() {
		return this.escalaMedicions_1;
	}

	public void setEscalaMedicions_1(Set<EscalaMedicion> escalaMedicions_1) {
		this.escalaMedicions_1 = escalaMedicions_1;
	}

}
