package modelo;

<<<<<<< HEAD
// Generated 25/01/2012 12:32:42 AM by Hibernate Tools 3.4.0.CR1
=======
<<<<<<< HEAD
// Generated 25/01/2012 12:32:42 AM by Hibernate Tools 3.4.0.CR1
=======
// Generated 24/01/2012 04:28:30 AM by Hibernate Tools 3.4.0.CR1
>>>>>>> 7d4823278d0a354855f5032a99e2b48c65b33e7f
>>>>>>> 9d67536bdd2e3b33aa6400eb3bb09741a4535bb0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ActividadPlanificadaId generated by hbm2java
 */
@Embeddable
public class ActividadPlanificadaId implements java.io.Serializable {

	private int codigoSesion;
<<<<<<< HEAD
	private int codigoActividadEntrenamiento;
=======
<<<<<<< HEAD
	private int codigoActividadEntrenamiento;
=======
	private int codActividadEntrenamiento;
>>>>>>> 7d4823278d0a354855f5032a99e2b48c65b33e7f
>>>>>>> 9d67536bdd2e3b33aa6400eb3bb09741a4535bb0

	public ActividadPlanificadaId() {
	}

	public ActividadPlanificadaId(int codigoSesion,
<<<<<<< HEAD
			int codigoActividadEntrenamiento) {
		this.codigoSesion = codigoSesion;
		this.codigoActividadEntrenamiento = codigoActividadEntrenamiento;
=======
<<<<<<< HEAD
			int codigoActividadEntrenamiento) {
		this.codigoSesion = codigoSesion;
		this.codigoActividadEntrenamiento = codigoActividadEntrenamiento;
=======
			int codActividadEntrenamiento) {
		this.codigoSesion = codigoSesion;
		this.codActividadEntrenamiento = codActividadEntrenamiento;
>>>>>>> 7d4823278d0a354855f5032a99e2b48c65b33e7f
>>>>>>> 9d67536bdd2e3b33aa6400eb3bb09741a4535bb0
	}

	@Column(name = "codigo_sesion", nullable = false)
	public int getCodigoSesion() {
		return this.codigoSesion;
	}

	public void setCodigoSesion(int codigoSesion) {
		this.codigoSesion = codigoSesion;
	}

<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> 9d67536bdd2e3b33aa6400eb3bb09741a4535bb0
	@Column(name = "codigo_actividad_entrenamiento", nullable = false)
	public int getCodigoActividadEntrenamiento() {
		return this.codigoActividadEntrenamiento;
	}

	public void setCodigoActividadEntrenamiento(int codigoActividadEntrenamiento) {
		this.codigoActividadEntrenamiento = codigoActividadEntrenamiento;
<<<<<<< HEAD
=======
=======
	@Column(name = "cod_actividad_entrenamiento", nullable = false)
	public int getCodActividadEntrenamiento() {
		return this.codActividadEntrenamiento;
	}

	public void setCodActividadEntrenamiento(int codActividadEntrenamiento) {
		this.codActividadEntrenamiento = codActividadEntrenamiento;
>>>>>>> 7d4823278d0a354855f5032a99e2b48c65b33e7f
>>>>>>> 9d67536bdd2e3b33aa6400eb3bb09741a4535bb0
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ActividadPlanificadaId))
			return false;
		ActividadPlanificadaId castOther = (ActividadPlanificadaId) other;

		return (this.getCodigoSesion() == castOther.getCodigoSesion())
<<<<<<< HEAD
				&& (this.getCodigoActividadEntrenamiento() == castOther
						.getCodigoActividadEntrenamiento());
=======
<<<<<<< HEAD
				&& (this.getCodigoActividadEntrenamiento() == castOther
						.getCodigoActividadEntrenamiento());
=======
				&& (this.getCodActividadEntrenamiento() == castOther
						.getCodActividadEntrenamiento());
>>>>>>> 7d4823278d0a354855f5032a99e2b48c65b33e7f
>>>>>>> 9d67536bdd2e3b33aa6400eb3bb09741a4535bb0
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoSesion();
<<<<<<< HEAD
		result = 37 * result + this.getCodigoActividadEntrenamiento();
=======
<<<<<<< HEAD
		result = 37 * result + this.getCodigoActividadEntrenamiento();
=======
		result = 37 * result + this.getCodActividadEntrenamiento();
>>>>>>> 7d4823278d0a354855f5032a99e2b48c65b33e7f
>>>>>>> 9d67536bdd2e3b33aa6400eb3bb09741a4535bb0
		return result;
	}

}
