package modelo;

// Generated 28/12/2011 03:24:38 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ActividadPlanificada generated by hbm2java
 */
@Entity
@Table(name = "actividad_planificada", schema = "public")
public class ActividadPlanificada implements java.io.Serializable {

	private ActividadPlanificadaId id;
	private Usuario usuario;
	private Sesion sesion;
	private IndicadorActividadEscala indicadorActividadEscala;
	private Date tiempo;
	private char estatus;
	private Date fechaCreacion;
	private Date horaCreacion;
	private Date fechaModificacion;
	private Date horaModificacion;

	public ActividadPlanificada() {
	}

	public ActividadPlanificada(ActividadPlanificadaId id, Usuario usuario,
			Sesion sesion, IndicadorActividadEscala indicadorActividadEscala,
			Date tiempo, char estatus, Date fechaCreacion, Date horaCreacion,
			Date fechaModificacion, Date horaModificacion) {
		this.id = id;
		this.usuario = usuario;
		this.sesion = sesion;
		this.indicadorActividadEscala = indicadorActividadEscala;
		this.tiempo = tiempo;
		this.estatus = estatus;
		this.fechaCreacion = fechaCreacion;
		this.horaCreacion = horaCreacion;
		this.fechaModificacion = fechaModificacion;
		this.horaModificacion = horaModificacion;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codigoIndicadorActividadEscala", column = @Column(name = "codigo_indicador_actividad_escala", nullable = false)),
			@AttributeOverride(name = "codigoSesion", column = @Column(name = "codigo_sesion", nullable = false)) })
	public ActividadPlanificadaId getId() {
		return this.id;
	}

	public void setId(ActividadPlanificadaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cedula_rif", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_sesion", nullable = false, insertable = false, updatable = false)
	public Sesion getSesion() {
		return this.sesion;
	}

	public void setSesion(Sesion sesion) {
		this.sesion = sesion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_indicador_actividad_escala", nullable = false, insertable = false, updatable = false)
	public IndicadorActividadEscala getIndicadorActividadEscala() {
		return this.indicadorActividadEscala;
	}

	public void setIndicadorActividadEscala(
			IndicadorActividadEscala indicadorActividadEscala) {
		this.indicadorActividadEscala = indicadorActividadEscala;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "tiempo", nullable = false, length = 15)
	public Date getTiempo() {
		return this.tiempo;
	}

	public void setTiempo(Date tiempo) {
		this.tiempo = tiempo;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_creacion", nullable = false, length = 13)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_creacion", nullable = false, length = 15)
	public Date getHoraCreacion() {
		return this.horaCreacion;
	}

	public void setHoraCreacion(Date horaCreacion) {
		this.horaCreacion = horaCreacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_modificacion", nullable = false, length = 13)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_modificacion", nullable = false, length = 15)
	public Date getHoraModificacion() {
		return this.horaModificacion;
	}

	public void setHoraModificacion(Date horaModificacion) {
		this.horaModificacion = horaModificacion;
	}

}
