package modelo;

// Generated 14/02/2012 08:24:27 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AfeccionPersonal generated by hbm2java
 */
@Entity
@Table(name = "afeccion_personal", schema = "public")
public class AfeccionPersonal implements java.io.Serializable {

	private int codigoAfeccionPersonal;
	private DatoBasico datoBasico;
	private Personal personal;
	private char estatus;
	private String observacion;

	public AfeccionPersonal() {
	}

	public AfeccionPersonal(int codigoAfeccionPersonal, DatoBasico datoBasico,
			Personal personal, char estatus) {
		this.codigoAfeccionPersonal = codigoAfeccionPersonal;
		this.datoBasico = datoBasico;
		this.personal = personal;
		this.estatus = estatus;
	}

	public AfeccionPersonal(int codigoAfeccionPersonal, DatoBasico datoBasico,
			Personal personal, char estatus, String observacion) {
		this.codigoAfeccionPersonal = codigoAfeccionPersonal;
		this.datoBasico = datoBasico;
		this.personal = personal;
		this.estatus = estatus;
		this.observacion = observacion;
	}

	@Id
	@Column(name = "codigo_afeccion_personal", unique = true, nullable = false)
	public int getCodigoAfeccionPersonal() {
		return this.codigoAfeccionPersonal;
	}

	public void setCodigoAfeccionPersonal(int codigoAfeccionPersonal) {
		this.codigoAfeccionPersonal = codigoAfeccionPersonal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_tipo_afeccion", nullable = false)
	public DatoBasico getDatoBasico() {
		return this.datoBasico;
	}

	public void setDatoBasico(DatoBasico datoBasico) {
		this.datoBasico = datoBasico;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cedula_rif", nullable = false)
	public Personal getPersonal() {
		return this.personal;
	}

	public void setPersonal(Personal personal) {
		this.personal = personal;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@Column(name = "observacion")
	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

}
