package modelo;

// Generated 12/12/2011 04:39:20 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Almacen generated by hbm2java
 */
@Entity
@Table(name = "almacen")
public class Almacen implements java.io.Serializable {

	private String codigoAlmacen;
	private Instalacion instalacion;
	private String nombreAlmacen;
	private String descripcion;
	private char estatus;
	private double capacidadAlmacen;

	public Almacen() {
	}

	public Almacen(String codigoAlmacen, Instalacion instalacion,
			String nombreAlmacen, char estatus, double capacidadAlmacen) {
		this.codigoAlmacen = codigoAlmacen;
		this.instalacion = instalacion;
		this.nombreAlmacen = nombreAlmacen;
		this.estatus = estatus;
		this.capacidadAlmacen = capacidadAlmacen;
	}

	public Almacen(String codigoAlmacen, Instalacion instalacion,
			String nombreAlmacen, String descripcion, char estatus,
			double capacidadAlmacen) {
		this.codigoAlmacen = codigoAlmacen;
		this.instalacion = instalacion;
		this.nombreAlmacen = nombreAlmacen;
		this.descripcion = descripcion;
		this.estatus = estatus;
		this.capacidadAlmacen = capacidadAlmacen;
	}

	@Id
	@Column(name = "codigo_almacen", unique = true, nullable = false)
	public String getCodigoAlmacen() {
		return this.codigoAlmacen;
	}

	public void setCodigoAlmacen(String codigoAlmacen) {
		this.codigoAlmacen = codigoAlmacen;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_instalacion", nullable = false)
	public Instalacion getInstalacion() {
		return this.instalacion;
	}

	public void setInstalacion(Instalacion instalacion) {
		this.instalacion = instalacion;
	}

	@Column(name = "nombre_almacen", nullable = false, length = 30)
	public String getNombreAlmacen() {
		return this.nombreAlmacen;
	}

	public void setNombreAlmacen(String nombreAlmacen) {
		this.nombreAlmacen = nombreAlmacen;
	}

	@Column(name = "descripcion", length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@Column(name = "capacidad_almacen", nullable = false, precision = 17, scale = 17)
	public double getCapacidadAlmacen() {
		return this.capacidadAlmacen;
	}

	public void setCapacidadAlmacen(double capacidadAlmacen) {
		this.capacidadAlmacen = capacidadAlmacen;
	}

}
