package modelo;

// Generated 12/12/2011 09:17:13 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AnnoEscolar generated by hbm2java
 */
@Entity
@Table(name = "anno_escolar")
public class AnnoEscolar implements java.io.Serializable {

	private String codigoAnnoEscolar;
	private char estatus;
	private String nombre;
	private Set<DatoAcademico> datoAcademicos = new HashSet<DatoAcademico>(0);

	public AnnoEscolar() {
	}

	public AnnoEscolar(String codigoAnnoEscolar, char estatus, String nombre) {
		this.codigoAnnoEscolar = codigoAnnoEscolar;
		this.estatus = estatus;
		this.nombre = nombre;
	}

	public AnnoEscolar(String codigoAnnoEscolar, char estatus, String nombre,
			Set<DatoAcademico> datoAcademicos) {
		this.codigoAnnoEscolar = codigoAnnoEscolar;
		this.estatus = estatus;
		this.nombre = nombre;
		this.datoAcademicos = datoAcademicos;
	}

	@Id
	@Column(name = "codigo_anno_escolar", unique = true, nullable = false)
	public String getCodigoAnnoEscolar() {
		return this.codigoAnnoEscolar;
	}

	public void setCodigoAnnoEscolar(String codigoAnnoEscolar) {
		this.codigoAnnoEscolar = codigoAnnoEscolar;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "annoEscolar")
	public Set<DatoAcademico> getDatoAcademicos() {
		return this.datoAcademicos;
	}

	public void setDatoAcademicos(Set<DatoAcademico> datoAcademicos) {
		this.datoAcademicos = datoAcademicos;
	}

}
