package modelo;

// Generated 11/12/2011 04:17:03 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categoria generated by hbm2java
 */
@Entity
@Table(name = "categoria")
public class Categoria implements java.io.Serializable {

	private String codigoCategoria;
	private int cantidadEquipo;
	private int edadInferior;
	private int edadSuperior;
	private char estatus;
	private int maximoJugador;
	private int minimoJugador;
	private String nombre;
	private Set<CategoriaCompetencia> categoriaCompetencias = new HashSet<CategoriaCompetencia>(
			0);
	private Set<Liga> ligas = new HashSet<Liga>(0);
	private Set<Equipo> equipos = new HashSet<Equipo>(0);
	private Set<ActividadEntrenamiento> actividadEntrenamientos = new HashSet<ActividadEntrenamiento>(
			0);

	public Categoria() {
	}

	public Categoria(String codigoCategoria, int cantidadEquipo,
			int edadInferior, int edadSuperior, char estatus,
			int maximoJugador, int minimoJugador, String nombre) {
		this.codigoCategoria = codigoCategoria;
		this.cantidadEquipo = cantidadEquipo;
		this.edadInferior = edadInferior;
		this.edadSuperior = edadSuperior;
		this.estatus = estatus;
		this.maximoJugador = maximoJugador;
		this.minimoJugador = minimoJugador;
		this.nombre = nombre;
	}

	public Categoria(String codigoCategoria, int cantidadEquipo,
			int edadInferior, int edadSuperior, char estatus,
			int maximoJugador, int minimoJugador, String nombre,
			Set<CategoriaCompetencia> categoriaCompetencias, Set<Liga> ligas,
			Set<Equipo> equipos,
			Set<ActividadEntrenamiento> actividadEntrenamientos) {
		this.codigoCategoria = codigoCategoria;
		this.cantidadEquipo = cantidadEquipo;
		this.edadInferior = edadInferior;
		this.edadSuperior = edadSuperior;
		this.estatus = estatus;
		this.maximoJugador = maximoJugador;
		this.minimoJugador = minimoJugador;
		this.nombre = nombre;
		this.categoriaCompetencias = categoriaCompetencias;
		this.ligas = ligas;
		this.equipos = equipos;
		this.actividadEntrenamientos = actividadEntrenamientos;
	}

	@Id
	@Column(name = "codigo_categoria", unique = true, nullable = false)
	public String getCodigoCategoria() {
		return this.codigoCategoria;
	}

	public void setCodigoCategoria(String codigoCategoria) {
		this.codigoCategoria = codigoCategoria;
	}

	@Column(name = "cantidad_equipo", nullable = false)
	public int getCantidadEquipo() {
		return this.cantidadEquipo;
	}

	public void setCantidadEquipo(int cantidadEquipo) {
		this.cantidadEquipo = cantidadEquipo;
	}

	@Column(name = "edad_inferior", nullable = false)
	public int getEdadInferior() {
		return this.edadInferior;
	}

	public void setEdadInferior(int edadInferior) {
		this.edadInferior = edadInferior;
	}

	@Column(name = "edad_superior", nullable = false)
	public int getEdadSuperior() {
		return this.edadSuperior;
	}

	public void setEdadSuperior(int edadSuperior) {
		this.edadSuperior = edadSuperior;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@Column(name = "maximo_jugador", nullable = false)
	public int getMaximoJugador() {
		return this.maximoJugador;
	}

	public void setMaximoJugador(int maximoJugador) {
		this.maximoJugador = maximoJugador;
	}

	@Column(name = "minimo_jugador", nullable = false)
	public int getMinimoJugador() {
		return this.minimoJugador;
	}

	public void setMinimoJugador(int minimoJugador) {
		this.minimoJugador = minimoJugador;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoria")
	public Set<CategoriaCompetencia> getCategoriaCompetencias() {
		return this.categoriaCompetencias;
	}

	public void setCategoriaCompetencias(
			Set<CategoriaCompetencia> categoriaCompetencias) {
		this.categoriaCompetencias = categoriaCompetencias;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "categorias")
	public Set<Liga> getLigas() {
		return this.ligas;
	}

	public void setLigas(Set<Liga> ligas) {
		this.ligas = ligas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoria")
	public Set<Equipo> getEquipos() {
		return this.equipos;
	}

	public void setEquipos(Set<Equipo> equipos) {
		this.equipos = equipos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoria")
	public Set<ActividadEntrenamiento> getActividadEntrenamientos() {
		return this.actividadEntrenamientos;
	}

	public void setActividadEntrenamientos(
			Set<ActividadEntrenamiento> actividadEntrenamientos) {
		this.actividadEntrenamientos = actividadEntrenamientos;
	}

}
