package modelo;

// Generated 11/12/2011 04:17:03 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ClaseMaterial generated by hbm2java
 */
@Entity
@Table(name = "clase_material")
public class ClaseMaterial implements java.io.Serializable {

	private String codigoClaseMaterial;
	private String descripcion;
	private char estatus;
	private Set<TipoMaterial> tipoMaterials = new HashSet<TipoMaterial>(0);

	public ClaseMaterial() {
	}

	public ClaseMaterial(String codigoClaseMaterial, String descripcion,
			char estatus) {
		this.codigoClaseMaterial = codigoClaseMaterial;
		this.descripcion = descripcion;
		this.estatus = estatus;
	}

	public ClaseMaterial(String codigoClaseMaterial, String descripcion,
			char estatus, Set<TipoMaterial> tipoMaterials) {
		this.codigoClaseMaterial = codigoClaseMaterial;
		this.descripcion = descripcion;
		this.estatus = estatus;
		this.tipoMaterials = tipoMaterials;
	}

	@Id
	@Column(name = "codigo_clase_material", unique = true, nullable = false)
	public String getCodigoClaseMaterial() {
		return this.codigoClaseMaterial;
	}

	public void setCodigoClaseMaterial(String codigoClaseMaterial) {
		this.codigoClaseMaterial = codigoClaseMaterial;
	}

	@Column(name = "descripcion", nullable = false)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "claseMaterial")
	public Set<TipoMaterial> getTipoMaterials() {
		return this.tipoMaterials;
	}

	public void setTipoMaterials(Set<TipoMaterial> tipoMaterials) {
		this.tipoMaterials = tipoMaterials;
	}

}
