package modelo;

// Generated 12/12/2011 09:17:13 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name = "cliente")
public class Cliente implements java.io.Serializable {

	private String rif;
	private Parroquia parroquia;
	private String correoElectronico;
	private String cuentaFacebook;
	private String cuentaTwitter;
	private String direccion;
	private char estatus;
	private String fax;
	private Date fechaIngreso;
	private String nombre;
	private String telefono1;
	private String telefono2;

	public Cliente() {
	}

	public Cliente(String rif, Parroquia parroquia, String direccion,
			char estatus, Date fechaIngreso, String nombre, String telefono1) {
		this.rif = rif;
		this.parroquia = parroquia;
		this.direccion = direccion;
		this.estatus = estatus;
		this.fechaIngreso = fechaIngreso;
		this.nombre = nombre;
		this.telefono1 = telefono1;
	}

	public Cliente(String rif, Parroquia parroquia, String correoElectronico,
			String cuentaFacebook, String cuentaTwitter, String direccion,
			char estatus, String fax, Date fechaIngreso, String nombre,
			String telefono1, String telefono2) {
		this.rif = rif;
		this.parroquia = parroquia;
		this.correoElectronico = correoElectronico;
		this.cuentaFacebook = cuentaFacebook;
		this.cuentaTwitter = cuentaTwitter;
		this.direccion = direccion;
		this.estatus = estatus;
		this.fax = fax;
		this.fechaIngreso = fechaIngreso;
		this.nombre = nombre;
		this.telefono1 = telefono1;
		this.telefono2 = telefono2;
	}

	@Id
	@Column(name = "rif", unique = true, nullable = false)
	public String getRif() {
		return this.rif;
	}

	public void setRif(String rif) {
		this.rif = rif;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_parroquia", nullable = false)
	public Parroquia getParroquia() {
		return this.parroquia;
	}

	public void setParroquia(Parroquia parroquia) {
		this.parroquia = parroquia;
	}

	@Column(name = "correo_electronico")
	public String getCorreoElectronico() {
		return this.correoElectronico;
	}

	public void setCorreoElectronico(String correoElectronico) {
		this.correoElectronico = correoElectronico;
	}

	@Column(name = "cuenta_facebook")
	public String getCuentaFacebook() {
		return this.cuentaFacebook;
	}

	public void setCuentaFacebook(String cuentaFacebook) {
		this.cuentaFacebook = cuentaFacebook;
	}

	@Column(name = "cuenta_twitter")
	public String getCuentaTwitter() {
		return this.cuentaTwitter;
	}

	public void setCuentaTwitter(String cuentaTwitter) {
		this.cuentaTwitter = cuentaTwitter;
	}

	@Column(name = "direccion", nullable = false)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@Column(name = "fax")
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_ingreso", nullable = false, length = 13)
	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "telefono1", nullable = false)
	public String getTelefono1() {
		return this.telefono1;
	}

	public void setTelefono1(String telefono1) {
		this.telefono1 = telefono1;
	}

	@Column(name = "telefono2")
	public String getTelefono2() {
		return this.telefono2;
	}

	public void setTelefono2(String telefono2) {
		this.telefono2 = telefono2;
	}

}
