package modelo;

// Generated 11/02/2012 01:49:19 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ComisionActividad generated by hbm2java
 */
@Entity
@Table(name = "comision_actividad", schema = "public")
public class ComisionActividad implements java.io.Serializable {

	private int codigoComisionActividad;
	private DatoBasico datoBasico;
	private Actividad actividad;

	public ComisionActividad() {
	}

	public ComisionActividad(int codigoComisionActividad,
			DatoBasico datoBasico, Actividad actividad) {
		this.codigoComisionActividad = codigoComisionActividad;
		this.datoBasico = datoBasico;
		this.actividad = actividad;
	}

	@Id
	@Column(name = "codigo_comision_actividad", unique = true, nullable = false)
	public int getCodigoComisionActividad() {
		return this.codigoComisionActividad;
	}

	public void setCodigoComisionActividad(int codigoComisionActividad) {
		this.codigoComisionActividad = codigoComisionActividad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_comision", nullable = false)
	public DatoBasico getDatoBasico() {
		return this.datoBasico;
	}

	public void setDatoBasico(DatoBasico datoBasico) {
		this.datoBasico = datoBasico;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_actividad", nullable = false)
	public Actividad getActividad() {
		return this.actividad;
	}

	public void setActividad(Actividad actividad) {
		this.actividad = actividad;
	}

}
