package modelo;

// Generated 27/01/2012 03:27:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ComisionFamiliar generated by hbm2java
 */
@Entity
@Table(name = "comision_familiar", schema = "public")
public class ComisionFamiliar implements java.io.Serializable {

	private int codigoComisionFamiliar;
	private DatoBasico datoBasico;
	private FamiliarJugador familiarJugador;
	private char estatus1;
	private Set<TareaActividadPlanificada> tareaActividadPlanificadas = new HashSet<TareaActividadPlanificada>(
			0);

	public ComisionFamiliar() {
	}

	public ComisionFamiliar(int codigoComisionFamiliar, DatoBasico datoBasico,
			FamiliarJugador familiarJugador, char estatus1) {
		this.codigoComisionFamiliar = codigoComisionFamiliar;
		this.datoBasico = datoBasico;
		this.familiarJugador = familiarJugador;
		this.estatus1 = estatus1;
	}

	public ComisionFamiliar(int codigoComisionFamiliar, DatoBasico datoBasico,
			FamiliarJugador familiarJugador, char estatus1,
			Set<TareaActividadPlanificada> tareaActividadPlanificadas) {
		this.codigoComisionFamiliar = codigoComisionFamiliar;
		this.datoBasico = datoBasico;
		this.familiarJugador = familiarJugador;
		this.estatus1 = estatus1;
		this.tareaActividadPlanificadas = tareaActividadPlanificadas;
	}

	@Id
	@Column(name = "codigo_comision_familiar", unique = true, nullable = false)
	public int getCodigoComisionFamiliar() {
		return this.codigoComisionFamiliar;
	}

	public void setCodigoComisionFamiliar(int codigoComisionFamiliar) {
		this.codigoComisionFamiliar = codigoComisionFamiliar;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_comision", nullable = false)
	public DatoBasico getDatoBasico() {
		return this.datoBasico;
	}

	public void setDatoBasico(DatoBasico datoBasico) {
		this.datoBasico = datoBasico;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_familiar_jugador", nullable = false)
	public FamiliarJugador getFamiliarJugador() {
		return this.familiarJugador;
	}

	public void setFamiliarJugador(FamiliarJugador familiarJugador) {
		this.familiarJugador = familiarJugador;
	}

	@Column(name = "estatus_1", nullable = false, length = 1)
	public char getEstatus1() {
		return this.estatus1;
	}

	public void setEstatus1(char estatus1) {
		this.estatus1 = estatus1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "comisionFamiliar")
	public Set<TareaActividadPlanificada> getTareaActividadPlanificadas() {
		return this.tareaActividadPlanificadas;
	}

	public void setTareaActividadPlanificadas(
			Set<TareaActividadPlanificada> tareaActividadPlanificadas) {
		this.tareaActividadPlanificadas = tareaActividadPlanificadas;
	}

}
