package modelo;

// Generated 28/12/2011 03:24:38 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Competencia generated by hbm2java
 */
@Entity
@Table(name = "competencia", schema = "public")
public class Competencia implements java.io.Serializable {

	private int codigoCompetencia;
	private DatoBasico datoBasicoByCodigoEstadoCompetencia;
	private ModalidadCompetencia modalidadCompetencia;
	private DatoBasico datoBasicoByCodigoOrganizacion;
	private DatoBasico datoBasicoByCodigoEstado;
	private LapsoDeportivo lapsoDeportivo;
	private int codigoTipoCompetencia;
	private String nombre;
	private Date fechaInicio;
	private Date fechaFin;
	private int cantidadEquipo;
	private int cantidadFase;
	private int cantidadJugador;
	private float montoInscripcion;
	private String condicionesGenerales;
	private String desempate;
	private String extrainning;
	private byte[] documento;
	private Set<ActividadCalendario> actividadCalendarios = new HashSet<ActividadCalendario>(
			0);
	private Set<FaseCompetencia> faseCompetencias = new HashSet<FaseCompetencia>(
			0);
	private Set<CategoriaCompetencia> categoriaCompetencias = new HashSet<CategoriaCompetencia>(
			0);
	private Set<EquipoCompetencia> equipoCompetencias = new HashSet<EquipoCompetencia>(
			0);
	private Set<Liga> ligas = new HashSet<Liga>(0);
	private Set<DatoDeportivo> datoDeportivos = new HashSet<DatoDeportivo>(0);
	private Set<Hospedaje> hospedajes = new HashSet<Hospedaje>(0);
	private Set<RosterCompetencia> rosterCompetencias = new HashSet<RosterCompetencia>(
			0);
	private Set<IndicadorCategoriaCompetencia> indicadorCategoriaCompetencias = new HashSet<IndicadorCategoriaCompetencia>(
			0);
	private Set<Juego> juegos = new HashSet<Juego>(0);

	public Competencia() {
	}

	public Competencia(int codigoCompetencia,
			DatoBasico datoBasicoByCodigoEstadoCompetencia,
			DatoBasico datoBasicoByCodigoOrganizacion,
			DatoBasico datoBasicoByCodigoEstado, LapsoDeportivo lapsoDeportivo,
			int codigoTipoCompetencia, String nombre, Date fechaInicio,
			Date fechaFin, int cantidadEquipo, int cantidadFase,
			int cantidadJugador, float montoInscripcion,
			String condicionesGenerales, String desempate, String extrainning) {
		this.codigoCompetencia = codigoCompetencia;
		this.datoBasicoByCodigoEstadoCompetencia = datoBasicoByCodigoEstadoCompetencia;
		this.datoBasicoByCodigoOrganizacion = datoBasicoByCodigoOrganizacion;
		this.datoBasicoByCodigoEstado = datoBasicoByCodigoEstado;
		this.lapsoDeportivo = lapsoDeportivo;
		this.codigoTipoCompetencia = codigoTipoCompetencia;
		this.nombre = nombre;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.cantidadEquipo = cantidadEquipo;
		this.cantidadFase = cantidadFase;
		this.cantidadJugador = cantidadJugador;
		this.montoInscripcion = montoInscripcion;
		this.condicionesGenerales = condicionesGenerales;
		this.desempate = desempate;
		this.extrainning = extrainning;
	}

	public Competencia(int codigoCompetencia,
			DatoBasico datoBasicoByCodigoEstadoCompetencia,
			ModalidadCompetencia modalidadCompetencia,
			DatoBasico datoBasicoByCodigoOrganizacion,
			DatoBasico datoBasicoByCodigoEstado, LapsoDeportivo lapsoDeportivo,
			int codigoTipoCompetencia, String nombre, Date fechaInicio,
			Date fechaFin, int cantidadEquipo, int cantidadFase,
			int cantidadJugador, float montoInscripcion,
			String condicionesGenerales, String desempate, String extrainning,
			byte[] documento, Set<ActividadCalendario> actividadCalendarios,
			Set<FaseCompetencia> faseCompetencias,
			Set<CategoriaCompetencia> categoriaCompetencias,
			Set<EquipoCompetencia> equipoCompetencias, Set<Liga> ligas,
			Set<DatoDeportivo> datoDeportivos, Set<Hospedaje> hospedajes,
			Set<RosterCompetencia> rosterCompetencias,
			Set<IndicadorCategoriaCompetencia> indicadorCategoriaCompetencias,
			Set<Juego> juegos) {
		this.codigoCompetencia = codigoCompetencia;
		this.datoBasicoByCodigoEstadoCompetencia = datoBasicoByCodigoEstadoCompetencia;
		this.modalidadCompetencia = modalidadCompetencia;
		this.datoBasicoByCodigoOrganizacion = datoBasicoByCodigoOrganizacion;
		this.datoBasicoByCodigoEstado = datoBasicoByCodigoEstado;
		this.lapsoDeportivo = lapsoDeportivo;
		this.codigoTipoCompetencia = codigoTipoCompetencia;
		this.nombre = nombre;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.cantidadEquipo = cantidadEquipo;
		this.cantidadFase = cantidadFase;
		this.cantidadJugador = cantidadJugador;
		this.montoInscripcion = montoInscripcion;
		this.condicionesGenerales = condicionesGenerales;
		this.desempate = desempate;
		this.extrainning = extrainning;
		this.documento = documento;
		this.actividadCalendarios = actividadCalendarios;
		this.faseCompetencias = faseCompetencias;
		this.categoriaCompetencias = categoriaCompetencias;
		this.equipoCompetencias = equipoCompetencias;
		this.ligas = ligas;
		this.datoDeportivos = datoDeportivos;
		this.hospedajes = hospedajes;
		this.rosterCompetencias = rosterCompetencias;
		this.indicadorCategoriaCompetencias = indicadorCategoriaCompetencias;
		this.juegos = juegos;
	}

	@Id
	@Column(name = "codigo_competencia", unique = true, nullable = false)
	public int getCodigoCompetencia() {
		return this.codigoCompetencia;
	}

	public void setCodigoCompetencia(int codigoCompetencia) {
		this.codigoCompetencia = codigoCompetencia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_estado_competencia", nullable = false)
	public DatoBasico getDatoBasicoByCodigoEstadoCompetencia() {
		return this.datoBasicoByCodigoEstadoCompetencia;
	}

	public void setDatoBasicoByCodigoEstadoCompetencia(
			DatoBasico datoBasicoByCodigoEstadoCompetencia) {
		this.datoBasicoByCodigoEstadoCompetencia = datoBasicoByCodigoEstadoCompetencia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_modalidad_competencia")
	public ModalidadCompetencia getModalidadCompetencia() {
		return this.modalidadCompetencia;
	}

	public void setModalidadCompetencia(
			ModalidadCompetencia modalidadCompetencia) {
		this.modalidadCompetencia = modalidadCompetencia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_organizacion", nullable = false)
	public DatoBasico getDatoBasicoByCodigoOrganizacion() {
		return this.datoBasicoByCodigoOrganizacion;
	}

	public void setDatoBasicoByCodigoOrganizacion(
			DatoBasico datoBasicoByCodigoOrganizacion) {
		this.datoBasicoByCodigoOrganizacion = datoBasicoByCodigoOrganizacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_estado", nullable = false)
	public DatoBasico getDatoBasicoByCodigoEstado() {
		return this.datoBasicoByCodigoEstado;
	}

	public void setDatoBasicoByCodigoEstado(DatoBasico datoBasicoByCodigoEstado) {
		this.datoBasicoByCodigoEstado = datoBasicoByCodigoEstado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_lapso_deportivo", nullable = false)
	public LapsoDeportivo getLapsoDeportivo() {
		return this.lapsoDeportivo;
	}

	public void setLapsoDeportivo(LapsoDeportivo lapsoDeportivo) {
		this.lapsoDeportivo = lapsoDeportivo;
	}

	@Column(name = "codigo_tipo_competencia", nullable = false)
	public int getCodigoTipoCompetencia() {
		return this.codigoTipoCompetencia;
	}

	public void setCodigoTipoCompetencia(int codigoTipoCompetencia) {
		this.codigoTipoCompetencia = codigoTipoCompetencia;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_inicio", nullable = false, length = 13)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_fin", nullable = false, length = 13)
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	@Column(name = "cantidad_equipo", nullable = false)
	public int getCantidadEquipo() {
		return this.cantidadEquipo;
	}

	public void setCantidadEquipo(int cantidadEquipo) {
		this.cantidadEquipo = cantidadEquipo;
	}

	@Column(name = "cantidad_fase", nullable = false)
	public int getCantidadFase() {
		return this.cantidadFase;
	}

	public void setCantidadFase(int cantidadFase) {
		this.cantidadFase = cantidadFase;
	}

	@Column(name = "cantidad_jugador", nullable = false)
	public int getCantidadJugador() {
		return this.cantidadJugador;
	}

	public void setCantidadJugador(int cantidadJugador) {
		this.cantidadJugador = cantidadJugador;
	}

	@Column(name = "monto_inscripcion", nullable = false, precision = 8, scale = 8)
	public float getMontoInscripcion() {
		return this.montoInscripcion;
	}

	public void setMontoInscripcion(float montoInscripcion) {
		this.montoInscripcion = montoInscripcion;
	}

	@Column(name = "condiciones_generales", nullable = false)
	public String getCondicionesGenerales() {
		return this.condicionesGenerales;
	}

	public void setCondicionesGenerales(String condicionesGenerales) {
		this.condicionesGenerales = condicionesGenerales;
	}

	@Column(name = "desempate", nullable = false)
	public String getDesempate() {
		return this.desempate;
	}

	public void setDesempate(String desempate) {
		this.desempate = desempate;
	}

	@Column(name = "extrainning", nullable = false)
	public String getExtrainning() {
		return this.extrainning;
	}

	public void setExtrainning(String extrainning) {
		this.extrainning = extrainning;
	}

	@Column(name = "documento")
	public byte[] getDocumento() {
		return this.documento;
	}

	public void setDocumento(byte[] documento) {
		this.documento = documento;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "competencia")
	public Set<ActividadCalendario> getActividadCalendarios() {
		return this.actividadCalendarios;
	}

	public void setActividadCalendarios(
			Set<ActividadCalendario> actividadCalendarios) {
		this.actividadCalendarios = actividadCalendarios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "competencia")
	public Set<FaseCompetencia> getFaseCompetencias() {
		return this.faseCompetencias;
	}

	public void setFaseCompetencias(Set<FaseCompetencia> faseCompetencias) {
		this.faseCompetencias = faseCompetencias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "competencia")
	public Set<CategoriaCompetencia> getCategoriaCompetencias() {
		return this.categoriaCompetencias;
	}

	public void setCategoriaCompetencias(
			Set<CategoriaCompetencia> categoriaCompetencias) {
		this.categoriaCompetencias = categoriaCompetencias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "competencia")
	public Set<EquipoCompetencia> getEquipoCompetencias() {
		return this.equipoCompetencias;
	}

	public void setEquipoCompetencias(Set<EquipoCompetencia> equipoCompetencias) {
		this.equipoCompetencias = equipoCompetencias;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "competencias")
	public Set<Liga> getLigas() {
		return this.ligas;
	}

	public void setLigas(Set<Liga> ligas) {
		this.ligas = ligas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "competencia")
	public Set<DatoDeportivo> getDatoDeportivos() {
		return this.datoDeportivos;
	}

	public void setDatoDeportivos(Set<DatoDeportivo> datoDeportivos) {
		this.datoDeportivos = datoDeportivos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "competencia")
	public Set<Hospedaje> getHospedajes() {
		return this.hospedajes;
	}

	public void setHospedajes(Set<Hospedaje> hospedajes) {
		this.hospedajes = hospedajes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "competencia")
	public Set<RosterCompetencia> getRosterCompetencias() {
		return this.rosterCompetencias;
	}

	public void setRosterCompetencias(Set<RosterCompetencia> rosterCompetencias) {
		this.rosterCompetencias = rosterCompetencias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "competencia")
	public Set<IndicadorCategoriaCompetencia> getIndicadorCategoriaCompetencias() {
		return this.indicadorCategoriaCompetencias;
	}

	public void setIndicadorCategoriaCompetencias(
			Set<IndicadorCategoriaCompetencia> indicadorCategoriaCompetencias) {
		this.indicadorCategoriaCompetencias = indicadorCategoriaCompetencias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "competencia")
	public Set<Juego> getJuegos() {
		return this.juegos;
	}

	public void setJuegos(Set<Juego> juegos) {
		this.juegos = juegos;
	}

}
