package modelo;

// Generated 11/01/2012 03:50:04 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CondicionCompetencia generated by hbm2java
 */
@Entity
@Table(name = "condicion_competencia", schema = "public")
public class CondicionCompetencia implements java.io.Serializable {

	private CondicionCompetenciaId id;
	private TipoCompetencia tipoCompetencia;
	private DatoBasico datoBasico;
	private boolean aplica;

	public CondicionCompetencia() {
	}

	public CondicionCompetencia(CondicionCompetenciaId id,
			TipoCompetencia tipoCompetencia, DatoBasico datoBasico,
			boolean aplica) {
		this.id = id;
		this.tipoCompetencia = tipoCompetencia;
		this.datoBasico = datoBasico;
		this.aplica = aplica;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codigoCondicion", column = @Column(name = "codigo_condicion", nullable = false)),
			@AttributeOverride(name = "codigoTipoCompetencia", column = @Column(name = "codigo_tipo_competencia", nullable = false)) })
	public CondicionCompetenciaId getId() {
		return this.id;
	}

	public void setId(CondicionCompetenciaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_tipo_competencia", nullable = false, insertable = false, updatable = false)
	public TipoCompetencia getTipoCompetencia() {
		return this.tipoCompetencia;
	}

	public void setTipoCompetencia(TipoCompetencia tipoCompetencia) {
		this.tipoCompetencia = tipoCompetencia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_condicion", nullable = false, insertable = false, updatable = false)
	public DatoBasico getDatoBasico() {
		return this.datoBasico;
	}

	public void setDatoBasico(DatoBasico datoBasico) {
		this.datoBasico = datoBasico;
	}

	@Column(name = "aplica", nullable = false)
	public boolean isAplica() {
		return this.aplica;
	}

	public void setAplica(boolean aplica) {
		this.aplica = aplica;
	}

}
