package modelo;

// Generated 28/12/2011 03:24:38 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ConstanteCategoria generated by hbm2java
 */
@Entity
@Table(name = "constante_categoria", schema = "public")
public class ConstanteCategoria implements java.io.Serializable {

	private ConstanteCategoriaId id;
	private Constante constante;
	private Categoria categoria;
	private int valor;

	public ConstanteCategoria() {
	}

	public ConstanteCategoria(ConstanteCategoriaId id, Constante constante,
			Categoria categoria, int valor) {
		this.id = id;
		this.constante = constante;
		this.categoria = categoria;
		this.valor = valor;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codigoConstanteCategoria", column = @Column(name = "codigo_constante_categoria", nullable = false)),
			@AttributeOverride(name = "codigoConstante", column = @Column(name = "codigo_constante", nullable = false)) })
	public ConstanteCategoriaId getId() {
		return this.id;
	}

	public void setId(ConstanteCategoriaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_constante", nullable = false, insertable = false, updatable = false)
	public Constante getConstante() {
		return this.constante;
	}

	public void setConstante(Constante constante) {
		this.constante = constante;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_categoria_1", nullable = false)
	public Categoria getCategoria() {
		return this.categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	@Column(name = "valor", nullable = false)
	public int getValor() {
		return this.valor;
	}

	public void setValor(int valor) {
		this.valor = valor;
	}

}
