package modelo;

// Generated 28/12/2011 03:24:38 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DatoDeportivoId generated by hbm2java
 */
@Embeddable
public class DatoDeportivoId implements java.io.Serializable {

	private int codigoCompetencia;
	private String cedulaRif;

	public DatoDeportivoId() {
	}

	public DatoDeportivoId(int codigoCompetencia, String cedulaRif) {
		this.codigoCompetencia = codigoCompetencia;
		this.cedulaRif = cedulaRif;
	}

	@Column(name = "codigo_competencia", nullable = false)
	public int getCodigoCompetencia() {
		return this.codigoCompetencia;
	}

	public void setCodigoCompetencia(int codigoCompetencia) {
		this.codigoCompetencia = codigoCompetencia;
	}

	@Column(name = "cedula_rif", nullable = false)
	public String getCedulaRif() {
		return this.cedulaRif;
	}

	public void setCedulaRif(String cedulaRif) {
		this.cedulaRif = cedulaRif;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DatoDeportivoId))
			return false;
		DatoDeportivoId castOther = (DatoDeportivoId) other;

		return (this.getCodigoCompetencia() == castOther.getCodigoCompetencia())
				&& ((this.getCedulaRif() == castOther.getCedulaRif()) || (this
						.getCedulaRif() != null
						&& castOther.getCedulaRif() != null && this
						.getCedulaRif().equals(castOther.getCedulaRif())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoCompetencia();
		result = 37 * result
				+ (getCedulaRif() == null ? 0 : this.getCedulaRif().hashCode());
		return result;
	}

}
