package modelo;

// Generated 10/12/2011 12:12:20 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DatoAcademicoEmpleado generated by hbm2java
 */
@Entity
@Table(name = "dato_academico_empleado")
public class DatoAcademicoEmpleado implements java.io.Serializable {

	private String codigoDatoAcademico;
	private Empleado empleado;
	private char estatus;
	private Date fechaEgreso;
	private String instituto;
	private String titulo;

	public DatoAcademicoEmpleado() {
	}

	public DatoAcademicoEmpleado(String codigoDatoAcademico, Empleado empleado,
			char estatus, Date fechaEgreso, String instituto, String titulo) {
		this.codigoDatoAcademico = codigoDatoAcademico;
		this.empleado = empleado;
		this.estatus = estatus;
		this.fechaEgreso = fechaEgreso;
		this.instituto = instituto;
		this.titulo = titulo;
	}

	@Id
	@Column(name = "codigo_dato_academico", unique = true, nullable = false)
	public String getCodigoDatoAcademico() {
		return this.codigoDatoAcademico;
	}

	public void setCodigoDatoAcademico(String codigoDatoAcademico) {
		this.codigoDatoAcademico = codigoDatoAcademico;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cedula", nullable = false)
	public Empleado getEmpleado() {
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_egreso", nullable = false, length = 13)
	public Date getFechaEgreso() {
		return this.fechaEgreso;
	}

	public void setFechaEgreso(Date fechaEgreso) {
		this.fechaEgreso = fechaEgreso;
	}

	@Column(name = "instituto", nullable = false)
	public String getInstituto() {
		return this.instituto;
	}

	public void setInstituto(String instituto) {
		this.instituto = instituto;
	}

	@Column(name = "titulo", nullable = false)
	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

}
