package modelo;

// Generated 24/01/2012 04:28:30 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DesempennoJugador generated by hbm2java
 */
@Entity
@Table(name = "desempenno_jugador", schema = "public")
public class DesempennoJugador implements java.io.Serializable {

	private int codigoDesempennoJugador;
	private AsistenciaJugador asistenciaJugador;
	private ActividadesEjecutadas actividadesEjecutadas;
	private char estatus;
	private Set<PuntuacionJugador> puntuacionJugadors = new HashSet<PuntuacionJugador>(
			0);

	public DesempennoJugador() {
	}

	public DesempennoJugador(int codigoDesempennoJugador,
			AsistenciaJugador asistenciaJugador,
			ActividadesEjecutadas actividadesEjecutadas, char estatus) {
		this.codigoDesempennoJugador = codigoDesempennoJugador;
		this.asistenciaJugador = asistenciaJugador;
		this.actividadesEjecutadas = actividadesEjecutadas;
		this.estatus = estatus;
	}

	public DesempennoJugador(int codigoDesempennoJugador,
			AsistenciaJugador asistenciaJugador,
			ActividadesEjecutadas actividadesEjecutadas, char estatus,
			Set<PuntuacionJugador> puntuacionJugadors) {
		this.codigoDesempennoJugador = codigoDesempennoJugador;
		this.asistenciaJugador = asistenciaJugador;
		this.actividadesEjecutadas = actividadesEjecutadas;
		this.estatus = estatus;
		this.puntuacionJugadors = puntuacionJugadors;
	}

	@Id
	@Column(name = "codigo_desempenno_jugador", unique = true, nullable = false)
	public int getCodigoDesempennoJugador() {
		return this.codigoDesempennoJugador;
	}

	public void setCodigoDesempennoJugador(int codigoDesempennoJugador) {
		this.codigoDesempennoJugador = codigoDesempennoJugador;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_asistencia", nullable = false)
	public AsistenciaJugador getAsistenciaJugador() {
		return this.asistenciaJugador;
	}

	public void setAsistenciaJugador(AsistenciaJugador asistenciaJugador) {
		this.asistenciaJugador = asistenciaJugador;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_actividad_ejecutada", nullable = false)
	public ActividadesEjecutadas getActividadesEjecutadas() {
		return this.actividadesEjecutadas;
	}

	public void setActividadesEjecutadas(
			ActividadesEjecutadas actividadesEjecutadas) {
		this.actividadesEjecutadas = actividadesEjecutadas;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "desempennoJugador")
	public Set<PuntuacionJugador> getPuntuacionJugadors() {
		return this.puntuacionJugadors;
	}

	public void setPuntuacionJugadors(Set<PuntuacionJugador> puntuacionJugadors) {
		this.puntuacionJugadors = puntuacionJugadors;
	}

}
