package modelo;

// Generated 11/01/2012 03:50:04 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DesempeoJugador generated by hbm2java
 */
@Entity
@Table(name = "desempeo_jugador", schema = "public")
public class DesempeoJugador implements java.io.Serializable {

	private DesempeoJugadorId id;
	private AsistenciaJugador asistenciaJugador;
	private ActividadesEjecutadas actividadesEjecutadas;
	private String puntuacion;
	private char estatus;

	public DesempeoJugador() {
	}

	public DesempeoJugador(DesempeoJugadorId id,
			AsistenciaJugador asistenciaJugador,
			ActividadesEjecutadas actividadesEjecutadas, String puntuacion,
			char estatus) {
		this.id = id;
		this.asistenciaJugador = asistenciaJugador;
		this.actividadesEjecutadas = actividadesEjecutadas;
		this.puntuacion = puntuacion;
		this.estatus = estatus;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codigoAsistencia", column = @Column(name = "codigo_asistencia", nullable = false)),
			@AttributeOverride(name = "codigoActividadEjecutada", column = @Column(name = "codigo_actividad_ejecutada", nullable = false)) })
	public DesempeoJugadorId getId() {
		return this.id;
	}

	public void setId(DesempeoJugadorId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_asistencia", nullable = false, insertable = false, updatable = false)
	public AsistenciaJugador getAsistenciaJugador() {
		return this.asistenciaJugador;
	}

	public void setAsistenciaJugador(AsistenciaJugador asistenciaJugador) {
		this.asistenciaJugador = asistenciaJugador;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_actividad_ejecutada", nullable = false, insertable = false, updatable = false)
	public ActividadesEjecutadas getActividadesEjecutadas() {
		return this.actividadesEjecutadas;
	}

	public void setActividadesEjecutadas(
			ActividadesEjecutadas actividadesEjecutadas) {
		this.actividadesEjecutadas = actividadesEjecutadas;
	}

	@Column(name = "puntuacion", nullable = false)
	public String getPuntuacion() {
		return this.puntuacion;
	}

	public void setPuntuacion(String puntuacion) {
		this.puntuacion = puntuacion;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

}
