package modelo;

<<<<<<< HEAD
// Generated 25/01/2012 12:32:42 AM by Hibernate Tools 3.4.0.CR1
=======
<<<<<<< HEAD
// Generated 25/01/2012 12:32:42 AM by Hibernate Tools 3.4.0.CR1
=======
// Generated 24/01/2012 04:28:30 AM by Hibernate Tools 3.4.0.CR1
>>>>>>> 7d4823278d0a354855f5032a99e2b48c65b33e7f
>>>>>>> 9d67536bdd2e3b33aa6400eb3bb09741a4535bb0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DetalleRequisicion generated by hbm2java
 */
@Entity
@Table(name = "detalle_requisicion", schema = "public")
public class DetalleRequisicion implements java.io.Serializable {

	private DetalleRequisicionId id;
	private Material material;
	private Requisicion requisicion;
	private int cantidadSolicitada;
	private Integer cantidadEntregada;
	private char estatus;

	public DetalleRequisicion() {
	}

	public DetalleRequisicion(DetalleRequisicionId id, Material material,
			Requisicion requisicion, int cantidadSolicitada, char estatus) {
		this.id = id;
		this.material = material;
		this.requisicion = requisicion;
		this.cantidadSolicitada = cantidadSolicitada;
		this.estatus = estatus;
	}

	public DetalleRequisicion(DetalleRequisicionId id, Material material,
			Requisicion requisicion, int cantidadSolicitada,
			Integer cantidadEntregada, char estatus) {
		this.id = id;
		this.material = material;
		this.requisicion = requisicion;
		this.cantidadSolicitada = cantidadSolicitada;
		this.cantidadEntregada = cantidadEntregada;
		this.estatus = estatus;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codigoMaterial", column = @Column(name = "codigo_material", nullable = false)),
			@AttributeOverride(name = "codigoRequisicion", column = @Column(name = "codigo_requisicion", nullable = false)) })
	public DetalleRequisicionId getId() {
		return this.id;
	}

	public void setId(DetalleRequisicionId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_material", nullable = false, insertable = false, updatable = false)
	public Material getMaterial() {
		return this.material;
	}

	public void setMaterial(Material material) {
		this.material = material;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_requisicion", nullable = false, insertable = false, updatable = false)
	public Requisicion getRequisicion() {
		return this.requisicion;
	}

	public void setRequisicion(Requisicion requisicion) {
		this.requisicion = requisicion;
	}

	@Column(name = "cantidad_solicitada", nullable = false)
	public int getCantidadSolicitada() {
		return this.cantidadSolicitada;
	}

	public void setCantidadSolicitada(int cantidadSolicitada) {
		this.cantidadSolicitada = cantidadSolicitada;
	}

	@Column(name = "cantidad_entregada")
	public Integer getCantidadEntregada() {
		return this.cantidadEntregada;
	}

	public void setCantidadEntregada(Integer cantidadEntregada) {
		this.cantidadEntregada = cantidadEntregada;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

}
