package modelo;

// Generated 11/01/2012 03:50:04 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DetalleSeguridadFuncional generated by hbm2java
 */
@Entity
@Table(name = "detalle_seguridad_funcional", schema = "public")
public class DetalleSeguridadFuncional implements java.io.Serializable {

	private DetalleSeguridadFuncionalId id;
	private TipoDato tipoDato;
	private Usuario usuario;
	private SeguridadFuncional seguridadFuncional;
	private Date fechaRegistro;
	private String codigoRegistro;
	private boolean agregar;
	private boolean modificar;
	private boolean eliminar;

	public DetalleSeguridadFuncional() {
	}

	public DetalleSeguridadFuncional(DetalleSeguridadFuncionalId id,
			TipoDato tipoDato, Usuario usuario,
			SeguridadFuncional seguridadFuncional, Date fechaRegistro,
			String codigoRegistro, boolean agregar, boolean modificar,
			boolean eliminar) {
		this.id = id;
		this.tipoDato = tipoDato;
		this.usuario = usuario;
		this.seguridadFuncional = seguridadFuncional;
		this.fechaRegistro = fechaRegistro;
		this.codigoRegistro = codigoRegistro;
		this.agregar = agregar;
		this.modificar = modificar;
		this.eliminar = eliminar;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codigoSeguridad", column = @Column(name = "codigo_seguridad", nullable = false)),
			@AttributeOverride(name = "codigoTipoDato", column = @Column(name = "codigo_tipo_dato", nullable = false)) })
	public DetalleSeguridadFuncionalId getId() {
		return this.id;
	}

	public void setId(DetalleSeguridadFuncionalId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_tipo_dato", nullable = false, insertable = false, updatable = false)
	public TipoDato getTipoDato() {
		return this.tipoDato;
	}

	public void setTipoDato(TipoDato tipoDato) {
		this.tipoDato = tipoDato;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cedula_rif", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_seguridad", nullable = false, insertable = false, updatable = false)
	public SeguridadFuncional getSeguridadFuncional() {
		return this.seguridadFuncional;
	}

	public void setSeguridadFuncional(SeguridadFuncional seguridadFuncional) {
		this.seguridadFuncional = seguridadFuncional;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_registro", nullable = false, length = 13)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@Column(name = "codigo_registro", nullable = false)
	public String getCodigoRegistro() {
		return this.codigoRegistro;
	}

	public void setCodigoRegistro(String codigoRegistro) {
		this.codigoRegistro = codigoRegistro;
	}

	@Column(name = "agregar", nullable = false)
	public boolean isAgregar() {
		return this.agregar;
	}

	public void setAgregar(boolean agregar) {
		this.agregar = agregar;
	}

	@Column(name = "modificar", nullable = false)
	public boolean isModificar() {
		return this.modificar;
	}

	public void setModificar(boolean modificar) {
		this.modificar = modificar;
	}

	@Column(name = "eliminar", nullable = false)
	public boolean isEliminar() {
		return this.eliminar;
	}

	public void setEliminar(boolean eliminar) {
		this.eliminar = eliminar;
	}

}
