package modelo;

// Generated 28/12/2011 03:24:38 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DonacionMaterial generated by hbm2java
 */
@Entity
@Table(name = "donacion_material", schema = "public")
public class DonacionMaterial implements java.io.Serializable {

	private DonacionMaterialId id;
	private DocumentoAcreedor documentoAcreedor;
	private Material material;
	private double montoEstimado;
	private char estatus;
	private int cantidad;

	public DonacionMaterial() {
	}

	public DonacionMaterial(DonacionMaterialId id,
			DocumentoAcreedor documentoAcreedor, Material material,
			double montoEstimado, char estatus, int cantidad) {
		this.id = id;
		this.documentoAcreedor = documentoAcreedor;
		this.material = material;
		this.montoEstimado = montoEstimado;
		this.estatus = estatus;
		this.cantidad = cantidad;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codigoMaterial", column = @Column(name = "codigo_material", nullable = false)),
			@AttributeOverride(name = "codigoDocumentoAcreedor", column = @Column(name = "codigo_documento_acreedor", nullable = false)) })
	public DonacionMaterialId getId() {
		return this.id;
	}

	public void setId(DonacionMaterialId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_documento_acreedor", nullable = false, insertable = false, updatable = false)
	public DocumentoAcreedor getDocumentoAcreedor() {
		return this.documentoAcreedor;
	}

	public void setDocumentoAcreedor(DocumentoAcreedor documentoAcreedor) {
		this.documentoAcreedor = documentoAcreedor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_material", nullable = false, insertable = false, updatable = false)
	public Material getMaterial() {
		return this.material;
	}

	public void setMaterial(Material material) {
		this.material = material;
	}

	@Column(name = "monto_estimado", nullable = false, precision = 17, scale = 17)
	public double getMontoEstimado() {
		return this.montoEstimado;
	}

	public void setMontoEstimado(double montoEstimado) {
		this.montoEstimado = montoEstimado;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@Column(name = "cantidad", nullable = false)
	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

}
