package modelo;

// Generated Dec 23, 2011 1:26:53 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EgresoFormaPago generated by hbm2java
 */
@Entity
@Table(name = "egreso_forma_pago", schema = "public")
public class EgresoFormaPago implements java.io.Serializable {

	private int codigoEgresoFormaPago;
	private Egreso egreso;
	private DatoBasico datoBasicoByCodigoFormaPago;
	private DatoBasico datoBasicoByCodigoBanco;
	private DatoBasico datoBasicoByCodigoTarjeta;
	private double monto;
	private char estatus;
	private String numeroDocuemntoPago;

	public EgresoFormaPago() {
	}

	public EgresoFormaPago(int codigoEgresoFormaPago, double monto, char estatus) {
		this.codigoEgresoFormaPago = codigoEgresoFormaPago;
		this.monto = monto;
		this.estatus = estatus;
	}

	public EgresoFormaPago(int codigoEgresoFormaPago, Egreso egreso,
			DatoBasico datoBasicoByCodigoFormaPago,
			DatoBasico datoBasicoByCodigoBanco,
			DatoBasico datoBasicoByCodigoTarjeta, double monto, char estatus,
			String numeroDocuemntoPago) {
		this.codigoEgresoFormaPago = codigoEgresoFormaPago;
		this.egreso = egreso;
		this.datoBasicoByCodigoFormaPago = datoBasicoByCodigoFormaPago;
		this.datoBasicoByCodigoBanco = datoBasicoByCodigoBanco;
		this.datoBasicoByCodigoTarjeta = datoBasicoByCodigoTarjeta;
		this.monto = monto;
		this.estatus = estatus;
		this.numeroDocuemntoPago = numeroDocuemntoPago;
	}

	@Id
	@Column(name = "codigo_egreso_forma_pago", unique = true, nullable = false)
	public int getCodigoEgresoFormaPago() {
		return this.codigoEgresoFormaPago;
	}

	public void setCodigoEgresoFormaPago(int codigoEgresoFormaPago) {
		this.codigoEgresoFormaPago = codigoEgresoFormaPago;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "numero_documento")
	public Egreso getEgreso() {
		return this.egreso;
	}

	public void setEgreso(Egreso egreso) {
		this.egreso = egreso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_forma_pago")
	public DatoBasico getDatoBasicoByCodigoFormaPago() {
		return this.datoBasicoByCodigoFormaPago;
	}

	public void setDatoBasicoByCodigoFormaPago(
			DatoBasico datoBasicoByCodigoFormaPago) {
		this.datoBasicoByCodigoFormaPago = datoBasicoByCodigoFormaPago;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_banco")
	public DatoBasico getDatoBasicoByCodigoBanco() {
		return this.datoBasicoByCodigoBanco;
	}

	public void setDatoBasicoByCodigoBanco(DatoBasico datoBasicoByCodigoBanco) {
		this.datoBasicoByCodigoBanco = datoBasicoByCodigoBanco;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_tarjeta")
	public DatoBasico getDatoBasicoByCodigoTarjeta() {
		return this.datoBasicoByCodigoTarjeta;
	}

	public void setDatoBasicoByCodigoTarjeta(
			DatoBasico datoBasicoByCodigoTarjeta) {
		this.datoBasicoByCodigoTarjeta = datoBasicoByCodigoTarjeta;
	}

	@Column(name = "monto", nullable = false, precision = 17, scale = 17)
	public double getMonto() {
		return this.monto;
	}

	public void setMonto(double monto) {
		this.monto = monto;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@Column(name = "numero_docuemnto_pago")
	public String getNumeroDocuemntoPago() {
		return this.numeroDocuemntoPago;
	}

	public void setNumeroDocuemntoPago(String numeroDocuemntoPago) {
		this.numeroDocuemntoPago = numeroDocuemntoPago;
	}

}
