package modelo;

// Generated 14/12/2011 05:11:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EmpleadoMantenimientoPlanificado generated by hbm2java
 */
@Entity
@Table(name = "empleado_mantenimiento_planificado")
public class EmpleadoMantenimientoPlanificado implements java.io.Serializable {

	private EmpleadoMantenimientoPlanificadoId id;
	private PlanificacionMantenimiento planificacionMantenimiento;
	private Empleado empleado;
	private char estatus;
	private Set<TareaMantenimientoPlanificado> tareaMantenimientoPlanificadosForFk6b2b18d580e2ecc8 = new HashSet<TareaMantenimientoPlanificado>(
			0);
	private Set<TareaMantenimientoPlanificado> tareaMantenimientoPlanificadosForEmpleadoMantenimientoPlanificadoTareaMantenimientoPlani573 = new HashSet<TareaMantenimientoPlanificado>(
			0);

	public EmpleadoMantenimientoPlanificado() {
	}

	public EmpleadoMantenimientoPlanificado(
			EmpleadoMantenimientoPlanificadoId id,
			PlanificacionMantenimiento planificacionMantenimiento,
			Empleado empleado, char estatus) {
		this.id = id;
		this.planificacionMantenimiento = planificacionMantenimiento;
		this.empleado = empleado;
		this.estatus = estatus;
	}

	public EmpleadoMantenimientoPlanificado(
			EmpleadoMantenimientoPlanificadoId id,
			PlanificacionMantenimiento planificacionMantenimiento,
			Empleado empleado,
			char estatus,
			Set<TareaMantenimientoPlanificado> tareaMantenimientoPlanificadosForFk6b2b18d580e2ecc8,
			Set<TareaMantenimientoPlanificado> tareaMantenimientoPlanificadosForEmpleadoMantenimientoPlanificadoTareaMantenimientoPlani573) {
		this.id = id;
		this.planificacionMantenimiento = planificacionMantenimiento;
		this.empleado = empleado;
		this.estatus = estatus;
		this.tareaMantenimientoPlanificadosForFk6b2b18d580e2ecc8 = tareaMantenimientoPlanificadosForFk6b2b18d580e2ecc8;
		this.tareaMantenimientoPlanificadosForEmpleadoMantenimientoPlanificadoTareaMantenimientoPlani573 = tareaMantenimientoPlanificadosForEmpleadoMantenimientoPlanificadoTareaMantenimientoPlani573;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codigoPlanificacionMantenimiento", column = @Column(name = "codigo_planificacion_mantenimiento", nullable = false)),
			@AttributeOverride(name = "cedula", column = @Column(name = "cedula", nullable = false)) })
	public EmpleadoMantenimientoPlanificadoId getId() {
		return this.id;
	}

	public void setId(EmpleadoMantenimientoPlanificadoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_planificacion_mantenimiento", nullable = false, insertable = false, updatable = false)
	public PlanificacionMantenimiento getPlanificacionMantenimiento() {
		return this.planificacionMantenimiento;
	}

	public void setPlanificacionMantenimiento(
			PlanificacionMantenimiento planificacionMantenimiento) {
		this.planificacionMantenimiento = planificacionMantenimiento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cedula", nullable = false, insertable = false, updatable = false)
	public Empleado getEmpleado() {
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empleadoMantenimientoPlanificadoByFk6b2b18d580e2ecc8")
	public Set<TareaMantenimientoPlanificado> getTareaMantenimientoPlanificadosForFk6b2b18d580e2ecc8() {
		return this.tareaMantenimientoPlanificadosForFk6b2b18d580e2ecc8;
	}

	public void setTareaMantenimientoPlanificadosForFk6b2b18d580e2ecc8(
			Set<TareaMantenimientoPlanificado> tareaMantenimientoPlanificadosForFk6b2b18d580e2ecc8) {
		this.tareaMantenimientoPlanificadosForFk6b2b18d580e2ecc8 = tareaMantenimientoPlanificadosForFk6b2b18d580e2ecc8;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empleadoMantenimientoPlanificadoByFk6b2b18d580e2ecc8")
	public Set<TareaMantenimientoPlanificado> getTareaMantenimientoPlanificadosForEmpleadoMantenimientoPlanificadoTareaMantenimientoPlani573() {
		return this.tareaMantenimientoPlanificadosForEmpleadoMantenimientoPlanificadoTareaMantenimientoPlani573;
	}

	public void setTareaMantenimientoPlanificadosForEmpleadoMantenimientoPlanificadoTareaMantenimientoPlani573(
			Set<TareaMantenimientoPlanificado> tareaMantenimientoPlanificadosForEmpleadoMantenimientoPlanificadoTareaMantenimientoPlani573) {
		this.tareaMantenimientoPlanificadosForEmpleadoMantenimientoPlanificadoTareaMantenimientoPlani573 = tareaMantenimientoPlanificadosForEmpleadoMantenimientoPlanificadoTareaMantenimientoPlani573;
	}

}
