package modelo;

// Generated 12/12/2011 09:17:13 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmpleadoCargo generated by hbm2java
 */
@Entity
@Table(name = "empleado_cargo")
public class EmpleadoCargo implements java.io.Serializable {

	private EmpleadoCargoId id;
	private Cargo cargo;
	private Empleado empleado;
	private char estado;
	private char estatus;
	private Date fechaFin;
	private Date fechaInicio;

	public EmpleadoCargo() {
	}

	public EmpleadoCargo(EmpleadoCargoId id, Cargo cargo, Empleado empleado,
			char estado, char estatus, Date fechaFin, Date fechaInicio) {
		this.id = id;
		this.cargo = cargo;
		this.empleado = empleado;
		this.estado = estado;
		this.estatus = estatus;
		this.fechaFin = fechaFin;
		this.fechaInicio = fechaInicio;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cedula", column = @Column(name = "cedula", nullable = false)),
			@AttributeOverride(name = "codigoCargo", column = @Column(name = "codigo_cargo", nullable = false)) })
	public EmpleadoCargoId getId() {
		return this.id;
	}

	public void setId(EmpleadoCargoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_cargo", nullable = false, insertable = false, updatable = false)
	public Cargo getCargo() {
		return this.cargo;
	}

	public void setCargo(Cargo cargo) {
		this.cargo = cargo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cedula", nullable = false, insertable = false, updatable = false)
	public Empleado getEmpleado() {
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	@Column(name = "estado", nullable = false, length = 1)
	public char getEstado() {
		return this.estado;
	}

	public void setEstado(char estado) {
		this.estado = estado;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_fin", nullable = false, length = 13)
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_inicio", nullable = false, length = 13)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

}
