package modelo;

// Generated 11/12/2011 04:17:03 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmpleadoTipoNomina generated by hbm2java
 */
@Entity
@Table(name = "empleado_tipo_nomina")
public class EmpleadoTipoNomina implements java.io.Serializable {

	private EmpleadoTipoNominaId id;
	private TipoNomina tipoNomina;
	private Empleado empleado;
	private char estado;
	private char estatus;
	private Date fechaFin;
	private Date fechaInicio;

	public EmpleadoTipoNomina() {
	}

	public EmpleadoTipoNomina(EmpleadoTipoNominaId id, TipoNomina tipoNomina,
			Empleado empleado, char estado, char estatus, Date fechaFin,
			Date fechaInicio) {
		this.id = id;
		this.tipoNomina = tipoNomina;
		this.empleado = empleado;
		this.estado = estado;
		this.estatus = estatus;
		this.fechaFin = fechaFin;
		this.fechaInicio = fechaInicio;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cedula", column = @Column(name = "cedula", nullable = false)),
			@AttributeOverride(name = "codigoTipoNomina", column = @Column(name = "codigo_tipo_nomina", nullable = false)) })
	public EmpleadoTipoNominaId getId() {
		return this.id;
	}

	public void setId(EmpleadoTipoNominaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_tipo_nomina", nullable = false, insertable = false, updatable = false)
	public TipoNomina getTipoNomina() {
		return this.tipoNomina;
	}

	public void setTipoNomina(TipoNomina tipoNomina) {
		this.tipoNomina = tipoNomina;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cedula", nullable = false, insertable = false, updatable = false)
	public Empleado getEmpleado() {
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	@Column(name = "estado", nullable = false, length = 1)
	public char getEstado() {
		return this.estado;
	}

	public void setEstado(char estado) {
		this.estado = estado;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_fin", nullable = false, length = 13)
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_inicio", nullable = false, length = 13)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

}
