package modelo;

// Generated 14/12/2011 05:11:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EstadoMantenimiento generated by hbm2java
 */
@Entity
@Table(name = "estado_mantenimiento")
public class EstadoMantenimiento implements java.io.Serializable {

	private String codigoEstadoMantenimiento;
	private Estado estado;
	private Mantenimiento mantenimiento;
	private char estatus;
	private Set<ResultadoMantenimiento> resultadoMantenimientos = new HashSet<ResultadoMantenimiento>(
			0);
	private Set<ResultadoMantenimiento> resultadoMantenimientos_1 = new HashSet<ResultadoMantenimiento>(
			0);

	public EstadoMantenimiento() {
	}

	public EstadoMantenimiento(String codigoEstadoMantenimiento, Estado estado,
			Mantenimiento mantenimiento, char estatus) {
		this.codigoEstadoMantenimiento = codigoEstadoMantenimiento;
		this.estado = estado;
		this.mantenimiento = mantenimiento;
		this.estatus = estatus;
	}

	public EstadoMantenimiento(String codigoEstadoMantenimiento, Estado estado,
			Mantenimiento mantenimiento, char estatus,
			Set<ResultadoMantenimiento> resultadoMantenimientos,
			Set<ResultadoMantenimiento> resultadoMantenimientos_1) {
		this.codigoEstadoMantenimiento = codigoEstadoMantenimiento;
		this.estado = estado;
		this.mantenimiento = mantenimiento;
		this.estatus = estatus;
		this.resultadoMantenimientos = resultadoMantenimientos;
		this.resultadoMantenimientos_1 = resultadoMantenimientos_1;
	}

	@Id
	@Column(name = "codigo_estado_mantenimiento", unique = true, nullable = false)
	public String getCodigoEstadoMantenimiento() {
		return this.codigoEstadoMantenimiento;
	}

	public void setCodigoEstadoMantenimiento(String codigoEstadoMantenimiento) {
		this.codigoEstadoMantenimiento = codigoEstadoMantenimiento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_estado", nullable = false)
	public Estado getEstado() {
		return this.estado;
	}

	public void setEstado(Estado estado) {
		this.estado = estado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_mantenimiento", nullable = false)
	public Mantenimiento getMantenimiento() {
		return this.mantenimiento;
	}

	public void setMantenimiento(Mantenimiento mantenimiento) {
		this.mantenimiento = mantenimiento;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estadoMantenimiento")
	public Set<ResultadoMantenimiento> getResultadoMantenimientos() {
		return this.resultadoMantenimientos;
	}

	public void setResultadoMantenimientos(
			Set<ResultadoMantenimiento> resultadoMantenimientos) {
		this.resultadoMantenimientos = resultadoMantenimientos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estadoMantenimiento")
	public Set<ResultadoMantenimiento> getResultadoMantenimientos_1() {
		return this.resultadoMantenimientos_1;
	}

	public void setResultadoMantenimientos_1(
			Set<ResultadoMantenimiento> resultadoMantenimientos_1) {
		this.resultadoMantenimientos_1 = resultadoMantenimientos_1;
	}

}
