package modelo;

// Generated 14/02/2012 08:24:27 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EstadoActividad generated by hbm2java
 */
@Entity
@Table(name = "estado_actividad", schema = "public")
public class EstadoActividad implements java.io.Serializable {

	private int codigoEstadoActividad;
	private DatoBasico datoBasico;
	private Actividad actividad;
	private char estatus;

	public EstadoActividad() {
	}

	public EstadoActividad(int codigoEstadoActividad, DatoBasico datoBasico,
			Actividad actividad, char estatus) {
		this.codigoEstadoActividad = codigoEstadoActividad;
		this.datoBasico = datoBasico;
		this.actividad = actividad;
		this.estatus = estatus;
	}

	@Id
	@Column(name = "codigo_estado_actividad", unique = true, nullable = false)
	public int getCodigoEstadoActividad() {
		return this.codigoEstadoActividad;
	}

	public void setCodigoEstadoActividad(int codigoEstadoActividad) {
		this.codigoEstadoActividad = codigoEstadoActividad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_estado", nullable = false)
	public DatoBasico getDatoBasico() {
		return this.datoBasico;
	}

	public void setDatoBasico(DatoBasico datoBasico) {
		this.datoBasico = datoBasico;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_actividad", nullable = false)
	public Actividad getActividad() {
		return this.actividad;
	}

	public void setActividad(Actividad actividad) {
		this.actividad = actividad;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

}
