package modelo;

<<<<<<< HEAD
=======
<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> 9d67536bdd2e3b33aa6400eb3bb09741a4535bb0
>>>>>>> 873ccb018e72b00b831aa9284cc0745bd1c2d514
// Generated 25/01/2012 12:32:42 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
<<<<<<< HEAD
=======
<<<<<<< HEAD
=======
=======
// Generated 24/01/2012 04:28:30 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
>>>>>>> 7d4823278d0a354855f5032a99e2b48c65b33e7f
>>>>>>> 9d67536bdd2e3b33aa6400eb3bb09741a4535bb0
>>>>>>> 873ccb018e72b00b831aa9284cc0745bd1c2d514
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EstadoActividad generated by hbm2java
 */
@Entity
@Table(name = "estado_actividad", schema = "public")
public class EstadoActividad implements java.io.Serializable {

<<<<<<< HEAD
	private int codigoEstadoActividad;
=======
<<<<<<< HEAD
	private int codigoEstadoActividad;
=======
<<<<<<< HEAD
	private int codigoEstadoActividad;
=======
	private EstadoActividadId id;
>>>>>>> 7d4823278d0a354855f5032a99e2b48c65b33e7f
>>>>>>> 9d67536bdd2e3b33aa6400eb3bb09741a4535bb0
>>>>>>> 873ccb018e72b00b831aa9284cc0745bd1c2d514
	private DatoBasico datoBasico;
	private Actividad actividad;
	private char estatus;

	public EstadoActividad() {
	}

<<<<<<< HEAD
	public EstadoActividad(int codigoEstadoActividad, DatoBasico datoBasico,
			Actividad actividad, char estatus) {
		this.codigoEstadoActividad = codigoEstadoActividad;
=======
<<<<<<< HEAD
	public EstadoActividad(int codigoEstadoActividad, DatoBasico datoBasico,
			Actividad actividad, char estatus) {
		this.codigoEstadoActividad = codigoEstadoActividad;
=======
<<<<<<< HEAD
	public EstadoActividad(int codigoEstadoActividad, DatoBasico datoBasico,
			Actividad actividad, char estatus) {
		this.codigoEstadoActividad = codigoEstadoActividad;
=======
	public EstadoActividad(EstadoActividadId id, DatoBasico datoBasico,
			Actividad actividad, char estatus) {
		this.id = id;
>>>>>>> 7d4823278d0a354855f5032a99e2b48c65b33e7f
>>>>>>> 9d67536bdd2e3b33aa6400eb3bb09741a4535bb0
>>>>>>> 873ccb018e72b00b831aa9284cc0745bd1c2d514
		this.datoBasico = datoBasico;
		this.actividad = actividad;
		this.estatus = estatus;
	}

<<<<<<< HEAD
=======
<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> 9d67536bdd2e3b33aa6400eb3bb09741a4535bb0
>>>>>>> 873ccb018e72b00b831aa9284cc0745bd1c2d514
	@Id
	@Column(name = "codigo_estado_actividad", unique = true, nullable = false)
	public int getCodigoEstadoActividad() {
		return this.codigoEstadoActividad;
	}

	public void setCodigoEstadoActividad(int codigoEstadoActividad) {
		this.codigoEstadoActividad = codigoEstadoActividad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_estado", nullable = false)
<<<<<<< HEAD
=======
<<<<<<< HEAD
=======
=======
	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codigoEstado", column = @Column(name = "codigo_estado", nullable = false)),
			@AttributeOverride(name = "codigoActividad", column = @Column(name = "codigo_actividad", nullable = false)) })
	public EstadoActividadId getId() {
		return this.id;
	}

	public void setId(EstadoActividadId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_estado", nullable = false, insertable = false, updatable = false)
>>>>>>> 7d4823278d0a354855f5032a99e2b48c65b33e7f
>>>>>>> 9d67536bdd2e3b33aa6400eb3bb09741a4535bb0
>>>>>>> 873ccb018e72b00b831aa9284cc0745bd1c2d514
	public DatoBasico getDatoBasico() {
		return this.datoBasico;
	}

	public void setDatoBasico(DatoBasico datoBasico) {
		this.datoBasico = datoBasico;
	}

	@ManyToOne(fetch = FetchType.LAZY)
<<<<<<< HEAD
	@JoinColumn(name = "codigo_actividad", nullable = false)
=======
<<<<<<< HEAD
	@JoinColumn(name = "codigo_actividad", nullable = false)
=======
<<<<<<< HEAD
	@JoinColumn(name = "codigo_actividad", nullable = false)
=======
	@JoinColumn(name = "codigo_actividad", nullable = false, insertable = false, updatable = false)
>>>>>>> 7d4823278d0a354855f5032a99e2b48c65b33e7f
>>>>>>> 9d67536bdd2e3b33aa6400eb3bb09741a4535bb0
>>>>>>> 873ccb018e72b00b831aa9284cc0745bd1c2d514
	public Actividad getActividad() {
		return this.actividad;
	}

	public void setActividad(Actividad actividad) {
		this.actividad = actividad;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

}
