package modelo;

// Generated 10/12/2011 11:05:49 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FamiliarJugadorId generated by hbm2java
 */
@Embeddable
public class FamiliarJugadorId implements java.io.Serializable {

	private String cedulaFamiliar;
	private String cedulaJugador;

	public FamiliarJugadorId() {
	}

	public FamiliarJugadorId(String cedulaFamiliar, String cedulaJugador) {
		this.cedulaFamiliar = cedulaFamiliar;
		this.cedulaJugador = cedulaJugador;
	}

	@Column(name = "cedula_familiar", nullable = false)
	public String getCedulaFamiliar() {
		return this.cedulaFamiliar;
	}

	public void setCedulaFamiliar(String cedulaFamiliar) {
		this.cedulaFamiliar = cedulaFamiliar;
	}

	@Column(name = "cedula_jugador", nullable = false)
	public String getCedulaJugador() {
		return this.cedulaJugador;
	}

	public void setCedulaJugador(String cedulaJugador) {
		this.cedulaJugador = cedulaJugador;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FamiliarJugadorId))
			return false;
		FamiliarJugadorId castOther = (FamiliarJugadorId) other;

		return ((this.getCedulaFamiliar() == castOther.getCedulaFamiliar()) || (this
				.getCedulaFamiliar() != null
				&& castOther.getCedulaFamiliar() != null && this
				.getCedulaFamiliar().equals(castOther.getCedulaFamiliar())))
				&& ((this.getCedulaJugador() == castOther.getCedulaJugador()) || (this
						.getCedulaJugador() != null
						&& castOther.getCedulaJugador() != null && this
						.getCedulaJugador()
						.equals(castOther.getCedulaJugador())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCedulaFamiliar() == null ? 0 : this.getCedulaFamiliar()
						.hashCode());
		result = 37
				* result
				+ (getCedulaJugador() == null ? 0 : this.getCedulaJugador()
						.hashCode());
		return result;
	}

}
