package modelo;
<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> 9d67536bdd2e3b33aa6400eb3bb09741a4535bb0

// Generated 25/01/2012 12:32:42 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
<<<<<<< HEAD
=======
=======
// Generated 24/01/2012 04:28:30 AM by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
>>>>>>> 7d4823278d0a354855f5032a99e2b48c65b33e7f
>>>>>>> 9d67536bdd2e3b33aa6400eb3bb09741a4535bb0

/**
 * FamiliarComisionEquipo generated by hbm2java
 */
@Entity
<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> 9d67536bdd2e3b33aa6400eb3bb09741a4535bb0
@Table(name = "familiar_comision_equipo", schema = "public")
public class FamiliarComisionEquipo implements java.io.Serializable {

	private int codigoFamiliarComision;
	private FamiliarJugador familiarJugador;
	private ComisionEquipo comisionEquipo;
	private char estatus;
	private Set<TareaActividadPlanificada> tareaActividadPlanificadas = new HashSet<TareaActividadPlanificada>(
			0);

	public FamiliarComisionEquipo() {
	}

	public FamiliarComisionEquipo(int codigoFamiliarComision,
			FamiliarJugador familiarJugador, ComisionEquipo comisionEquipo,
			char estatus) {
		this.codigoFamiliarComision = codigoFamiliarComision;
		this.familiarJugador = familiarJugador;
		this.comisionEquipo = comisionEquipo;
		this.estatus = estatus;
	}

	public FamiliarComisionEquipo(int codigoFamiliarComision,
			FamiliarJugador familiarJugador, ComisionEquipo comisionEquipo,
			char estatus,
			Set<TareaActividadPlanificada> tareaActividadPlanificadas) {
		this.codigoFamiliarComision = codigoFamiliarComision;
		this.familiarJugador = familiarJugador;
		this.comisionEquipo = comisionEquipo;
		this.estatus = estatus;
		this.tareaActividadPlanificadas = tareaActividadPlanificadas;
	}

	@Id
	@Column(name = "codigo_familiar_comision", unique = true, nullable = false)
	public int getCodigoFamiliarComision() {
		return this.codigoFamiliarComision;
	}

	public void setCodigoFamiliarComision(int codigoFamiliarComision) {
		this.codigoFamiliarComision = codigoFamiliarComision;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_familiar_jugador", nullable = false)
	public FamiliarJugador getFamiliarJugador() {
		return this.familiarJugador;
	}

	public void setFamiliarJugador(FamiliarJugador familiarJugador) {
		this.familiarJugador = familiarJugador;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_comision_equipo", nullable = false)
	public ComisionEquipo getComisionEquipo() {
		return this.comisionEquipo;
	}

	public void setComisionEquipo(ComisionEquipo comisionEquipo) {
		this.comisionEquipo = comisionEquipo;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "familiarComisionEquipo")
	public Set<TareaActividadPlanificada> getTareaActividadPlanificadas() {
		return this.tareaActividadPlanificadas;
	}

	public void setTareaActividadPlanificadas(
			Set<TareaActividadPlanificada> tareaActividadPlanificadas) {
		this.tareaActividadPlanificadas = tareaActividadPlanificadas;
	}

}
<<<<<<< HEAD
=======
=======
@Table(name="familiar_comision_equipo"
    ,schema="public"
)
public class FamiliarComisionEquipo  implements java.io.Serializable {


     private FamiliarComisionEquipoId id;
     private FamiliarJugador familiarJugador;
     private ComisionEquipo comisionEquipo;
     private char estatus;
     private Set<TareaActividadPlanificada> tareaActividadPlanificadas = new HashSet<TareaActividadPlanificada>(0);

    public FamiliarComisionEquipo() {
    }

	
    public FamiliarComisionEquipo(FamiliarComisionEquipoId id, FamiliarJugador familiarJugador, ComisionEquipo comisionEquipo, char estatus) {
        this.id = id;
        this.familiarJugador = familiarJugador;
        this.comisionEquipo = comisionEquipo;
        this.estatus = estatus;
    }
    public FamiliarComisionEquipo(FamiliarComisionEquipoId id, FamiliarJugador familiarJugador, ComisionEquipo comisionEquipo, char estatus, Set<TareaActividadPlanificada> tareaActividadPlanificadas) {
       this.id = id;
       this.familiarJugador = familiarJugador;
       this.comisionEquipo = comisionEquipo;
       this.estatus = estatus;
       this.tareaActividadPlanificadas = tareaActividadPlanificadas;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="codigoComisionEquipo", column=@Column(name="codigo_comision_equipo", nullable=false) ), 
        @AttributeOverride(name="codigoFamiliarJugador", column=@Column(name="codigo_familiar_jugador", nullable=false) ) } )
    public FamiliarComisionEquipoId getId() {
        return this.id;
    }
    
    public void setId(FamiliarComisionEquipoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codigo_familiar_jugador", nullable=false, insertable=false, updatable=false)
    public FamiliarJugador getFamiliarJugador() {
        return this.familiarJugador;
    }
    
    public void setFamiliarJugador(FamiliarJugador familiarJugador) {
        this.familiarJugador = familiarJugador;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="codigo_comision_equipo", nullable=false, insertable=false, updatable=false)
    public ComisionEquipo getComisionEquipo() {
        return this.comisionEquipo;
    }
    
    public void setComisionEquipo(ComisionEquipo comisionEquipo) {
        this.comisionEquipo = comisionEquipo;
    }

    
    @Column(name="estatus", nullable=false, length=1)
    public char getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(char estatus) {
        this.estatus = estatus;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="familiarComisionEquipo")
    public Set<TareaActividadPlanificada> getTareaActividadPlanificadas() {
        return this.tareaActividadPlanificadas;
    }
    
    public void setTareaActividadPlanificadas(Set<TareaActividadPlanificada> tareaActividadPlanificadas) {
        this.tareaActividadPlanificadas = tareaActividadPlanificadas;
    }




}


>>>>>>> 7d4823278d0a354855f5032a99e2b48c65b33e7f
>>>>>>> 9d67536bdd2e3b33aa6400eb3bb09741a4535bb0
