package modelo;

// Generated 16/12/2011 10:21:41 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * IndicadorCompetencia generated by hbm2java
 */
@Entity
@Table(name = "indicador_competencia")
public class IndicadorCompetencia implements java.io.Serializable {

	private String codigoIndicadorCompetencia;
	private Competencia competencia;
	private Indicador indicador;
	private Set<DesempennoIndividual> desempennoIndividuals = new HashSet<DesempennoIndividual>(
			0);
	private Set<DesempennoColectivo> desempennoColectivos = new HashSet<DesempennoColectivo>(
			0);

	public IndicadorCompetencia() {
	}

	public IndicadorCompetencia(String codigoIndicadorCompetencia,
			Competencia competencia, Indicador indicador) {
		this.codigoIndicadorCompetencia = codigoIndicadorCompetencia;
		this.competencia = competencia;
		this.indicador = indicador;
	}

	public IndicadorCompetencia(String codigoIndicadorCompetencia,
			Competencia competencia, Indicador indicador,
			Set<DesempennoIndividual> desempennoIndividuals,
			Set<DesempennoColectivo> desempennoColectivos) {
		this.codigoIndicadorCompetencia = codigoIndicadorCompetencia;
		this.competencia = competencia;
		this.indicador = indicador;
		this.desempennoIndividuals = desempennoIndividuals;
		this.desempennoColectivos = desempennoColectivos;
	}

	@Id
	@Column(name = "codigo_indicador_competencia", unique = true, nullable = false)
	public String getCodigoIndicadorCompetencia() {
		return this.codigoIndicadorCompetencia;
	}

	public void setCodigoIndicadorCompetencia(String codigoIndicadorCompetencia) {
		this.codigoIndicadorCompetencia = codigoIndicadorCompetencia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_competencia", nullable = false)
	public Competencia getCompetencia() {
		return this.competencia;
	}

	public void setCompetencia(Competencia competencia) {
		this.competencia = competencia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_indicador", nullable = false)
	public Indicador getIndicador() {
		return this.indicador;
	}

	public void setIndicador(Indicador indicador) {
		this.indicador = indicador;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "indicadorCompetencia")
	public Set<DesempennoIndividual> getDesempennoIndividuals() {
		return this.desempennoIndividuals;
	}

	public void setDesempennoIndividuals(
			Set<DesempennoIndividual> desempennoIndividuals) {
		this.desempennoIndividuals = desempennoIndividuals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "indicadorCompetencia")
	public Set<DesempennoColectivo> getDesempennoColectivos() {
		return this.desempennoColectivos;
	}

	public void setDesempennoColectivos(
			Set<DesempennoColectivo> desempennoColectivos) {
		this.desempennoColectivos = desempennoColectivos;
	}

}
