package modelo;

// Generated 10/02/2012 01:24:38 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ingreso generated by hbm2java
 */
@Entity
@Table(name = "ingreso", schema = "public")
public class Ingreso implements java.io.Serializable {

	private int codigoIngreso;
	private DatoBasico datoBasico;
	private String numeroDocumento;
	private Date fechaPago;
	private char estatus;
	private Set<IngresoFormaPago> ingresoFormaPagos = new HashSet<IngresoFormaPago>(
			0);
	private Set<IngresoDocumentoAcreedor> ingresoDocumentoAcreedors = new HashSet<IngresoDocumentoAcreedor>(
			0);

	public Ingreso() {
	}

	public Ingreso(int codigoIngreso, Date fechaPago, char estatus) {
		this.codigoIngreso = codigoIngreso;
		this.fechaPago = fechaPago;
		this.estatus = estatus;
	}

	public Ingreso(int codigoIngreso, DatoBasico datoBasico,
			String numeroDocumento, Date fechaPago, char estatus,
			Set<IngresoFormaPago> ingresoFormaPagos,
			Set<IngresoDocumentoAcreedor> ingresoDocumentoAcreedors) {
		this.codigoIngreso = codigoIngreso;
		this.datoBasico = datoBasico;
		this.numeroDocumento = numeroDocumento;
		this.fechaPago = fechaPago;
		this.estatus = estatus;
		this.ingresoFormaPagos = ingresoFormaPagos;
		this.ingresoDocumentoAcreedors = ingresoDocumentoAcreedors;
	}

	@Id
	@Column(name = "codigo_ingreso", unique = true, nullable = false)
	public int getCodigoIngreso() {
		return this.codigoIngreso;
	}

	public void setCodigoIngreso(int codigoIngreso) {
		this.codigoIngreso = codigoIngreso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_tipo_documento")
	public DatoBasico getDatoBasico() {
		return this.datoBasico;
	}

	public void setDatoBasico(DatoBasico datoBasico) {
		this.datoBasico = datoBasico;
	}

	@Column(name = "numero_documento")
	public String getNumeroDocumento() {
		return this.numeroDocumento;
	}

	public void setNumeroDocumento(String numeroDocumento) {
		this.numeroDocumento = numeroDocumento;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_pago", nullable = false, length = 13)
	public Date getFechaPago() {
		return this.fechaPago;
	}

	public void setFechaPago(Date fechaPago) {
		this.fechaPago = fechaPago;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ingreso")
	public Set<IngresoFormaPago> getIngresoFormaPagos() {
		return this.ingresoFormaPagos;
	}

	public void setIngresoFormaPagos(Set<IngresoFormaPago> ingresoFormaPagos) {
		this.ingresoFormaPagos = ingresoFormaPagos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ingreso")
	public Set<IngresoDocumentoAcreedor> getIngresoDocumentoAcreedors() {
		return this.ingresoDocumentoAcreedors;
	}

	public void setIngresoDocumentoAcreedors(
			Set<IngresoDocumentoAcreedor> ingresoDocumentoAcreedors) {
		this.ingresoDocumentoAcreedors = ingresoDocumentoAcreedors;
	}

}
