package modelo;

// Generated 28/12/2011 03:24:38 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Juego generated by hbm2java
 */
@Entity
@Table(name = "juego", schema = "public")
public class Juego implements java.io.Serializable {

	private int codigoJuego;
	private Estadio estadio;
	private Competencia competencia;
	private DatoBasico datoBasico;
	private Date horaInicio;
	private Date fecha;
	private String observaciones;
	private int cantidadInning;
	private Date duracion;
	private Set<PersonalJuego> personalJuegos = new HashSet<PersonalJuego>(0);
	private Set<ActividadCalendario> actividadCalendarios = new HashSet<ActividadCalendario>(
			0);
	private Set<PersonalEquipo> personalEquipos = new HashSet<PersonalEquipo>(0);
	private Set<EquipoJuego> equipoJuegos = new HashSet<EquipoJuego>(0);
	private Set<LineUp> lineUps = new HashSet<LineUp>(0);
	private Set<PersonalForaneoJuego> personalForaneoJuegos = new HashSet<PersonalForaneoJuego>(
			0);
	private Set<JugadorForaneo> jugadorForaneos = new HashSet<JugadorForaneo>(0);

	public Juego() {
	}

	public Juego(int codigoJuego, Estadio estadio, Competencia competencia,
			DatoBasico datoBasico, Date horaInicio, Date fecha,
			String observaciones, int cantidadInning, Date duracion) {
		this.codigoJuego = codigoJuego;
		this.estadio = estadio;
		this.competencia = competencia;
		this.datoBasico = datoBasico;
		this.horaInicio = horaInicio;
		this.fecha = fecha;
		this.observaciones = observaciones;
		this.cantidadInning = cantidadInning;
		this.duracion = duracion;
	}

	public Juego(int codigoJuego, Estadio estadio, Competencia competencia,
			DatoBasico datoBasico, Date horaInicio, Date fecha,
			String observaciones, int cantidadInning, Date duracion,
			Set<PersonalJuego> personalJuegos,
			Set<ActividadCalendario> actividadCalendarios,
			Set<PersonalEquipo> personalEquipos, Set<EquipoJuego> equipoJuegos,
			Set<LineUp> lineUps,
			Set<PersonalForaneoJuego> personalForaneoJuegos,
			Set<JugadorForaneo> jugadorForaneos) {
		this.codigoJuego = codigoJuego;
		this.estadio = estadio;
		this.competencia = competencia;
		this.datoBasico = datoBasico;
		this.horaInicio = horaInicio;
		this.fecha = fecha;
		this.observaciones = observaciones;
		this.cantidadInning = cantidadInning;
		this.duracion = duracion;
		this.personalJuegos = personalJuegos;
		this.actividadCalendarios = actividadCalendarios;
		this.personalEquipos = personalEquipos;
		this.equipoJuegos = equipoJuegos;
		this.lineUps = lineUps;
		this.personalForaneoJuegos = personalForaneoJuegos;
		this.jugadorForaneos = jugadorForaneos;
	}

	@Id
	@Column(name = "codigo_juego", unique = true, nullable = false)
	public int getCodigoJuego() {
		return this.codigoJuego;
	}

	public void setCodigoJuego(int codigoJuego) {
		this.codigoJuego = codigoJuego;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_estadio", nullable = false)
	public Estadio getEstadio() {
		return this.estadio;
	}

	public void setEstadio(Estadio estadio) {
		this.estadio = estadio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_competencia", nullable = false)
	public Competencia getCompetencia() {
		return this.competencia;
	}

	public void setCompetencia(Competencia competencia) {
		this.competencia = competencia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_estado", nullable = false)
	public DatoBasico getDatoBasico() {
		return this.datoBasico;
	}

	public void setDatoBasico(DatoBasico datoBasico) {
		this.datoBasico = datoBasico;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_inicio", nullable = false, length = 15)
	public Date getHoraInicio() {
		return this.horaInicio;
	}

	public void setHoraInicio(Date horaInicio) {
		this.horaInicio = horaInicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", nullable = false, length = 13)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "observaciones", nullable = false)
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	@Column(name = "cantidad_inning", nullable = false)
	public int getCantidadInning() {
		return this.cantidadInning;
	}

	public void setCantidadInning(int cantidadInning) {
		this.cantidadInning = cantidadInning;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "duracion", nullable = false, length = 15)
	public Date getDuracion() {
		return this.duracion;
	}

	public void setDuracion(Date duracion) {
		this.duracion = duracion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "juego")
	public Set<PersonalJuego> getPersonalJuegos() {
		return this.personalJuegos;
	}

	public void setPersonalJuegos(Set<PersonalJuego> personalJuegos) {
		this.personalJuegos = personalJuegos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "juego")
	public Set<ActividadCalendario> getActividadCalendarios() {
		return this.actividadCalendarios;
	}

	public void setActividadCalendarios(
			Set<ActividadCalendario> actividadCalendarios) {
		this.actividadCalendarios = actividadCalendarios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "juego")
	public Set<PersonalEquipo> getPersonalEquipos() {
		return this.personalEquipos;
	}

	public void setPersonalEquipos(Set<PersonalEquipo> personalEquipos) {
		this.personalEquipos = personalEquipos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "juego")
	public Set<EquipoJuego> getEquipoJuegos() {
		return this.equipoJuegos;
	}

	public void setEquipoJuegos(Set<EquipoJuego> equipoJuegos) {
		this.equipoJuegos = equipoJuegos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "juego")
	public Set<LineUp> getLineUps() {
		return this.lineUps;
	}

	public void setLineUps(Set<LineUp> lineUps) {
		this.lineUps = lineUps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "juego")
	public Set<PersonalForaneoJuego> getPersonalForaneoJuegos() {
		return this.personalForaneoJuegos;
	}

	public void setPersonalForaneoJuegos(
			Set<PersonalForaneoJuego> personalForaneoJuegos) {
		this.personalForaneoJuegos = personalForaneoJuegos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "juego")
	public Set<JugadorForaneo> getJugadorForaneos() {
		return this.jugadorForaneos;
	}

	public void setJugadorForaneos(Set<JugadorForaneo> jugadorForaneos) {
		this.jugadorForaneos = jugadorForaneos;
	}

}
