package modelo;

// Generated 16/12/2011 03:51:27 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * JugadorClave generated by hbm2java
 */
@Entity
@Table(name = "jugador_clave")
public class JugadorClave implements java.io.Serializable {

	private JugadorClaveId id;
	private RosterCompetencia rosterCompetencia;
	private DatoBasico datoBasico;
	private float valor;

	public JugadorClave() {
	}

	public JugadorClave(JugadorClaveId id, RosterCompetencia rosterCompetencia,
			DatoBasico datoBasico, float valor) {
		this.id = id;
		this.rosterCompetencia = rosterCompetencia;
		this.datoBasico = datoBasico;
		this.valor = valor;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codigoRosterCompetencia", column = @Column(name = "codigo_roster_competencia", nullable = false)),
			@AttributeOverride(name = "codigoTipoMencion", column = @Column(name = "codigo_tipo_mencion", nullable = false)) })
	public JugadorClaveId getId() {
		return this.id;
	}

	public void setId(JugadorClaveId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_roster_competencia", nullable = false, insertable = false, updatable = false)
	public RosterCompetencia getRosterCompetencia() {
		return this.rosterCompetencia;
	}

	public void setRosterCompetencia(RosterCompetencia rosterCompetencia) {
		this.rosterCompetencia = rosterCompetencia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_tipo_mencion", nullable = false, insertable = false, updatable = false)
	public DatoBasico getDatoBasico() {
		return this.datoBasico;
	}

	public void setDatoBasico(DatoBasico datoBasico) {
		this.datoBasico = datoBasico;
	}

	@Column(name = "valor", nullable = false, precision = 8, scale = 8)
	public float getValor() {
		return this.valor;
	}

	public void setValor(float valor) {
		this.valor = valor;
	}

}
