package modelo;

<<<<<<< HEAD
// Generated 25/01/2012 12:32:42 AM by Hibernate Tools 3.4.0.CR1
=======
<<<<<<< HEAD
// Generated 25/01/2012 12:32:42 AM by Hibernate Tools 3.4.0.CR1
=======
// Generated 24/01/2012 04:28:30 AM by Hibernate Tools 3.4.0.CR1
>>>>>>> 7d4823278d0a354855f5032a99e2b48c65b33e7f
>>>>>>> 9d67536bdd2e3b33aa6400eb3bb09741a4535bb0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LapsoDeportivo generated by hbm2java
 */
@Entity
@Table(name = "lapso_deportivo", schema = "public")
public class LapsoDeportivo implements java.io.Serializable {

	private int codigoLapsoDeportivo;
	private DatoBasico datoBasico;
	private Date fechaInicio;
	private Date fechaFin;
	private String nombre;
	private char estatus;
<<<<<<< HEAD
	private Date fechaInicioAscenso;
	private Date fechaFinAscenso;
=======
<<<<<<< HEAD
	private Date fechaInicioAscenso;
	private Date fechaFinAscenso;
=======
	private Date fechaAscenso;
>>>>>>> 7d4823278d0a354855f5032a99e2b48c65b33e7f
>>>>>>> 9d67536bdd2e3b33aa6400eb3bb09741a4535bb0
	private Set<Competencia> competencias = new HashSet<Competencia>(0);
	private Set<PlanTemporada> planTemporadas = new HashSet<PlanTemporada>(0);

	public LapsoDeportivo() {
	}

	public LapsoDeportivo(int codigoLapsoDeportivo, DatoBasico datoBasico,
			Date fechaInicio, Date fechaFin, String nombre, char estatus) {
		this.codigoLapsoDeportivo = codigoLapsoDeportivo;
		this.datoBasico = datoBasico;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.nombre = nombre;
		this.estatus = estatus;
	}

	public LapsoDeportivo(int codigoLapsoDeportivo, DatoBasico datoBasico,
			Date fechaInicio, Date fechaFin, String nombre, char estatus,
<<<<<<< HEAD
			Date fechaInicioAscenso, Date fechaFinAscenso,
			Set<Competencia> competencias, Set<PlanTemporada> planTemporadas) {
=======
<<<<<<< HEAD
			Date fechaInicioAscenso, Date fechaFinAscenso,
			Set<Competencia> competencias, Set<PlanTemporada> planTemporadas) {
=======
			Date fechaAscenso, Set<Competencia> competencias,
			Set<PlanTemporada> planTemporadas) {
>>>>>>> 7d4823278d0a354855f5032a99e2b48c65b33e7f
>>>>>>> 9d67536bdd2e3b33aa6400eb3bb09741a4535bb0
		this.codigoLapsoDeportivo = codigoLapsoDeportivo;
		this.datoBasico = datoBasico;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.nombre = nombre;
		this.estatus = estatus;
<<<<<<< HEAD
		this.fechaInicioAscenso = fechaInicioAscenso;
		this.fechaFinAscenso = fechaFinAscenso;
=======
<<<<<<< HEAD
		this.fechaInicioAscenso = fechaInicioAscenso;
		this.fechaFinAscenso = fechaFinAscenso;
=======
		this.fechaAscenso = fechaAscenso;
>>>>>>> 7d4823278d0a354855f5032a99e2b48c65b33e7f
>>>>>>> 9d67536bdd2e3b33aa6400eb3bb09741a4535bb0
		this.competencias = competencias;
		this.planTemporadas = planTemporadas;
	}

	@Id
	@Column(name = "codigo_lapso_deportivo", unique = true, nullable = false)
	public int getCodigoLapsoDeportivo() {
		return this.codigoLapsoDeportivo;
	}

	public void setCodigoLapsoDeportivo(int codigoLapsoDeportivo) {
		this.codigoLapsoDeportivo = codigoLapsoDeportivo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tipo_lapso", nullable = false)
	public DatoBasico getDatoBasico() {
		return this.datoBasico;
	}

	public void setDatoBasico(DatoBasico datoBasico) {
		this.datoBasico = datoBasico;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_inicio", nullable = false, length = 13)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_fin", nullable = false, length = 13)
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@Temporal(TemporalType.DATE)
<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> 9d67536bdd2e3b33aa6400eb3bb09741a4535bb0
	@Column(name = "fecha_inicio_ascenso", length = 13)
	public Date getFechaInicioAscenso() {
		return this.fechaInicioAscenso;
	}

	public void setFechaInicioAscenso(Date fechaInicioAscenso) {
		this.fechaInicioAscenso = fechaInicioAscenso;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_fin_ascenso", length = 13)
	public Date getFechaFinAscenso() {
		return this.fechaFinAscenso;
	}

	public void setFechaFinAscenso(Date fechaFinAscenso) {
		this.fechaFinAscenso = fechaFinAscenso;
<<<<<<< HEAD
=======
=======
	@Column(name = "fecha_ascenso", length = 13)
	public Date getFechaAscenso() {
		return this.fechaAscenso;
	}

	public void setFechaAscenso(Date fechaAscenso) {
		this.fechaAscenso = fechaAscenso;
>>>>>>> 7d4823278d0a354855f5032a99e2b48c65b33e7f
>>>>>>> 9d67536bdd2e3b33aa6400eb3bb09741a4535bb0
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lapsoDeportivo")
	public Set<Competencia> getCompetencias() {
		return this.competencias;
	}

	public void setCompetencias(Set<Competencia> competencias) {
		this.competencias = competencias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lapsoDeportivo")
	public Set<PlanTemporada> getPlanTemporadas() {
		return this.planTemporadas;
	}

	public void setPlanTemporadas(Set<PlanTemporada> planTemporadas) {
		this.planTemporadas = planTemporadas;
	}

}
