package modelo;

// Generated 12/12/2011 09:17:13 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MaterialMantenimientoPlanificado generated by hbm2java
 */
@Entity
@Table(name = "material_mantenimiento_planificado")
public class MaterialMantenimientoPlanificado implements java.io.Serializable {

	private MaterialMantenimientoPlanificadoId id;
	private Material material;
	private PlanificacionMantenimiento planificacionMantenimiento;
	private int cantidadRequerida;
	private char estatus;

	public MaterialMantenimientoPlanificado() {
	}

	public MaterialMantenimientoPlanificado(
			MaterialMantenimientoPlanificadoId id, Material material,
			PlanificacionMantenimiento planificacionMantenimiento,
			int cantidadRequerida, char estatus) {
		this.id = id;
		this.material = material;
		this.planificacionMantenimiento = planificacionMantenimiento;
		this.cantidadRequerida = cantidadRequerida;
		this.estatus = estatus;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codigoMaterial", column = @Column(name = "codigo_material", nullable = false)),
			@AttributeOverride(name = "codigoPlanificacionMantenimiento", column = @Column(name = "codigo_planificacion_mantenimiento", nullable = false)) })
	public MaterialMantenimientoPlanificadoId getId() {
		return this.id;
	}

	public void setId(MaterialMantenimientoPlanificadoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_material", nullable = false, insertable = false, updatable = false)
	public Material getMaterial() {
		return this.material;
	}

	public void setMaterial(Material material) {
		this.material = material;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_planificacion_mantenimiento", nullable = false, insertable = false, updatable = false)
	public PlanificacionMantenimiento getPlanificacionMantenimiento() {
		return this.planificacionMantenimiento;
	}

	public void setPlanificacionMantenimiento(
			PlanificacionMantenimiento planificacionMantenimiento) {
		this.planificacionMantenimiento = planificacionMantenimiento;
	}

	@Column(name = "cantidad_requerida", nullable = false)
	public int getCantidadRequerida() {
		return this.cantidadRequerida;
	}

	public void setCantidadRequerida(int cantidadRequerida) {
		this.cantidadRequerida = cantidadRequerida;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

}
