package modelo;

// Generated 28/12/2011 03:24:38 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MaterialActividadPlanificada generated by hbm2java
 */
@Entity
@Table(name = "material_actividad_planificada", schema = "public")
public class MaterialActividadPlanificada implements java.io.Serializable {

	private MaterialActividadPlanificadaId id;
	private PlanificacionActividad planificacionActividad;
	private Material material;
	private char estatus;
	private int cantidadRequerida;

	public MaterialActividadPlanificada() {
	}

	public MaterialActividadPlanificada(MaterialActividadPlanificadaId id,
			PlanificacionActividad planificacionActividad, Material material,
			char estatus, int cantidadRequerida) {
		this.id = id;
		this.planificacionActividad = planificacionActividad;
		this.material = material;
		this.estatus = estatus;
		this.cantidadRequerida = cantidadRequerida;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codigoPlanificacionActividad", column = @Column(name = "codigo_planificacion_actividad", nullable = false)),
			@AttributeOverride(name = "codigoMaterial", column = @Column(name = "codigo_material", nullable = false)) })
	public MaterialActividadPlanificadaId getId() {
		return this.id;
	}

	public void setId(MaterialActividadPlanificadaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_planificacion_actividad", nullable = false, insertable = false, updatable = false)
	public PlanificacionActividad getPlanificacionActividad() {
		return this.planificacionActividad;
	}

	public void setPlanificacionActividad(
			PlanificacionActividad planificacionActividad) {
		this.planificacionActividad = planificacionActividad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_material", nullable = false, insertable = false, updatable = false)
	public Material getMaterial() {
		return this.material;
	}

	public void setMaterial(Material material) {
		this.material = material;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@Column(name = "cantidad_requerida", nullable = false)
	public int getCantidadRequerida() {
		return this.cantidadRequerida;
	}

	public void setCantidadRequerida(int cantidadRequerida) {
		this.cantidadRequerida = cantidadRequerida;
	}

}
