package modelo;

// Generated 10/12/2011 11:05:49 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Medico generated by hbm2java
 */
@Entity
@Table(name = "medico")
public class Medico implements java.io.Serializable {

	private String matricula;
	private String apellido;
	private String cedulaMedico;
	private char estatus;
	private Date fechaIngreso;
	private String nombre;
	private String numeroColegio;
	private Set<DatoMedico> datoMedicos = new HashSet<DatoMedico>(0);

	public Medico() {
	}

	public Medico(String matricula, String apellido, String cedulaMedico,
			char estatus, Date fechaIngreso, String nombre, String numeroColegio) {
		this.matricula = matricula;
		this.apellido = apellido;
		this.cedulaMedico = cedulaMedico;
		this.estatus = estatus;
		this.fechaIngreso = fechaIngreso;
		this.nombre = nombre;
		this.numeroColegio = numeroColegio;
	}

	public Medico(String matricula, String apellido, String cedulaMedico,
			char estatus, Date fechaIngreso, String nombre,
			String numeroColegio, Set<DatoMedico> datoMedicos) {
		this.matricula = matricula;
		this.apellido = apellido;
		this.cedulaMedico = cedulaMedico;
		this.estatus = estatus;
		this.fechaIngreso = fechaIngreso;
		this.nombre = nombre;
		this.numeroColegio = numeroColegio;
		this.datoMedicos = datoMedicos;
	}

	@Id
	@Column(name = "matricula", unique = true, nullable = false)
	public String getMatricula() {
		return this.matricula;
	}

	public void setMatricula(String matricula) {
		this.matricula = matricula;
	}

	@Column(name = "apellido", nullable = false)
	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	@Column(name = "cedula_medico", nullable = false)
	public String getCedulaMedico() {
		return this.cedulaMedico;
	}

	public void setCedulaMedico(String cedulaMedico) {
		this.cedulaMedico = cedulaMedico;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_ingreso", nullable = false, length = 13)
	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "numero_colegio", nullable = false)
	public String getNumeroColegio() {
		return this.numeroColegio;
	}

	public void setNumeroColegio(String numeroColegio) {
		this.numeroColegio = numeroColegio;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "medico")
	public Set<DatoMedico> getDatoMedicos() {
		return this.datoMedicos;
	}

	public void setDatoMedicos(Set<DatoMedico> datoMedicos) {
		this.datoMedicos = datoMedicos;
	}

}
