package modelo;

// Generated 11/01/2012 03:50:04 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ModalidadCompetencia generated by hbm2java
 */
@Entity
@Table(name = "modalidad_competencia", schema = "public")
public class ModalidadCompetencia implements java.io.Serializable {

	private int codigoModalidadCompetencia;
	private TipoCompetencia tipoCompetencia;
	private String nombre;
	private String descripcion;
	private char estatus;
	private Set<Competencia> competencias = new HashSet<Competencia>(0);

	public ModalidadCompetencia() {
	}

	public ModalidadCompetencia(int codigoModalidadCompetencia,
			TipoCompetencia tipoCompetencia, String nombre, char estatus) {
		this.codigoModalidadCompetencia = codigoModalidadCompetencia;
		this.tipoCompetencia = tipoCompetencia;
		this.nombre = nombre;
		this.estatus = estatus;
	}

	public ModalidadCompetencia(int codigoModalidadCompetencia,
			TipoCompetencia tipoCompetencia, String nombre, String descripcion,
			char estatus, Set<Competencia> competencias) {
		this.codigoModalidadCompetencia = codigoModalidadCompetencia;
		this.tipoCompetencia = tipoCompetencia;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.estatus = estatus;
		this.competencias = competencias;
	}

	@Id
	@Column(name = "codigo_modalidad_competencia", unique = true, nullable = false)
	public int getCodigoModalidadCompetencia() {
		return this.codigoModalidadCompetencia;
	}

	public void setCodigoModalidadCompetencia(int codigoModalidadCompetencia) {
		this.codigoModalidadCompetencia = codigoModalidadCompetencia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_tipo_competencia", nullable = false)
	public TipoCompetencia getTipoCompetencia() {
		return this.tipoCompetencia;
	}

	public void setTipoCompetencia(TipoCompetencia tipoCompetencia) {
		this.tipoCompetencia = tipoCompetencia;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modalidadCompetencia")
	public Set<Competencia> getCompetencias() {
		return this.competencias;
	}

	public void setCompetencias(Set<Competencia> competencias) {
		this.competencias = competencias;
	}

}
