package modelo;

// Generated 10/12/2011 11:05:49 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ModalidadCompetencia generated by hbm2java
 */
@Entity
@Table(name = "modalidad_competencia")
public class ModalidadCompetencia implements java.io.Serializable {

	private String codigoModalidadCompetencia;
	private String nombre;
	private Set<TipoModalidadCompetencia> tipoModalidadCompetencias = new HashSet<TipoModalidadCompetencia>(
			0);

	public ModalidadCompetencia() {
	}

	public ModalidadCompetencia(String codigoModalidadCompetencia, String nombre) {
		this.codigoModalidadCompetencia = codigoModalidadCompetencia;
		this.nombre = nombre;
	}

	public ModalidadCompetencia(String codigoModalidadCompetencia,
			String nombre,
			Set<TipoModalidadCompetencia> tipoModalidadCompetencias) {
		this.codigoModalidadCompetencia = codigoModalidadCompetencia;
		this.nombre = nombre;
		this.tipoModalidadCompetencias = tipoModalidadCompetencias;
	}

	@Id
	@Column(name = "codigo_modalidad_competencia", unique = true, nullable = false)
	public String getCodigoModalidadCompetencia() {
		return this.codigoModalidadCompetencia;
	}

	public void setCodigoModalidadCompetencia(String codigoModalidadCompetencia) {
		this.codigoModalidadCompetencia = codigoModalidadCompetencia;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modalidadCompetencia")
	public Set<TipoModalidadCompetencia> getTipoModalidadCompetencias() {
		return this.tipoModalidadCompetencias;
	}

	public void setTipoModalidadCompetencias(
			Set<TipoModalidadCompetencia> tipoModalidadCompetencias) {
		this.tipoModalidadCompetencias = tipoModalidadCompetencias;
	}

}
