package modelo;

// Generated 28/12/2011 03:24:38 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Nomina generated by hbm2java
 */
@Entity
@Table(name = "nomina", schema = "public")
public class Nomina implements java.io.Serializable {

	private String codigoNomina;
	private DatoBasico datoBasico;
	private CuentaPagar cuentaPagar;
	private Date fechaInicio;
	private Date fechaFin;
	private char estatus;
	private Set<Movimiento> movimientos = new HashSet<Movimiento>(0);

	public Nomina() {
	}

	public Nomina(DatoBasico datoBasico, CuentaPagar cuentaPagar,
			Date fechaInicio, Date fechaFin, char estatus) {
		this.datoBasico = datoBasico;
		this.cuentaPagar = cuentaPagar;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.estatus = estatus;
	}

	public Nomina(DatoBasico datoBasico, CuentaPagar cuentaPagar,
			Date fechaInicio, Date fechaFin, char estatus,
			Set<Movimiento> movimientos) {
		this.datoBasico = datoBasico;
		this.cuentaPagar = cuentaPagar;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.estatus = estatus;
		this.movimientos = movimientos;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "cuentaPagar"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "codigo_nomina", unique = true, nullable = false)
	public String getCodigoNomina() {
		return this.codigoNomina;
	}

	public void setCodigoNomina(String codigoNomina) {
		this.codigoNomina = codigoNomina;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_tipo_nomina", nullable = false)
	public DatoBasico getDatoBasico() {
		return this.datoBasico;
	}

	public void setDatoBasico(DatoBasico datoBasico) {
		this.datoBasico = datoBasico;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public CuentaPagar getCuentaPagar() {
		return this.cuentaPagar;
	}

	public void setCuentaPagar(CuentaPagar cuentaPagar) {
		this.cuentaPagar = cuentaPagar;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_inicio", nullable = false, length = 13)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_fin", nullable = false, length = 13)
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nomina")
	public Set<Movimiento> getMovimientos() {
		return this.movimientos;
	}

	public void setMovimientos(Set<Movimiento> movimientos) {
		this.movimientos = movimientos;
	}

}
