package modelo;

// Generated 11/01/2012 03:50:04 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NotaEntrega generated by hbm2java
 */
@Entity
@Table(name = "nota_entrega", schema = "public")
public class NotaEntrega implements java.io.Serializable {

	private NotaEntregaId id;
	private DocumentoAcreedor documentoAcreedor;
	private CuentaPagar cuentaPagar;
	private Date fechaRecepcion;
	private Set<RecepcionMaterial> recepcionMaterials = new HashSet<RecepcionMaterial>(
			0);

	public NotaEntrega() {
	}

	public NotaEntrega(NotaEntregaId id, DocumentoAcreedor documentoAcreedor,
			CuentaPagar cuentaPagar, Date fechaRecepcion) {
		this.id = id;
		this.documentoAcreedor = documentoAcreedor;
		this.cuentaPagar = cuentaPagar;
		this.fechaRecepcion = fechaRecepcion;
	}

	public NotaEntrega(NotaEntregaId id, DocumentoAcreedor documentoAcreedor,
			CuentaPagar cuentaPagar, Date fechaRecepcion,
			Set<RecepcionMaterial> recepcionMaterials) {
		this.id = id;
		this.documentoAcreedor = documentoAcreedor;
		this.cuentaPagar = cuentaPagar;
		this.fechaRecepcion = fechaRecepcion;
		this.recepcionMaterials = recepcionMaterials;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codigoNotaEntrega", column = @Column(name = "codigo_nota_entrega", nullable = false)),
			@AttributeOverride(name = "origen", column = @Column(name = "origen", nullable = false)) })
	public NotaEntregaId getId() {
		return this.id;
	}

	public void setId(NotaEntregaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_documento_acreedor", nullable = false)
	public DocumentoAcreedor getDocumentoAcreedor() {
		return this.documentoAcreedor;
	}

	public void setDocumentoAcreedor(DocumentoAcreedor documentoAcreedor) {
		this.documentoAcreedor = documentoAcreedor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "origen", nullable = false, insertable = false, updatable = false)
	public CuentaPagar getCuentaPagar() {
		return this.cuentaPagar;
	}

	public void setCuentaPagar(CuentaPagar cuentaPagar) {
		this.cuentaPagar = cuentaPagar;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_recepcion", nullable = false, length = 13)
	public Date getFechaRecepcion() {
		return this.fechaRecepcion;
	}

	public void setFechaRecepcion(Date fechaRecepcion) {
		this.fechaRecepcion = fechaRecepcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "notaEntrega")
	public Set<RecepcionMaterial> getRecepcionMaterials() {
		return this.recepcionMaterials;
	}

	public void setRecepcionMaterials(Set<RecepcionMaterial> recepcionMaterials) {
		this.recepcionMaterials = recepcionMaterials;
	}

}
