package modelo;

<<<<<<< HEAD
// Generated 25/01/2012 12:32:42 AM by Hibernate Tools 3.4.0.CR1
=======
// Generated 24/01/2012 04:28:30 AM by Hibernate Tools 3.4.0.CR1
>>>>>>> 7d4823278d0a354855f5032a99e2b48c65b33e7f

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PerfilGrupoId generated by hbm2java
 */
@Embeddable
public class PerfilGrupoId implements java.io.Serializable {

	private int codigoPerfil;
	private int codigoGrupo;

	public PerfilGrupoId() {
	}

	public PerfilGrupoId(int codigoPerfil, int codigoGrupo) {
		this.codigoPerfil = codigoPerfil;
		this.codigoGrupo = codigoGrupo;
	}

	@Column(name = "codigo_perfil", nullable = false)
	public int getCodigoPerfil() {
		return this.codigoPerfil;
	}

	public void setCodigoPerfil(int codigoPerfil) {
		this.codigoPerfil = codigoPerfil;
	}

	@Column(name = "codigo_grupo", nullable = false)
	public int getCodigoGrupo() {
		return this.codigoGrupo;
	}

	public void setCodigoGrupo(int codigoGrupo) {
		this.codigoGrupo = codigoGrupo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PerfilGrupoId))
			return false;
		PerfilGrupoId castOther = (PerfilGrupoId) other;

		return (this.getCodigoPerfil() == castOther.getCodigoPerfil())
				&& (this.getCodigoGrupo() == castOther.getCodigoGrupo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoPerfil();
		result = 37 * result + this.getCodigoGrupo();
		return result;
	}

}
