package modelo;
// Generated 16/12/2011 10:21:41 AM by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Personal generated by hbm2java
 */
@Entity
@Table(name="personal"
)
public class Personal  implements java.io.Serializable {


     private String cedulaRif;
     private String nombre;
     private String apellido;
     private Set<PersonalJuego> personalJuegos = new HashSet<PersonalJuego>(0);

    public Personal() {
    }

	
    public Personal(String cedulaRif, String nombre, String apellido) {
        this.cedulaRif = cedulaRif;
        this.nombre = nombre;
        this.apellido = apellido;
    }
    public Personal(String cedulaRif, String nombre, String apellido, Set<PersonalJuego> personalJuegos) {
       this.cedulaRif = cedulaRif;
       this.nombre = nombre;
       this.apellido = apellido;
       this.personalJuegos = personalJuegos;
    }
   
     @Id 

    
    @Column(name="cedula_rif", unique=true, nullable=false)
    public String getCedulaRif() {
        return this.cedulaRif;
    }
    
    public void setCedulaRif(String cedulaRif) {
        this.cedulaRif = cedulaRif;
    }

    
    @Column(name="nombre", nullable=false)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="apellido", nullable=false)
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="personal")
    public Set<PersonalJuego> getPersonalJuegos() {
        return this.personalJuegos;
    }
    
    public void setPersonalJuegos(Set<PersonalJuego> personalJuegos) {
        this.personalJuegos = personalJuegos;
    }




}


