package modelo;

// Generated 14/02/2012 08:24:27 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PersonalActividad generated by hbm2java
 */
@Entity
@Table(name = "personal_actividad", schema = "public")
public class PersonalActividad implements java.io.Serializable {

	private int codigoPersonalActividad;
	private Actividad actividad;
	private Personal personal;
	private char estatus;
	private Set<TareaActividad> tareaActividads = new HashSet<TareaActividad>(0);

	public PersonalActividad() {
	}

	public PersonalActividad(int codigoPersonalActividad, Actividad actividad,
			Personal personal, char estatus) {
		this.codigoPersonalActividad = codigoPersonalActividad;
		this.actividad = actividad;
		this.personal = personal;
		this.estatus = estatus;
	}

	public PersonalActividad(int codigoPersonalActividad, Actividad actividad,
			Personal personal, char estatus, Set<TareaActividad> tareaActividads) {
		this.codigoPersonalActividad = codigoPersonalActividad;
		this.actividad = actividad;
		this.personal = personal;
		this.estatus = estatus;
		this.tareaActividads = tareaActividads;
	}

	@Id
	@Column(name = "codigo_personal_actividad", unique = true, nullable = false)
	public int getCodigoPersonalActividad() {
		return this.codigoPersonalActividad;
	}

	public void setCodigoPersonalActividad(int codigoPersonalActividad) {
		this.codigoPersonalActividad = codigoPersonalActividad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_actividad", nullable = false)
	public Actividad getActividad() {
		return this.actividad;
	}

	public void setActividad(Actividad actividad) {
		this.actividad = actividad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cedula_rif", nullable = false)
	public Personal getPersonal() {
		return this.personal;
	}

	public void setPersonal(Personal personal) {
		this.personal = personal;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personalActividad")
	public Set<TareaActividad> getTareaActividads() {
		return this.tareaActividads;
	}

	public void setTareaActividads(Set<TareaActividad> tareaActividads) {
		this.tareaActividads = tareaActividads;
	}

}
