package modelo;

// Generated Dec 23, 2011 1:26:53 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PersonalJuegoId generated by hbm2java
 */
@Embeddable
public class PersonalJuegoId implements java.io.Serializable {

	private int codigoJuego1;
	private String cedulaRif;

	public PersonalJuegoId() {
	}

	public PersonalJuegoId(int codigoJuego1, String cedulaRif) {
		this.codigoJuego1 = codigoJuego1;
		this.cedulaRif = cedulaRif;
	}

	@Column(name = "codigo_juego1", nullable = false)
	public int getCodigoJuego1() {
		return this.codigoJuego1;
	}

	public void setCodigoJuego1(int codigoJuego1) {
		this.codigoJuego1 = codigoJuego1;
	}

	@Column(name = "cedula_rif", nullable = false)
	public String getCedulaRif() {
		return this.cedulaRif;
	}

	public void setCedulaRif(String cedulaRif) {
		this.cedulaRif = cedulaRif;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PersonalJuegoId))
			return false;
		PersonalJuegoId castOther = (PersonalJuegoId) other;

		return (this.getCodigoJuego1() == castOther.getCodigoJuego1())
				&& ((this.getCedulaRif() == castOther.getCedulaRif()) || (this
						.getCedulaRif() != null
						&& castOther.getCedulaRif() != null && this
						.getCedulaRif().equals(castOther.getCedulaRif())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoJuego1();
		result = 37 * result
				+ (getCedulaRif() == null ? 0 : this.getCedulaRif().hashCode());
		return result;
	}

}
