package modelo;

<<<<<<< HEAD
=======
<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> 9d67536bdd2e3b33aa6400eb3bb09741a4535bb0
>>>>>>> 873ccb018e72b00b831aa9284cc0745bd1c2d514
// Generated 25/01/2012 12:32:42 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
<<<<<<< HEAD
=======
<<<<<<< HEAD
=======
=======
// Generated 24/01/2012 04:28:30 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
>>>>>>> 7d4823278d0a354855f5032a99e2b48c65b33e7f
>>>>>>> 9d67536bdd2e3b33aa6400eb3bb09741a4535bb0
>>>>>>> 873ccb018e72b00b831aa9284cc0745bd1c2d514
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PersonalActividad generated by hbm2java
 */
@Entity
@Table(name = "personal_actividad", schema = "public")
public class PersonalActividad implements java.io.Serializable {

<<<<<<< HEAD
	private int codigoPersonalActividad;
=======
<<<<<<< HEAD
	private int codigoPersonalActividad;
=======
<<<<<<< HEAD
	private int codigoPersonalActividad;
=======
	private PersonalActividadId id;
>>>>>>> 7d4823278d0a354855f5032a99e2b48c65b33e7f
>>>>>>> 9d67536bdd2e3b33aa6400eb3bb09741a4535bb0
>>>>>>> 873ccb018e72b00b831aa9284cc0745bd1c2d514
	private Actividad actividad;
	private Personal personal;
	private char estatus;
	private Set<TareaActividad> tareaActividads = new HashSet<TareaActividad>(0);

	public PersonalActividad() {
	}

<<<<<<< HEAD
	public PersonalActividad(int codigoPersonalActividad, Actividad actividad,
			Personal personal, char estatus) {
		this.codigoPersonalActividad = codigoPersonalActividad;
=======
<<<<<<< HEAD
	public PersonalActividad(int codigoPersonalActividad, Actividad actividad,
			Personal personal, char estatus) {
		this.codigoPersonalActividad = codigoPersonalActividad;
=======
<<<<<<< HEAD
	public PersonalActividad(int codigoPersonalActividad, Actividad actividad,
			Personal personal, char estatus) {
		this.codigoPersonalActividad = codigoPersonalActividad;
=======
	public PersonalActividad(PersonalActividadId id, Actividad actividad,
			Personal personal, char estatus) {
		this.id = id;
>>>>>>> 7d4823278d0a354855f5032a99e2b48c65b33e7f
>>>>>>> 9d67536bdd2e3b33aa6400eb3bb09741a4535bb0
>>>>>>> 873ccb018e72b00b831aa9284cc0745bd1c2d514
		this.actividad = actividad;
		this.personal = personal;
		this.estatus = estatus;
	}

<<<<<<< HEAD
	public PersonalActividad(int codigoPersonalActividad, Actividad actividad,
			Personal personal, char estatus, Set<TareaActividad> tareaActividads) {
		this.codigoPersonalActividad = codigoPersonalActividad;
=======
<<<<<<< HEAD
	public PersonalActividad(int codigoPersonalActividad, Actividad actividad,
			Personal personal, char estatus, Set<TareaActividad> tareaActividads) {
		this.codigoPersonalActividad = codigoPersonalActividad;
=======
<<<<<<< HEAD
	public PersonalActividad(int codigoPersonalActividad, Actividad actividad,
			Personal personal, char estatus, Set<TareaActividad> tareaActividads) {
		this.codigoPersonalActividad = codigoPersonalActividad;
=======
	public PersonalActividad(PersonalActividadId id, Actividad actividad,
			Personal personal, char estatus, Set<TareaActividad> tareaActividads) {
		this.id = id;
>>>>>>> 7d4823278d0a354855f5032a99e2b48c65b33e7f
>>>>>>> 9d67536bdd2e3b33aa6400eb3bb09741a4535bb0
>>>>>>> 873ccb018e72b00b831aa9284cc0745bd1c2d514
		this.actividad = actividad;
		this.personal = personal;
		this.estatus = estatus;
		this.tareaActividads = tareaActividads;
	}

<<<<<<< HEAD
=======
<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> 9d67536bdd2e3b33aa6400eb3bb09741a4535bb0
>>>>>>> 873ccb018e72b00b831aa9284cc0745bd1c2d514
	@Id
	@Column(name = "codigo_personal_actividad", unique = true, nullable = false)
	public int getCodigoPersonalActividad() {
		return this.codigoPersonalActividad;
	}

	public void setCodigoPersonalActividad(int codigoPersonalActividad) {
		this.codigoPersonalActividad = codigoPersonalActividad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_actividad", nullable = false)
<<<<<<< HEAD
=======
<<<<<<< HEAD
=======
=======
	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cedulaRif", column = @Column(name = "cedula_rif", nullable = false)),
			@AttributeOverride(name = "codigoActividad", column = @Column(name = "codigo_actividad", nullable = false)) })
	public PersonalActividadId getId() {
		return this.id;
	}

	public void setId(PersonalActividadId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_actividad", nullable = false, insertable = false, updatable = false)
>>>>>>> 7d4823278d0a354855f5032a99e2b48c65b33e7f
>>>>>>> 9d67536bdd2e3b33aa6400eb3bb09741a4535bb0
>>>>>>> 873ccb018e72b00b831aa9284cc0745bd1c2d514
	public Actividad getActividad() {
		return this.actividad;
	}

	public void setActividad(Actividad actividad) {
		this.actividad = actividad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
<<<<<<< HEAD
	@JoinColumn(name = "cedula_rif", nullable = false)
=======
<<<<<<< HEAD
	@JoinColumn(name = "cedula_rif", nullable = false)
=======
<<<<<<< HEAD
	@JoinColumn(name = "cedula_rif", nullable = false)
=======
	@JoinColumn(name = "cedula_rif", nullable = false, insertable = false, updatable = false)
>>>>>>> 7d4823278d0a354855f5032a99e2b48c65b33e7f
>>>>>>> 9d67536bdd2e3b33aa6400eb3bb09741a4535bb0
>>>>>>> 873ccb018e72b00b831aa9284cc0745bd1c2d514
	public Personal getPersonal() {
		return this.personal;
	}

	public void setPersonal(Personal personal) {
		this.personal = personal;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personalActividad")
	public Set<TareaActividad> getTareaActividads() {
		return this.tareaActividads;
	}

	public void setTareaActividads(Set<TareaActividad> tareaActividads) {
		this.tareaActividads = tareaActividads;
	}

}
