package modelo;

<<<<<<< HEAD
// Generated 25/01/2012 12:32:42 AM by Hibernate Tools 3.4.0.CR1
=======
// Generated 24/01/2012 04:28:30 AM by Hibernate Tools 3.4.0.CR1
>>>>>>> 7d4823278d0a354855f5032a99e2b48c65b33e7f

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RecepcionMaterialId generated by hbm2java
 */
@Embeddable
public class RecepcionMaterialId implements java.io.Serializable {

	private int codigoMaterial;
	private int codigoNotaEntrega;

	public RecepcionMaterialId() {
	}

	public RecepcionMaterialId(int codigoMaterial, int codigoNotaEntrega) {
		this.codigoMaterial = codigoMaterial;
		this.codigoNotaEntrega = codigoNotaEntrega;
	}

	@Column(name = "codigo_material", nullable = false)
	public int getCodigoMaterial() {
		return this.codigoMaterial;
	}

	public void setCodigoMaterial(int codigoMaterial) {
		this.codigoMaterial = codigoMaterial;
	}

	@Column(name = "codigo_nota_entrega", nullable = false)
	public int getCodigoNotaEntrega() {
		return this.codigoNotaEntrega;
	}

	public void setCodigoNotaEntrega(int codigoNotaEntrega) {
		this.codigoNotaEntrega = codigoNotaEntrega;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RecepcionMaterialId))
			return false;
		RecepcionMaterialId castOther = (RecepcionMaterialId) other;

		return (this.getCodigoMaterial() == castOther.getCodigoMaterial())
				&& (this.getCodigoNotaEntrega() == castOther
						.getCodigoNotaEntrega());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoMaterial();
		result = 37 * result + this.getCodigoNotaEntrega();
		return result;
	}

}
