package modelo;

// Generated 15/12/2011 03:23:59 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Regla generated by hbm2java
 */
@Entity
@Table(name = "regla")
public class Regla implements java.io.Serializable {

	private String codigoRegla;
	private Indicador indicador;
	private DatoBasico datoBasico;
	private String nombre;
	private String criterio;
	private String descripcion;
	private Set<ReglaCategoria> reglaCategorias = new HashSet<ReglaCategoria>(0);

	public Regla() {
	}

	public Regla(String codigoRegla, Indicador indicador,
			DatoBasico datoBasico, String nombre, String criterio,
			String descripcion) {
		this.codigoRegla = codigoRegla;
		this.indicador = indicador;
		this.datoBasico = datoBasico;
		this.nombre = nombre;
		this.criterio = criterio;
		this.descripcion = descripcion;
	}

	public Regla(String codigoRegla, Indicador indicador,
			DatoBasico datoBasico, String nombre, String criterio,
			String descripcion, Set<ReglaCategoria> reglaCategorias) {
		this.codigoRegla = codigoRegla;
		this.indicador = indicador;
		this.datoBasico = datoBasico;
		this.nombre = nombre;
		this.criterio = criterio;
		this.descripcion = descripcion;
		this.reglaCategorias = reglaCategorias;
	}

	@Id
	@Column(name = "codigo_regla", unique = true, nullable = false)
	public String getCodigoRegla() {
		return this.codigoRegla;
	}

	public void setCodigoRegla(String codigoRegla) {
		this.codigoRegla = codigoRegla;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_indicador_regla", nullable = false)
	public Indicador getIndicador() {
		return this.indicador;
	}

	public void setIndicador(Indicador indicador) {
		this.indicador = indicador;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_unidad_medida", nullable = false)
	public DatoBasico getDatoBasico() {
		return this.datoBasico;
	}

	public void setDatoBasico(DatoBasico datoBasico) {
		this.datoBasico = datoBasico;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "criterio", nullable = false)
	public String getCriterio() {
		return this.criterio;
	}

	public void setCriterio(String criterio) {
		this.criterio = criterio;
	}

	@Column(name = "descripcion", nullable = false)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "regla")
	public Set<ReglaCategoria> getReglaCategorias() {
		return this.reglaCategorias;
	}

	public void setReglaCategorias(Set<ReglaCategoria> reglaCategorias) {
		this.reglaCategorias = reglaCategorias;
	}

}
