package modelo;

<<<<<<< HEAD
// Generated 25/01/2012 12:32:42 AM by Hibernate Tools 3.4.0.CR1
=======
// Generated 24/01/2012 04:28:30 AM by Hibernate Tools 3.4.0.CR1
>>>>>>> 7d4823278d0a354855f5032a99e2b48c65b33e7f

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SolicitudMantenimiento generated by hbm2java
 */
@Entity
@Table(name = "solicitud_mantenimiento", schema = "public")
public class SolicitudMantenimiento implements java.io.Serializable {

	private SolicitudMantenimientoId id;
	private Actividad actividad;
	private DatoBasico datoBasico;
<<<<<<< HEAD
	private String descripcionActividad;
=======
>>>>>>> 7d4823278d0a354855f5032a99e2b48c65b33e7f
	private char estatus;

	public SolicitudMantenimiento() {
	}

	public SolicitudMantenimiento(SolicitudMantenimientoId id,
<<<<<<< HEAD
			Actividad actividad, DatoBasico datoBasico,
			String descripcionActividad, char estatus) {
		this.id = id;
		this.actividad = actividad;
		this.datoBasico = datoBasico;
		this.descripcionActividad = descripcionActividad;
=======
			Actividad actividad, DatoBasico datoBasico, char estatus) {
		this.id = id;
		this.actividad = actividad;
		this.datoBasico = datoBasico;
>>>>>>> 7d4823278d0a354855f5032a99e2b48c65b33e7f
		this.estatus = estatus;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codigoSolicitud", column = @Column(name = "codigo_solicitud", nullable = false)),
			@AttributeOverride(name = "codigoActividad", column = @Column(name = "codigo_actividad", nullable = false)) })
	public SolicitudMantenimientoId getId() {
		return this.id;
	}

	public void setId(SolicitudMantenimientoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_actividad", nullable = false, insertable = false, updatable = false)
	public Actividad getActividad() {
		return this.actividad;
	}

	public void setActividad(Actividad actividad) {
		this.actividad = actividad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_prioridad", nullable = false)
	public DatoBasico getDatoBasico() {
		return this.datoBasico;
	}

	public void setDatoBasico(DatoBasico datoBasico) {
		this.datoBasico = datoBasico;
	}

<<<<<<< HEAD
	@Column(name = "descripcion_actividad", nullable = false)
	public String getDescripcionActividad() {
		return this.descripcionActividad;
	}

	public void setDescripcionActividad(String descripcionActividad) {
		this.descripcionActividad = descripcionActividad;
	}

=======
>>>>>>> 7d4823278d0a354855f5032a99e2b48c65b33e7f
	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

}
