package modelo;

// Generated 12/12/2011 09:17:13 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Talla generated by hbm2java
 */
@Entity
@Table(name = "talla")
public class Talla implements java.io.Serializable {

	private String codigoTalla;
	private TipoIndumentaria tipoIndumentaria;
	private char estatus;
	private String talla;
	private Set<Jugador> jugadors = new HashSet<Jugador>(0);

	public Talla() {
	}

	public Talla(String codigoTalla, TipoIndumentaria tipoIndumentaria,
			char estatus, String talla) {
		this.codigoTalla = codigoTalla;
		this.tipoIndumentaria = tipoIndumentaria;
		this.estatus = estatus;
		this.talla = talla;
	}

	public Talla(String codigoTalla, TipoIndumentaria tipoIndumentaria,
			char estatus, String talla, Set<Jugador> jugadors) {
		this.codigoTalla = codigoTalla;
		this.tipoIndumentaria = tipoIndumentaria;
		this.estatus = estatus;
		this.talla = talla;
		this.jugadors = jugadors;
	}

	@Id
	@Column(name = "codigo_talla", unique = true, nullable = false)
	public String getCodigoTalla() {
		return this.codigoTalla;
	}

	public void setCodigoTalla(String codigoTalla) {
		this.codigoTalla = codigoTalla;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_indumentaria", nullable = false)
	public TipoIndumentaria getTipoIndumentaria() {
		return this.tipoIndumentaria;
	}

	public void setTipoIndumentaria(TipoIndumentaria tipoIndumentaria) {
		this.tipoIndumentaria = tipoIndumentaria;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@Column(name = "talla", nullable = false)
	public String getTalla() {
		return this.talla;
	}

	public void setTalla(String talla) {
		this.talla = talla;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "talla")
	public Set<Jugador> getJugadors() {
		return this.jugadors;
	}

	public void setJugadors(Set<Jugador> jugadors) {
		this.jugadors = jugadors;
	}

}
