package modelo;

<<<<<<< HEAD
// Generated 25/01/2012 12:32:42 AM by Hibernate Tools 3.4.0.CR1
=======
// Generated 24/01/2012 04:28:30 AM by Hibernate Tools 3.4.0.CR1
>>>>>>> 7d4823278d0a354855f5032a99e2b48c65b33e7f

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
<<<<<<< HEAD
=======
import javax.persistence.JoinColumns;
>>>>>>> 7d4823278d0a354855f5032a99e2b48c65b33e7f
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TareaActividad generated by hbm2java
 */
@Entity
@Table(name = "tarea_actividad", schema = "public")
public class TareaActividad implements java.io.Serializable {

	private int codigoTareaActividad;
	private DatoBasico datoBasico;
	private Actividad actividad;
	private PersonalActividad personalActividad;
	private char estatus;
<<<<<<< HEAD
	private boolean tareaEjecutada;
=======
>>>>>>> 7d4823278d0a354855f5032a99e2b48c65b33e7f

	public TareaActividad() {
	}

	public TareaActividad(int codigoTareaActividad, DatoBasico datoBasico,
			Actividad actividad, PersonalActividad personalActividad,
<<<<<<< HEAD
			char estatus, boolean tareaEjecutada) {
=======
			char estatus) {
>>>>>>> 7d4823278d0a354855f5032a99e2b48c65b33e7f
		this.codigoTareaActividad = codigoTareaActividad;
		this.datoBasico = datoBasico;
		this.actividad = actividad;
		this.personalActividad = personalActividad;
		this.estatus = estatus;
<<<<<<< HEAD
		this.tareaEjecutada = tareaEjecutada;
=======
>>>>>>> 7d4823278d0a354855f5032a99e2b48c65b33e7f
	}

	@Id
	@Column(name = "codigo_tarea_actividad", unique = true, nullable = false)
	public int getCodigoTareaActividad() {
		return this.codigoTareaActividad;
	}

	public void setCodigoTareaActividad(int codigoTareaActividad) {
		this.codigoTareaActividad = codigoTareaActividad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_tarea", nullable = false)
	public DatoBasico getDatoBasico() {
		return this.datoBasico;
	}

	public void setDatoBasico(DatoBasico datoBasico) {
		this.datoBasico = datoBasico;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_actividad", nullable = false)
	public Actividad getActividad() {
		return this.actividad;
	}

	public void setActividad(Actividad actividad) {
		this.actividad = actividad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
<<<<<<< HEAD
	@JoinColumn(name = "codigo_personal_actividad", nullable = false)
=======
	@JoinColumns({
			@JoinColumn(name = "cedula_rif", referencedColumnName = "cedula_rif", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "codigo_actividad", referencedColumnName = "codigo_actividad", nullable = false, insertable = false, updatable = false) })
>>>>>>> 7d4823278d0a354855f5032a99e2b48c65b33e7f
	public PersonalActividad getPersonalActividad() {
		return this.personalActividad;
	}

	public void setPersonalActividad(PersonalActividad personalActividad) {
		this.personalActividad = personalActividad;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

<<<<<<< HEAD
	@Column(name = "tarea_ejecutada", nullable = false)
	public boolean isTareaEjecutada() {
		return this.tareaEjecutada;
	}

	public void setTareaEjecutada(boolean tareaEjecutada) {
		this.tareaEjecutada = tareaEjecutada;
	}

=======
>>>>>>> 7d4823278d0a354855f5032a99e2b48c65b33e7f
}
