package modelo;

// Generated 15/12/2011 03:23:59 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoDato generated by hbm2java
 */
@Entity
@Table(name = "tipo_dato")
public class TipoDato implements java.io.Serializable {

	private String codigoTipoDato;
	private TipoDato tipoDato;
	private String nombre;
	private String descripcion;
	private char estatus;
	private Set<DatoBasico> datoBasicos = new HashSet<DatoBasico>(0);
	private Set<TipoDato> tipoDatos = new HashSet<TipoDato>(0);

	public TipoDato() {
	}

	public TipoDato(String codigoTipoDato, TipoDato tipoDato, String nombre,
			String descripcion, char estatus) {
		this.codigoTipoDato = codigoTipoDato;
		this.tipoDato = tipoDato;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.estatus = estatus;
	}

	public TipoDato(String codigoTipoDato, TipoDato tipoDato, String nombre,
			String descripcion, char estatus, Set<DatoBasico> datoBasicos,
			Set<TipoDato> tipoDatos) {
		this.codigoTipoDato = codigoTipoDato;
		this.tipoDato = tipoDato;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.estatus = estatus;
		this.datoBasicos = datoBasicos;
		this.tipoDatos = tipoDatos;
	}

	@Id
	@Column(name = "codigo_tipo_dato", unique = true, nullable = false)
	public String getCodigoTipoDato() {
		return this.codigoTipoDato;
	}

	public void setCodigoTipoDato(String codigoTipoDato) {
		this.codigoTipoDato = codigoTipoDato;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parent_codigo_tipo_dato", nullable = false)
	public TipoDato getTipoDato() {
		return this.tipoDato;
	}

	public void setTipoDato(TipoDato tipoDato) {
		this.tipoDato = tipoDato;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", nullable = false)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoDato")
	public Set<DatoBasico> getDatoBasicos() {
		return this.datoBasicos;
	}

	public void setDatoBasicos(Set<DatoBasico> datoBasicos) {
		this.datoBasicos = datoBasicos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoDato")
	public Set<TipoDato> getTipoDatos() {
		return this.tipoDatos;
	}

	public void setTipoDatos(Set<TipoDato> tipoDatos) {
		this.tipoDatos = tipoDatos;
	}

}
