package modelo;

<<<<<<< HEAD
// Generated 25/01/2012 12:32:42 AM by Hibernate Tools 3.4.0.CR1
=======
<<<<<<< HEAD
// Generated 25/01/2012 12:32:42 AM by Hibernate Tools 3.4.0.CR1
=======
// Generated 24/01/2012 04:28:30 AM by Hibernate Tools 3.4.0.CR1
>>>>>>> 7d4823278d0a354855f5032a99e2b48c65b33e7f
>>>>>>> 9d67536bdd2e3b33aa6400eb3bb09741a4535bb0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoIngreso generated by hbm2java
 */
@Entity
@Table(name = "tipo_ingreso", schema = "public")
public class TipoIngreso implements java.io.Serializable {

	private int codigoTipoIngreso;
	private DatoBasico datoBasicoByCodigoPeriodicidad;
	private DatoBasico datoBasicoByCodigoTipo;
	private String descripcion;
	private Double monto;
	private char estatus;
<<<<<<< HEAD
	private char aplicacion;
=======
<<<<<<< HEAD
	private char aplicacion;
=======
>>>>>>> 7d4823278d0a354855f5032a99e2b48c65b33e7f
>>>>>>> 9d67536bdd2e3b33aa6400eb3bb09741a4535bb0
	private Set<DocumentoAcreedor> documentoAcreedors = new HashSet<DocumentoAcreedor>(
			0);

	public TipoIngreso() {
	}

	public TipoIngreso(int codigoTipoIngreso,
<<<<<<< HEAD
			DatoBasico datoBasicoByCodigoTipo, String descripcion,
			char estatus, char aplicacion) {
=======
<<<<<<< HEAD
			DatoBasico datoBasicoByCodigoTipo, String descripcion,
			char estatus, char aplicacion) {
=======
			DatoBasico datoBasicoByCodigoTipo, String descripcion, char estatus) {
>>>>>>> 7d4823278d0a354855f5032a99e2b48c65b33e7f
>>>>>>> 9d67536bdd2e3b33aa6400eb3bb09741a4535bb0
		this.codigoTipoIngreso = codigoTipoIngreso;
		this.datoBasicoByCodigoTipo = datoBasicoByCodigoTipo;
		this.descripcion = descripcion;
		this.estatus = estatus;
<<<<<<< HEAD
		this.aplicacion = aplicacion;
=======
<<<<<<< HEAD
		this.aplicacion = aplicacion;
=======
>>>>>>> 7d4823278d0a354855f5032a99e2b48c65b33e7f
>>>>>>> 9d67536bdd2e3b33aa6400eb3bb09741a4535bb0
	}

	public TipoIngreso(int codigoTipoIngreso,
			DatoBasico datoBasicoByCodigoPeriodicidad,
			DatoBasico datoBasicoByCodigoTipo, String descripcion,
<<<<<<< HEAD
			Double monto, char estatus, char aplicacion,
=======
<<<<<<< HEAD
			Double monto, char estatus, char aplicacion,
=======
			Double monto, char estatus,
>>>>>>> 7d4823278d0a354855f5032a99e2b48c65b33e7f
>>>>>>> 9d67536bdd2e3b33aa6400eb3bb09741a4535bb0
			Set<DocumentoAcreedor> documentoAcreedors) {
		this.codigoTipoIngreso = codigoTipoIngreso;
		this.datoBasicoByCodigoPeriodicidad = datoBasicoByCodigoPeriodicidad;
		this.datoBasicoByCodigoTipo = datoBasicoByCodigoTipo;
		this.descripcion = descripcion;
		this.monto = monto;
		this.estatus = estatus;
<<<<<<< HEAD
		this.aplicacion = aplicacion;
=======
<<<<<<< HEAD
		this.aplicacion = aplicacion;
=======
>>>>>>> 7d4823278d0a354855f5032a99e2b48c65b33e7f
>>>>>>> 9d67536bdd2e3b33aa6400eb3bb09741a4535bb0
		this.documentoAcreedors = documentoAcreedors;
	}

	@Id
	@Column(name = "codigo_tipo_ingreso", unique = true, nullable = false)
	public int getCodigoTipoIngreso() {
		return this.codigoTipoIngreso;
	}

	public void setCodigoTipoIngreso(int codigoTipoIngreso) {
		this.codigoTipoIngreso = codigoTipoIngreso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_periodicidad")
	public DatoBasico getDatoBasicoByCodigoPeriodicidad() {
		return this.datoBasicoByCodigoPeriodicidad;
	}

	public void setDatoBasicoByCodigoPeriodicidad(
			DatoBasico datoBasicoByCodigoPeriodicidad) {
		this.datoBasicoByCodigoPeriodicidad = datoBasicoByCodigoPeriodicidad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_tipo", nullable = false)
	public DatoBasico getDatoBasicoByCodigoTipo() {
		return this.datoBasicoByCodigoTipo;
	}

	public void setDatoBasicoByCodigoTipo(DatoBasico datoBasicoByCodigoTipo) {
		this.datoBasicoByCodigoTipo = datoBasicoByCodigoTipo;
	}

	@Column(name = "descripcion", nullable = false)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "monto", precision = 17, scale = 17)
	public Double getMonto() {
		return this.monto;
	}

	public void setMonto(Double monto) {
		this.monto = monto;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> 9d67536bdd2e3b33aa6400eb3bb09741a4535bb0
	@Column(name = "aplicacion", nullable = false, length = 1)
	public char getAplicacion() {
		return this.aplicacion;
	}

	public void setAplicacion(char aplicacion) {
		this.aplicacion = aplicacion;
	}

<<<<<<< HEAD
=======
=======
>>>>>>> 7d4823278d0a354855f5032a99e2b48c65b33e7f
>>>>>>> 9d67536bdd2e3b33aa6400eb3bb09741a4535bb0
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoIngreso")
	public Set<DocumentoAcreedor> getDocumentoAcreedors() {
		return this.documentoAcreedors;
	}

	public void setDocumentoAcreedors(Set<DocumentoAcreedor> documentoAcreedors) {
		this.documentoAcreedors = documentoAcreedors;
	}

}
