package modelo;

// Generated 14/12/2011 05:11:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoLogro generated by hbm2java
 */
@Entity
@Table(name = "tipo_logro")
public class TipoLogro implements java.io.Serializable {

	private String codigoLogro;
	private String nombre;
	private char estatus;
	private Set<DatoDeportivo> datoDeportivos = new HashSet<DatoDeportivo>(0);
	private Set<DatoDeportivo> datoDeportivos_1 = new HashSet<DatoDeportivo>(0);

	public TipoLogro() {
	}

	public TipoLogro(String codigoLogro, String nombre, char estatus) {
		this.codigoLogro = codigoLogro;
		this.nombre = nombre;
		this.estatus = estatus;
	}

	public TipoLogro(String codigoLogro, String nombre, char estatus,
			Set<DatoDeportivo> datoDeportivos,
			Set<DatoDeportivo> datoDeportivos_1) {
		this.codigoLogro = codigoLogro;
		this.nombre = nombre;
		this.estatus = estatus;
		this.datoDeportivos = datoDeportivos;
		this.datoDeportivos_1 = datoDeportivos_1;
	}

	@Id
	@Column(name = "codigo_logro", unique = true, nullable = false)
	public String getCodigoLogro() {
		return this.codigoLogro;
	}

	public void setCodigoLogro(String codigoLogro) {
		this.codigoLogro = codigoLogro;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "estatus", nullable = false, length = 1)
	public char getEstatus() {
		return this.estatus;
	}

	public void setEstatus(char estatus) {
		this.estatus = estatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoLogro")
	public Set<DatoDeportivo> getDatoDeportivos() {
		return this.datoDeportivos;
	}

	public void setDatoDeportivos(Set<DatoDeportivo> datoDeportivos) {
		this.datoDeportivos = datoDeportivos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoLogro")
	public Set<DatoDeportivo> getDatoDeportivos_1() {
		return this.datoDeportivos_1;
	}

	public void setDatoDeportivos_1(Set<DatoDeportivo> datoDeportivos_1) {
		this.datoDeportivos_1 = datoDeportivos_1;
	}

}
