package modelo;

// Generated 15/12/2011 03:23:59 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UmpireJuego generated by hbm2java
 */
@Entity
@Table(name = "umpire_juego")
public class UmpireJuego implements java.io.Serializable {

	private UmpireJuegoId id;
	private DatoBasico datoBasicoByCodigoUmpire;
	private Juego juego;
	private DatoBasico datoBasicoByCodigoPosicion;

	public UmpireJuego() {
	}

	public UmpireJuego(UmpireJuegoId id, DatoBasico datoBasicoByCodigoUmpire,
			Juego juego, DatoBasico datoBasicoByCodigoPosicion) {
		this.id = id;
		this.datoBasicoByCodigoUmpire = datoBasicoByCodigoUmpire;
		this.juego = juego;
		this.datoBasicoByCodigoPosicion = datoBasicoByCodigoPosicion;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "codigoJuego", column = @Column(name = "codigo_juego", nullable = false)),
			@AttributeOverride(name = "codigoUmpire", column = @Column(name = "codigo_umpire", nullable = false)) })
	public UmpireJuegoId getId() {
		return this.id;
	}

	public void setId(UmpireJuegoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_umpire", nullable = false, insertable = false, updatable = false)
	public DatoBasico getDatoBasicoByCodigoUmpire() {
		return this.datoBasicoByCodigoUmpire;
	}

	public void setDatoBasicoByCodigoUmpire(DatoBasico datoBasicoByCodigoUmpire) {
		this.datoBasicoByCodigoUmpire = datoBasicoByCodigoUmpire;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_juego", nullable = false, insertable = false, updatable = false)
	public Juego getJuego() {
		return this.juego;
	}

	public void setJuego(Juego juego) {
		this.juego = juego;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo_posicion", nullable = false)
	public DatoBasico getDatoBasicoByCodigoPosicion() {
		return this.datoBasicoByCodigoPosicion;
	}

	public void setDatoBasicoByCodigoPosicion(
			DatoBasico datoBasicoByCodigoPosicion) {
		this.datoBasicoByCodigoPosicion = datoBasicoByCodigoPosicion;
	}

}
